### ISSUE TITLE
vertex group weights + random, crashing

### ISSUE THREAD

**Issue by JLiebo** [nortikin/sverchok#774] opened 2016-04-20 17:12 UTC
Hi guys, 

Sorry if this isn't the best way to contact you (couldn't find a specific way on the various forums etc). I've recently started using Sverchok and love it, but I'm noticing it crashing on me in a few instances, and/or it'll start running very slow. The most recent just happened when working with a vert group weight and random node. I'm attaching a crash report for you, in the case that it'll help, and I'm also attaching a screenshot of the node set up.

I'm wondering though if I'm simply not using the right set up? I've got the latest Sverchok with Blender 2.77 and Python 3.5 running on OS X El Capitan, and GPU is an AMD Radeon HD 6750M. Thanks ahead for your time on this, and I appreciate the work you've put into this app.

![screen shot 2016-04-20 at 1 07 51 pm](https://cloud.githubusercontent.com/assets/18488675/14683560/61dc98d2-06f9-11e6-923c-3376028fe2cb.png)

see crash dump here: https://gist.github.com/zeffii/40f2f48cf04fc46e331672aae7afeb31

**Comment by zeffii** [comment] 2016-04-20 18:00
Welcome @JLiebo --
likely only the first thread is of interest, none of Blender's Python execution by Sverchok is multithreaded yet. The crash report is interesting to read, but unfortunately doesn't pinpoint a possible culprit.

Maybe you could attach a `.blend` with instructions by which to reproduce the crash?

**Comment by JLiebo** [comment] 2016-04-20 18:17
Thanks @zeffii –
Kinda figured on the report's thread. Yes, I'll get a `.blend` file together for crash reproduction.

**Comment by JLiebo** [comment] 2016-04-20 21:26
@zeffii –

Of course now I can't get it to crash on me! I, can, however get it to freeze (upwards of 15min. at times) as it does more than it crashes. I'm attaching a *blend* file, which, while different in terms of nodes, caused the latest freeze up, as well as another screenshot. What caused the seemingly infinite hang is when I toggled the `separate` to the `off` position in a *Center Polygons* node. I wonder if you can recreate the issue? Really want to figure out whether this is just a memory issue with the existing poly count of the `object` I'm trying to operate on, or something more is at hand. I've already tried changing *draw modes* etc in *User Pref*, but that's not helping.

Any thoughts or similar are much appreciated. 

[freeze-up_01.blend.zip](https://github.com/nortikin/sverchok/files/228837/freeze-up_01.blend.zip)



![freeze shot](https://cloud.githubusercontent.com/assets/18488675/14690930/8d0061c4-071c-11e6-883f-b7ae33badd7e.png)

**Comment by zeffii** [comment] 2016-04-21 08:02
Thanks for making the `.blend`. Whether it can be fixed easily is too early to determine, but I can give some tips.

![image](https://cloud.githubusercontent.com/assets/619340/14701704/e90f9e82-07a6-11e6-8521-5fe644cdd48d.png)


 1. Start Blender from a console to make any of Sverchok's debug information visible .
 2. Sometimes a freeze can be mitigated by clicking into that console window and hitting enter. (I don't know why this works, but I don't think it's coincidence that it has worked for me in the past)

i've edited your original first post and made a linked-gist of the crash report, else is slows down the page loading on this issues tracker.

This `.blend` won't even load on this machine (slow netbook with 2gb of ram) -- will have to import some other way :)

**Comment by zeffii** [comment] 2016-04-21 08:23
this Plane object doesn't strike me as problematic , relatively low poly count..

![image](https://cloud.githubusercontent.com/assets/619340/14702079/d344d642-07a8-11e6-958b-66dc1344211a.png)

I have not used the VertexGroups feature in Blender / Sverchok (I think it was @Kosvor / @nortikin  who implemented it?

From the console, this error does show:
```python
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 318, in do_update_general
    node.process()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\number\formula2.py", line 109, in process
    r = self.inte(vecs, code_formula, list_mult, 3)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\number\formula2.py", line 123, in inte
    out2.append(self.calc_item(x, formula, new_list_n, j, k, q))
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\number\formula2.py", line 145, in calc_item
    return eval(formula)
  File "<syntax-tree>", line 1, in <module>
Node Formula2 had exception a float is required
```
leading me to believe a float should be used (5.0 instead of 5) in that Formula, but that also shouldn't be the problem..

**Comment by zeffii** [comment] 2016-04-21 08:25
I think to debug this I'd delete most of Plane's geometry anyway and `.append` the object and the nodetree in a new `.blend` Just to get a sense of what happens where there's really not much geometry.

**Comment by zeffii** [comment] 2016-04-21 08:43
with 80 faces (vertex groups) , this produces 320 individual (separated) points

![image](https://cloud.githubusercontent.com/assets/619340/14702844/fd384d72-07ac-11e6-91e3-4a3573cd74c9.png)


the original object has 808 such groups, if the growth is proportional (80->320 = 4 ) then that's 808*4 =3232 separate points , still not a lot,  Maybe this is pushing a limit somewhere, where the overhead for each new list far exceeds the value of separating each result..

**Comment by JLiebo** [comment] 2016-04-21 15:36
Thanks in return for taking a look thus far, @zeffii 
Nice call on starting Blender from a terminal. (I like the "Have a nice day with sverchok" touch:)) Starting up this way right now, and it's already really helpful just seeing the live debug info. Yes, interesting that you were receiving `Node Formula2 had exception a float is required` because so far I don't have any warnings coming in from the console w/ the `* 5` as opposed to the *integer value* `5.0`. 

Similarly, I, too, didn't originally think the poly count was too high, and this is what made me suspicious that something else was at play. I'm gonna go in and see if creating the object in question from the ground up in **sverchok** (as opposed to piping it in through an `Objects_in`) will help; though, in candor it would of course be good to have the ability of operating on a specifically assigned `vert group` within a previously-designed blender mesh/object without the freezes. 

One thing I'm wondering is if my **numpy** v 1.11.0 is causing any conflicts if sverchok is using a different version. My understanding is that _python3.5_ itself is already fairly unstable in Mac El Capitan.

**Comment by zeffii** [comment] 2016-04-21 21:22
I don't think it will make a difference how the geometry is created. Via 

- `Object In` + 'Vert Groups'    

or

-  built from ground up using a plethora nodes..  


At least, it's not what I would focus on first.Though, I might try doing this without vertex groups, and just use a intermediate mesh object that only contains the desired faces and take it from there.
  
-----------

As for numpy, it's compiled into Blender's python binary (if i'm not mistaken). The problem you're finding also happens on my machine, so i'm less inclined to seriously consider `numpy` as a source of the problem. In Blender's Python console you can 
```python

>>> import numpy as np
>>> np.version.version
'1.9.1'
```
----------
A possible insight might come from writing a small bit of _python_ that's analogous to the `NodeTree`. and see how fast that executes.

Maybe @ly29 may have some insight?

**Comment by Kosvor** [comment] 2016-04-22 07:13
Index socket of weights node is for list of integer numbers. Verts socket outputs list of tuples. If u want to change weights of all verts then dont use index socket at all. Use just weights socket (float values).

**Comment by JLiebo** [comment] 2016-04-22 18:18
@zeffii, @Kosvor,
Thanks for the info and insight here. It's good to know that it's not just my machine that freezes up – least as far as narrowing down issues is concerned. Zeffii, btw thanks for the kill-process tip the other day a la clicking into terminal. Certainly better than having to recover from an autosave. Thinking that, yeah, writing some python similar to a **Node Tree** is the way to go for testing.

**Comment by zeffii** [comment] 2016-04-26 09:19
@JLiebo have you managed to get your concept working without the freezes? I don't want to close the issue without acknowledging a solution or understanding of the cause.

**Comment by zeffii** [comment] 2016-04-26 09:31
if I remove the Centers Polygons node, it takes maybe a second to calculate..showing that the real slow down is that node and not the other nodes (therefore not likely affiliated with the Random float node either)

![image](https://cloud.githubusercontent.com/assets/619340/14813528/6237dc4e-0ba2-11e6-97a7-4f927958eb47.png)

**Comment by zeffii** [comment] 2016-04-26 10:05
the Vertex Groups socket will output only the Polygon indices of the vertex groups.

![image](https://cloud.githubusercontent.com/assets/619340/14814170/62b6b480-0ba5-11e6-8a05-bd1fbdd8b3be.png)

Feeding the Vertex Groups output to _random_ isn't producing the results you think, and also probably isn't what you want.

1. if you wanted to generate a random number for every Vertex in the vertex Group you would need to first determine the Length of the List which holds the Vertex Group. (use the List Length node)
2. But even when you do that you generate N random numbers and try to modify the Z value of each vertex. There are not an equal number of vertices / Vertex Group entires. Therefore this operation doesn't seem meaningful.

**Comment by JLiebo** [comment] 2016-04-26 17:19
Hi @zeffii,

Thanks for your note and info. You beat me to writing – I've had to work on another project for the past several days – and was actually going to write that we should probably close this issue.

I'm definitely still new to **Sverchok** and Python coding in general, so obviously the goal for me is to get comfortable with both (play around, as it were) hopefully without the crashes and/or major freezes. So I thought, well, it will probably take me a while to write the code for testing execution time, but what I can do in the meantime is try and limit my **subdivision surfacing** and hence **poly count** to see if that will quicken things up, which it is a bit. Actually, I got through your examples today without it freezing or crashing with **Centers polygons**, so this is good.

Right, re outputting **Vert groups** to a **random**, the goal originally was to _randomize_ the face vertices of the object in question along the Z axis, which I'd assigned as a group, just as one would do in using a **Displace Mod**. I was, of course, able to do this, but when I started experimenting with ways to alter the _randomization parameters_ is when I started running into troubles with the freezes, etc. My thinking is, the more I learn how to python code, the more I'll know straightaway which parameters I should be using, if that makes sense. 

What I can say is that your examples and info have been really helpful thus far, and I definitely appreciate your time. Wish I could be more helpful in return so that we could nail down and speed up the issues at play. If there's anything I can try on my end, so that we know we're both getting the same freezes or long computation times, let me know and I'll get on it.

**Comment by zeffii** [comment] 2016-04-26 17:31
@JLiebo I think your initial post/subsequent posts are fine. Gotta start conversations some how :)

My advice is to describe in words the begin-state and what kind of operations you'd like to perform on verts / edges / faces, based on deliberate criteria. Of course feel free to submit .blends containing your attempts, but emphasize the desired result in writing :)

Keep experimenting, we're here to help if we can :)

**Closed by zeffii** 2016-04-26 17:31 UTC

**Comment by JLiebo** [comment] 2016-04-26 19:05
Thanks much @zeffii. 
Cheers:)
