### ISSUE TITLE
Profile Parametric same Parameter in consecutive lines not working

### ISSUE THREAD

**Issue by geniusupgrader** [nortikin/sverchok#1751] opened 2017-08-11 20:04 UTC
This **is** working:
M 0,0
l a,0 0,b -a,0
X

And this **is not** working:
M 0,0
l a,0
l 0,b
l -a,0
X

See the next picture for reference:

![notworking](https://user-images.githubusercontent.com/6190906/29229601-91cfdedc-7edf-11e7-9452-910e19cbdc02.png)

But with an additional UV Connection and taking the data output from it, the lines and everything is then Ok:

![withuv](https://user-images.githubusercontent.com/6190906/29229625-ae4a9250-7edf-11e7-82b3-6354ce887a9a.png)

And there is a also a display problem, when viewing faces. With the same setup as above (with the UV Connection) and faces visible in the Viewer Draw, see the Picture below. But maybe this is a known Problem. I must admit I was too lazy to search in the issues. Maybe someone can bring me there? (if it is already a known problem...)

![facedisplayproblem](https://user-images.githubusercontent.com/6190906/29229745-518c13e4-7ee0-11e7-81e8-17b2bed5191b.png)

**Comment by zeffii** [comment] 2017-08-11 20:28
1. will have to look
2. the display problem is the result of you passing an NGon to the opengl drawing, which by default uses (for speed) the simplest triangle fan drawing method.  Viewer draw has an N panel toggle for "NGon" , which deals better with this kind of "concave" geometry.

**Comment by zeffii** [comment] 2017-08-12 07:41
As for the first matter, i'm not available to fix that at the moment.  It might may ( or may not ) be trivial. 

I've wanted to rewrite the path parser for some time because the initial design was a bit _ad hoc_, it has several corner cases with ugly fixes.

paradoxically, responding to this issue might have taken more energy than fixing the code immediately. 👨‍🚀

**Comment by geniusupgrader** [comment] 2017-08-12 07:48
Well, thanks for that.

I also have found the checkbox for NGon. Sometimes you overlook these parameters, especially when they are not in the documentation...

I think the Profile Parametric Node is a very important Node for doing some 2D CAD-like actions. It makes Blender more usable as a (parametric) CAD enviroment.

**Comment by zeffii** [comment] 2017-08-12 07:56
> Sometimes you overlook these parameters, especially when they are not in the documentation...

I agree, no-one will find that by quickly looking at the docs. It's there but I called it " optional forced tesselation (via N-Panel) " , and you have to dig a little in the links in the doc. No-one will do that or know to look..

It should be possible to make a more robust parser, but I think it will have to be a new node (so as not to break existing .blends). No ETA on this.. it's way down on my todo.

**Comment by zeffii** [comment] 2017-09-05 14:31
i'm closing this, but the issue is noted for any eventual upgrade to this node.

**Closed by zeffii** 2017-09-05 14:31 UTC
Labels: low priority, maintenance

**Comment by nortikin** [comment] 2017-09-06 06:21
i noticed some more related to me error - line from selection not correctly writing to text
