### ISSUE TITLE
Blender 2.73.5 Hash 26f9a92 , Sverchok make Blender to crash.

### ISSUE THREAD

**Issue by yanivg101** [nortikin/sverchok#559] opened 2015-02-01 21:59 UTC
I can't load blend file that use Sverchok in that version of Blender.

this is what Blender write when it crash:

"# Blender 2.73 (sub 5), Commit date: 2015-01-31 17:19, Hash 26f9a92 # backtrace"

I tried to load the file with the official 2.73a version and all goes well.
I also try with this version (Hash 26f9a92) to do this:
1. Open Blender.
2. Load Factory Settings.
3. Enable only the Sverchok Addon.
4. Check for update on the settings of the addons (where you enable/disable addons)
![image](https://cloud.githubusercontent.com/assets/6355171/5994034/11f24e4a-aa6e-11e4-892d-97dc3c21b936.png)

5. Open the Node editor.
6. When I try to make new Sverchok Node, Blender crash.
![image](https://cloud.githubusercontent.com/assets/6355171/5994047/39524076-aa6e-11e4-88f1-3ad001412795.png)

**Comment by zeffii** [comment] 2015-02-01 22:21
Yikes, i'll look through the Blender committers logs to see if anything stands out

**Comment by unity2k** [comment] 2015-02-01 22:23
I too am having the same crash.

Date: Sun, 1 Feb 2015 14:21:11 -0800

**Comment by zeffii** [comment] 2015-02-01 22:31
The update button / feature is probably not tested by any us that have the Sverchok repository locally, I literally have a symbolic link from `..\scripts\addons\Sverchok` to `..Documents\GitHub\Sverchok\ `

**Comment by zeffii** [comment] 2015-02-01 22:50
OK, I can confirm this too. but has nothing to do with the update button.. just pressing New alone closed Blender to the desktop

**Comment by zeffii** [comment] 2015-02-01 22:54
please use an official 2.73 build until the problem is resolved.

**Comment by zeffii** [comment] 2015-02-01 23:10
There is a ticket on the Committers issue tracker that points directly at this issue: (not a Sverchok bug)
https://developer.blender.org/T43501?workflow=create

**Comment by ly29** [comment] 2015-02-02 08:49
In general crashes are blender problems and not sverchoks direct fault, however finding the cause can be tricky.
Anyway it seems to be resolved.

**Comment by zeffii** [comment] 2015-02-02 08:49
this is fixed in the latest builds. (fixed just a few hours ago)

**Closed by ly29** 2015-02-02 08:49 UTC

**Comment by yanivg101** [comment] 2015-02-02 10:27
Good.
Just for the button issue:
I try it just to ensure the the addon is working. but now I know that it useless because it will not update the addon (it was on the last time)
I wish Blender will add a button on the preference to update all addons and it will work. [timesaver]

**Comment by zeffii** [comment] 2015-02-02 10:44
@yanivg101 
ideally we shouldn't have features that we don't test frequently, so it's good that you point this out. 

The update addon button is super useful for users (when it works) but for developers who use GIT and a symbolic link between their `2.73\scripts\addon\sverchok` and local `Git\sverchok\` development directory. something is bound to go wrong.

We could, and probably should, have a second separate Blender installation purely to test that update button.

**Comment by zeffii** [comment] 2015-02-02 10:46
I think i'll prepare a script that will bootstrap Sverchok from any new Blender installation, and get the latest files from GitHub and enable the addon.

**Comment by ly29** [comment] 2015-02-02 10:59
Also there are so many variables with updating and so many things that can go wrong that it will always be a bit fragile. It works reasonably well right now. 
This problem was due creating a new non standard node layout, not the update functionality.

**Comment by zeffii** [comment] 2015-02-02 11:05
Right, i was under the impression that there was a bug in the _updater_ too. I guess not, language can be difficult :)
