### ISSUE TITLE
What is the difference between Sverchok and Sorcar?

### ISSUE THREAD

**Issue by EaryChow** [nortikin/sverchok#2844] opened 2020-01-19 17:36 UTC
Hello, I am new to GitHub and I am not sure if this is where I can post my questions. If I am posting this in the wrong place please tell me where I can ask my questions. I have been using Sorcar for a while now, and I have just discover this Sverchok addon, which does similar things as Sorcar, but in more complicated ways. I am confused about these two, is there really a need to have two addons doing the same thing? If there is, then what is the difference? Can the two addons merge into one to prevent this awkwardness? As a general Blender user I am not sure about which one I should use anymore, and I wonder which one of these two will be merging into the official Blender branch in the future. If I learn Sorcar, but Sverchok ended up merging into the official release of Blender, I would probably need to give it up and learn Sverchok from scratch. I am so confused, could you please help me clear this up?

**Comment by portnov** [comment] 2020-01-19 19:30
Hello!
Good question anyway. I'm not very familiar with Sorcar, but afaik Sorcar appeared much later than Sverchok. So, maybe it worth asking Sorcar's author about why did he decide to create yet another addon :)
As far as I know, Sorcar always operates on an object which exists inside Blender scene (it even uses Blender's selection). On the other hand, Sverchok almost never deals with objects within scene (well, it can output objects into scene, and it can input objects, and there are other types of interactions, but we think of them as "peripheral interaction", not as a main thing that lies in the core of addon). IMHO this gives Sverchok more potential, because of ability to operate on more abstract level. I heard some day Sverchok used to operate on Blender objects too, but that was long before I joined the project. @zeffii maybe you can elaborate why did we decide to go from operating on scene object into more abstract area? One of reasons probably was to be nearer to Rhino/Grasshopper, which operates on pure numbers too, until the definition is "baked".
Since approaches are so different, I don't think it's possible to merge these addons. But, an information or ideas exchange would always be nice. For example, some features implemented in Sorcar after Sverchok's ideas, others in Sverchok after Sorcar's :)

I do not think either Sverchok or Sorcar are going to be merged into Blender distribution any time soon... at least, I do not see any movements towards that amongst Sverchok developers. Btw, why, @zeffii ? :)
And, anyway, if either of these addons will be merged into Blender distribution, it will not mean that the other one will be stopped in development.

@zeffii  btw, look at https://github.com/aachman98/Sorcar readme and wiki. It would be good ours to look as nice :)

**Comment by EaryChow** [comment] 2020-01-19 20:19
> Sorcar always operates on an object which exists inside Blender scene
I don't understand what you mean. In Sorcar, I can start up with an empty scene, add an object node and set the node to preview, then Sorcar would automatically generate an object in the scene. 

As far as I know, Sverchok works in a kind of similar way, but more complicated. You add an object node, then add a Viewer BMesh node, then hook up the vers, edges, faces one by one before you can see the mesh generated in the scene.

**Comment by zeffii** [comment] 2020-01-19 20:35
Hi @EaryChow, welcome. 

I sense in you an awful fear of wasting energy learning one "paradigm" instead of another. I can not elaborate on Sorcar because i've never used it, so i can not offer comparisons. What I can do is briefly describe what Sverchok is designed to do.

Sverchok is primarily designed to give the user parametric control over mesh construction, either via our primitives or via a combination of elementary nodes ( splines, arcs, lines, vectors.,etc ), or File reading nodes to read input geometry from Disk. We have many many nodes that can further process mesh data similar to Modifiers, and often far more advanced than Modifiers by allowing masking of verts/edges/faces to include/exclude in the effect. We also have the usual Math, Vector and Matrix manipulation nodes that can operate on for example just the Vertices of a mesh.

You can generate entire meshes inside Sverchok without ever generating a real Object in the Blender scene, or you can use the Object Viewers (BMeshViewer, PolyLine, Curve...etc )

I think your assessment that Sverchok is complicated is correct in the sense that Sverchok allows highly complicated interaction with meshes, with relative ease. There are many things that are super simple in Animation Nodes and Sorcar, that Sverchok does not offer a convenient solution for - because Sverchok is designed for the things I mentioned above. 

@portnov  will look at the docs, our community outreach has periods of weakness when we're busy

**Comment by zeffii** [comment] 2020-01-19 20:52
@portnov 

> I do not see any movements towards that amongst Sverchok developers. Btw, why, @zeffii ? :)

I can't say for certain what the rest of you feel, but there are a number of good reasons to not want inclusion in the standard distribution.
- Sverchok is not a trivial add-on, and its documentation is not exhaustive. (something that's much easier to do for smaller add-ons)
- i was discouraged by the announcement of "Everything Nodes". It seems like it would be redundant to have multiple node systems with overlapping functionality.
- we have not raised the version beyond 0.6.0 because it reflects how complete we feel that it is (there's no objective way to measure that.. )

**Comment by EaryChow** [comment] 2020-01-19 21:10
So... It's like Sorcar is trying to make an easy-to-use, node-based modeling tool that works similar to the default Blender work flow, while Sverchok offers something more complicated and abstract, that is kind of independant from how Blender works by default? In that way I sort of understand now.

**Comment by zeffii** [comment] 2020-01-19 21:14
@EaryChow - that's a good summary.

another thing we lack is good tutorial videos, like a step by step introduction made by one of the developers. So it is only really the most inquisitive / persistent users who achieve "Sverchok enlightenment". Another group of users transition easier are those with experience in Grasshopper/Houdini/Dynamo..etc

**Comment by zeffii** [comment] 2020-01-19 21:40
>  is kind of independent from how Blender works

we use Blender python libraries (mathutils and bmesh and kdtree/bvh etc) and offer output of mesh data / curve extensively as proper Blender Objects, so another way to describe it is that we implement a novel way to construct Objects using the available Blender API. We also implement many of our own utility functions and sverchok-API to bypass limitations/gaps in Blender. 

it's a lot of fun, else I don't think i'd be doing it 6 years...

**Comment by Durman** [comment] 2020-01-20 14:45
@aachman98 probably would like to add something to the answer. =)

**Comment by aachman98** [comment] 2020-03-05 19:46
Hi everyone!
Sorry for the late reply, had been quite busy for the last couple of months.

First of all, a big thanks to Sverchok because it was one of my earlier inspirations and a great source of learning node systems in Blender (programmer's side)! If it weren't for me being extremely lazy to learn Sverchok, Sorcar wouldn't even have happened ;)

If it is all right to continue the discussion here, then I would like to mention that comparing Sverchok and Sorcar is like comparing apples and... small plastic apples. Both may look like they serve the same purpose, but the latter's easiness to grasp doesn't make it better in any way. As @zeffii  says, Sverchok is more about mesh construction using powerful modifier-like operations to give you total control. Sorcar, on the other hand, is a tool which may come in handy when you need quick results with iterations using procedures you are already familiar with (assuming you are a regular Blender user).
Each system has its own area where it shines the most.
In a game jam? Need quick assets with variations? Don't want to spend much time in perfecting things? Sorcar is your friend.
Working on a big project? Need to create complex meshes with high control over each fundamental unit? Want multiple levels of proceduralism? You can't go wrong with Sverchok.

@portnov 
> I do not think either Sverchok or Sorcar are going to be merged into Blender distribution any time soon

I don't know about Sverchok, but Sorcar would definitely not be merging with Blender, given its architecture. It works on existing blender ops and rarely use custom algorithms to create mesh from ground up. Think of it as an automation tool for Blender rather than a procedural system. The only crucial thing it does is eliminates the inability to change parameters for already applied modifiers or operations (like changing extrude amount, vertices of cylinder, etc.).

@EaryChow 
> I don't understand what you mean. In Sorcar, I can start up with an empty scene, add an object node and set the node to preview, then Sorcar would automatically generate an object in the scene. If you don't want it in the scene, you can probably just... don't set it to preview? Then you kind of need to imagine what it looks like, hahah.
As far as I know, Sverchok works in a kind of similar way, but more complicated. You add an object node, then add a Viewer BMesh node, then hook up the vers, edges, faces one by one before you can see the mesh generated in the scene.

Let me give you an example:
Sverchok object (plane) before extrusion:
{
	[(-1.0, -1.0, 0.0), (1.0, -1.0, 0.0), (-1.0, 1.0, 0.0), (1.0, 1.0, 0.0)],
	[(2, 0), (0, 1), (1, 3), (3, 2)],
	[(0, 2, 3, 1)]
}
Sverchok object after extrusion:
{
	[(-1.0, -1.0, 0.0), (1.0, -1.0, 0.0), (-1.0, 1.0, 0.0), (1.0, 1.0, 0.0), (-1.0, 1.0, 1.0), (-1.0, -1.0, 1.0), (1.0, -1.0, 1.0), (1.0, 1.0, 1.0)],
	[(2, 0), (0, 1), (1, 3), (3, 2), (4, 5), (5, 6), (6, 7), (7, 4), (3, 7), (6, 1), (0, 5), (4, 2)],
	[(0, 2, 3, 1), (5, 6, 7, 4), (1, 3, 7, 6), (2, 0, 5, 4), (3, 2, 4, 7), (0, 1, 6, 5)]
}

Sorcar object before extrusion: bpy.data.objects['Plane']
Sorcar object after extrusion: bpy.data.objects['Plane']

Get @portnov 's point? Sorcar keeps references as its object rather than the actual geometry. The same is passed from node to node which is why only one connection is needed (unlike Sverchok where array of vert/edge/face is passed). This makes Sverchok powerful as you can mix & match different components or simply mask them individually. You'll have to rely on Blender's selection tools to do that in Sorcar.

> btw, look at https://github.com/aachman98/Sorcar readme and wiki. It would be good ours to look as nice :)

See FlipFluid addon's GitHub page as well: https://github.com/rlguy/Blender-FLIP-Fluids

And frankly, I don't think you can compare 6+ years of dedicated development (not to mention the awesome efforts by a huge community) with a 7-8 months on-and-off side project by a college idiot... xD. I'm open to exchanging ideas with the Sverchok community; just let me know a better place to hold discussions than this issue tracker (maybe another BlenderArtists thread?).
Anyways, let's see if EverythingNodes is able to bring the power of Sverchok with ease of Sorcar together!

P.S. Thanks to @Durman  for mentioning me here

**Comment by Durman** [comment] 2020-03-06 05:04
@aachman98 
> Sorcar keeps references as its object rather than the actual geometry. The same is passed from node to node which is why only one connection is needed (unlike Sverchok where array of vert/edge/face is passed).

There are ideas about improving data structure of Svershok. I would say that Sverchok does not have data structure at all now. 
![2020-03-06_08-48-10](https://user-images.githubusercontent.com/28003269/76053805-d2cb8b80-5f87-11ea-9387-ec34defd7267.png)
#2927

And Sverchok is not going to be merged because it at least does not written on C/C++. And I would say that Sverchok mostly is greate aductional project but which is difficult to use in practice.

**Comment by portnov** [comment] 2020-03-06 05:32
@Durman / @aachman98 I believe by "merged" it was meant not that sverchok / sorcar is going to be merged to Blender's C core itself - there were no such precedents at all. What is (theoretically, some day) possible is to include the addon into list of addons that are included into blender distribution by default.

**Comment by aachman98** [comment] 2020-03-06 09:52
> There are ideas about improving data structure of Svershok. I would say that Sverchok does not have data structure at all now.

Oh..
I was hoping for a fixed structure that would be helpful in an API. "Send to Sverchok" and "Receive from Sverchok" nodes will be a possibility then. And even if there is no common ground, simply forwarding the vert & faces array would be enough to bake the geometry I guess (or create an object in Sorcar's case).



> to include the addon into list of addons that are included into blender distribution by default.

I see. Although it would be good to see a node system for modeling embedded in the internal deps graph. Have you thought of creating custom Blender build, now that you feel like Sverchok has enough modular pieces that give a sense of completeness to it?

**Comment by portnov** [comment] 2020-03-06 10:19
I do not see any reason for "custom blender build". It could be useful if it would be hard to install Sverchok. For example, it seems to me it would be reasonable for Animation Nodes, since it is written in Cython and thus the developer has to make some "builds" (actual compilation, a process similar to building Blender from source, for example), then user has to download binary files and follow the instruction... to download a pre-configured blender build would be simpler for user. But for Sverchok, you just download zip from github main page and install it in a standard way. It is simpler than installing a custom blender build...

**Comment by aachman98** [comment] 2020-03-06 15:20
I meant modifying the Blender source which can be later merged with official repo.

**Comment by portnov** [comment] 2020-03-06 15:44
What for?...

**Comment by zeffii** [comment] 2020-03-06 16:09
it will be interesting to see how far numpy can take us.

**Comment by portnov** [comment] 2020-03-06 16:26
I've done some investigations earlier (#1990). For things numpy is designed for (vectorized mathematical computations), numpy can easily be faster than hand-written C code, because it automatically uses SIMD instructions for vectorization when possible. The problem is, there are not so much things in Sverchok where we actually do something like that. Much more of code, and more computation time is just a wall with for-if-elses, which do some lists manipulations. Numpy can hardly be useful there.

**Comment by aachman98** [comment] 2020-03-06 20:19
> What for?... I mean, what modifications could we bring into blender?
> 
> We probably could write some things that we miss in Sverchok, for example an API for NURBS. But I'm afraid nobody of us has enough expertise in C language / Blender sources.

Modifications like bringing all modifiers and operations to node editor, or creating nodes on callbacks from viewport actions. Or maybe bringing all the Sverchok nodes to modifier stack, which will make it more awesome than ever!
Anyways, modifying Blender source seems like a long shot; and given that EverythingNodes is going to be released, there's no need to create a node evaluation system that is context aware.

I'm still up for a Sorcar to Sverchok workflow though. Let me know if Sverchok can communicate across node trees and receive values from a Sorcar node.

**Comment by portnov** [comment] 2020-03-07 06:42
> Modifications like bringing all modifiers and operations to node editor, or creating nodes on callbacks from viewport actions. Or maybe bringing all the Sverchok nodes to modifier stack, which will make it more awesome than ever! (EDIT: maybe not, because you'll lose some control over data transfer)

well, that all is totally not Sverchok. I suspect this is more or less what the Everything Nodes is about.

**Comment by zeffii** [comment] 2020-03-07 09:07
an interesting thing I would like in blender modifiers, is a way to define our own modifiers in code. Because if it can be done in code, it could potentially be implemented as a nodetree.

https://github.com/eliemichel/OpenMeshEffectForBlender

**Comment by nortikin** [comment] 2020-03-14 00:54
> > What for?... I mean, what modifications could we bring into blender?
> > We probably could write some things that we miss in Sverchok, for example an API for NURBS. But I'm afraid nobody of us has enough expertise in C language / Blender sources.
> 
> Modifications like bringing all modifiers and operations to node editor, or creating nodes on callbacks from viewport actions. Or maybe bringing all the Sverchok nodes to modifier stack, which will make it more awesome than ever! (EDIT: maybe not, because you'll lose some control over data transfer)
> Anyways, modifying Blender source seems like a long shot; and given that EverythingNodes is going to be released, there's no need to create a node evaluation system that is context aware.
> 
> I'm still up for a Sorcar to Sverchok workflow though. Let me know if Sverchok can communicate across node trees and receive values from a Sorcar node.

we have such communicative node called NodeRemore control, we can add new system support (allready there are couple of)

**Comment by nortikin** [comment] 2020-04-28 19:05
update
ok, I contacted Sorcar developer and we developed node remote control to communicate from sverchok to sorcar.
it si in master allready. But for now you do with number (float int angle) node

**Comment by enzyme69** [comment] 2020-04-29 01:10
@nortikin Got example of SV and SC connection?

**Comment by enzyme69** [comment] 2020-04-29 01:11
@nortikin Btw, we have not been able to control node parameter from 3D View panel for a very long time :(

**Comment by nortikin** [comment] 2020-04-30 15:28
> @nortikin Got example of SV and SC connection?

https://vk.com/wall-35076122_10943

**Comment by aachman98** [comment] 2020-05-23 00:38
> @nortikin Got example of SV and SC connection?

@enzyme69 
sorry couldnt reply earlier
new nodes, will update tomorrow: https://youtu.be/pTIiMj5GpyI

**Comment by aachman98** [comment] 2020-05-25 18:03
#3281 
Thank you @nortikin @zeffii !

**Comment by enzyme69** [comment] 2020-05-26 06:41
@aachman98 Where is "receive from socar" node in SV... is it not yet publlished?

<img width="993" alt="Screen Shot 2020-05-26 at 4 40 34 pm" src="https://user-images.githubusercontent.com/3952687/82868295-b54b0400-9f6f-11ea-8cdb-44e86f3a3704.png">

**Comment by enzyme69** [comment] 2020-05-26 06:42
Also we might need "send from SVerchok into Sorcar" maybe :) Normally I use Objects In and Objects Out, but would it create endless cyclic?

**Comment by aachman98** [comment] 2020-05-26 07:08
> @aachman98 Where is "receive from socar" node in SV... is it not yet publlished?
> 
> 
> 
> <img width="993" alt="Screen Shot 2020-05-26 at 4 40 34 pm" src="https://user-images.githubusercontent.com/3952687/82868295-b54b0400-9f6f-11ea-8cdb-44e86f3a3704.png">
> 
> 

Both the nodes are in final dev phase. The sverchok node requires a minor fix before merging into master. The Sorcar node is pushed to the master, but will be released with other major updates.

**Comment by aachman98** [comment] 2020-05-26 07:14
> Also we might need "send from SVerchok into Sorcar" maybe :) Normally I use Objects In and Objects Out, but would it create endless cyclic?

Will begin working on it right away.

**Comment by nortikin** [comment] 2020-05-26 13:20
> Also we might need "send from SVerchok into Sorcar" maybe :) Normally I use Objects In and Objects Out, but would it create endless cyclic?

for now please, use node remote control. It works with number node (float, int, angle). But not with mesh yet

**Comment by aachman98** [comment] 2020-05-26 13:27
> But not with mesh yet

![image](https://user-images.githubusercontent.com/26548023/82906269-9bff8300-9f82-11ea-8e57-32c711d3b2b4.png)

Soon to be remedied!

**Comment by aachman98** [comment] 2020-05-26 14:22
This was fun!

![Screenshot from 2020-05-26 19-49-15](https://user-images.githubusercontent.com/26548023/82912036-34e5cc80-9f8a-11ea-9260-781e36a1875d.png)

Can I use it as a default mesh for "Receive From Sverchok" node?

**Comment by vicdoval** [comment] 2020-05-26 21:19
> Can I use it as a default mesh for "Receive From Sverchok" node?
Yes! Its pretty cool ;)

**Comment by nortikin** [comment] 2020-05-27 09:19
kek lol. we have not template with logo in sverchok... Musthave

**Comment by portnov** [comment] 2020-05-27 15:50
Hm.
https://gist.github.com/5fbdc5c05e8acb5f92b59a2ef0cecae2
![Screenshot_20200527_205024](https://user-images.githubusercontent.com/284644/83043004-bb1e1380-a05b-11ea-862a-15307f5ed749.png)

:)

**Comment by aachman98** [comment] 2020-05-27 22:09
> Hm.
> https://gist.github.com/5fbdc5c05e8acb5f92b59a2ef0cecae2

I like your approach! Much less hassle than creating a sin wave and adjusting parameters endlessly xD

![image](https://user-images.githubusercontent.com/26548023/83076555-64ccc700-a093-11ea-9537-24fc4619c0ee.png)

Closer to the real one, now..
Anyways, I think we should move out of this issue section. It's not necessary to keep it open just for this. DevTalk or BlenderArtist?

**Comment by zeffii** [comment] 2020-05-29 13:28
interestingly that gist crashes my blender ( https://gist.github.com/portnov/5fbdc5c05e8acb5f92b59a2ef0cecae2 )

**Comment by portnov** [comment] 2020-05-29 14:37
That's most probably a crash in delaunay2d_cdt :/ try another version of blender - newer or older...

**Comment by zeffii** [comment] 2020-05-29 15:07
the cropmesh 2d when i connect the faces 

![image](https://user-images.githubusercontent.com/619340/83274988-d198ac00-a1ce-11ea-827a-6aa447bc586a.png)

i updated 2.83, might go to 2.90

**Comment by portnov** [comment] 2020-05-29 15:11
yup, it uses mathutils.geometry.delaunay2d_cdt, which crashes sometimes :/
Unfortunately, in this particular case "sweep line" algorithm can't find the intersection @Durman

**Comment by Durman** [comment] 2020-05-29 16:25
@zeffii Most likely the problem is in part of Blender code. Have a look at this topic.
https://devtalk.blender.org/t/delaunay-2d-cdt-robustness/10968/11

 I think someone have to reports bags about this function. Probably after that it will get more robust.

**Comment by aachman98** [comment] 2020-05-30 12:33
@enzyme69 
> Also we might need "send from SVerchok into Sorcar" maybe :)

![image](https://user-images.githubusercontent.com/26548023/83327885-e5aadf00-a29c-11ea-99a5-00b4e9ea1b80.png)

Done! Working out the kinks at the moment...
You already have option to control Sorcar "Number" node parameter using Node Remote MK2, thanks to @zeffii, @nortikin!

[Video demo](https://youtu.be/q_vrZRnzirw)

**Closed** 2020-08-19 05:52 UTC
Labels: question
