### ISSUE TITLE
Meshing watertight trees

### ISSUE THREAD

**Issue by nantille** [nortikin/sverchok#830] opened 2016-08-25 13:41 UTC
Hello,

It's hard to know where to ask such a question so I post it here. 

I have a basic understanding of what sverchok can do. My question is far beyond my capabilities with Sverchok at the moment.

I'm looking for a way to mesh branching structures (like a tree for instance). I have a set of points in space and I follow them with a spline, which I extrude. So you get a tubular structure. The problem comes at branching points. I cannot split the spline and I have to create a new one that will collide with its parent. I would like to know if there is a way to mesh branches with Sverchok so that when they branch/split, this results in one manifold and watertight mesh, with generated uv mapping.

I already have done this in blender python but the worst part is when I use boolean modifiers to merge all branches to make it watertight. This takes ages. With Sverchok, I hope to create similar meshes better and faster but I don't know where to start...

**Comment by nortikin** [comment] 2016-08-25 14:58
aha... joints have to be manifold and united and with clean topology?

**Comment by nantille** [comment] 2016-08-25 15:44
As much as possible yes. I'm doing it the brute force way with splines and I get good results, even uv mapping (generated automatically from curve object) is kept after boolean union but the topology at joints is a bit rubbish. I don't have any other choice at the moment.

I'm working on the visualisation of neurons, which are very similar to trees. Here's an example of branching I'm trying to achieve. 
![curves_branching](https://cloud.githubusercontent.com/assets/10866779/17975729/15c75c4c-6aeb-11e6-9e31-d51fa715f9e8.jpg)


There are other approaches that I tried. Like using metaballs but it's slow and I cannot easily uv map that. However, in cases where I can go procedural (like for blood vessels in the attached image), I get rather good results for what it is. 
![vasculature](https://cloud.githubusercontent.com/assets/10866779/17975755/38f9dffa-6aeb-11e6-9681-85329fdaf0f4.jpg)



Another approach, the low-level and best one, is to create an algorithm that will create faces for the branches and at branching points, handling how many branches are connected together, creating holes and then bridging them to make a correct structure. There are people who have done that for various cases but none of them (to my knowledge) have open sourced their code, like the t-spline plugin for rhino which was bought by Autodesk...

I know that Sverchok can create topology from splines, the tricky part is when branching occurs.

**Comment by nortikin** [comment] 2016-08-25 15:53
try skin modifier node. maybe it is what you need... or viewer bmesh, and usr skin modifier in blender itself.

**Comment by ly29** [comment] 2016-08-25 16:04
That does look tricky, I wish we could offer you a solution.

**Comment by nantille** [comment] 2016-08-25 18:56
I tried the skin modifier already but it has two disadvantages: it's soooo slow and I cannot control the amount of tesselation between given points (I have to recompile Blender to change that...not so cool), so I end up with way too many polygons for what's needed. But yes in theory the skin modifier would be interesting.

If there's no way to do something like the skin modifier but faster with Sverchok, I'll stick to what I have in the meantime.

**Comment by zeffii** [comment] 2016-08-25 19:32
why does this structure need to be watertight?

**Comment by nantille** [comment] 2016-08-25 21:46
It doesn't necessarily need to be so when I design illustrations and visualisations. If I use transparency with materials, then I need non self-intersecting meshes at least, which is why I do the (utterly slow) boolean merging of all branches, still faster than skin modifier.

For reconstruction, simulation and visualisation, data is often transformed to what is fitting for the context. From a point dataset, we have surface meshes and we may then voxelise these. Or on the other hand we extract iso surfaces from volumes. A normal voxeliser requires watertight meshes. I already use bmesh fill_holes() which doesn't work in all conditions. The easiest and maybe slowest solution is to apply a remesh modifier to ensure watertightness at the cost of slightly different mesh output.

Also, for some molecular simulations, we have to provide watertight non self-intersecting meshes but that's a separate process at the moment.

**Comment by zeffii** [comment] 2016-08-26 07:38
There comes a point where this isn't so much about Sverchok / Blender as it is about finding tricks to load share over multiple processors. The nature of the problem (meshing) does tend to be computationally heavy, and I imagine simulation (this is vague - elaborate please) is no different and perhaps even more so. In Sverchok we have not touched on parallelization yet, but there are features which can be multithreaded (non bpy stuff unfortunately)

Regarding the utterly slow boolean, it may be worth looking at how you write that code - it may be slow(er) by design. Without seeing the code noone really knows, indeed there may be ways to go _parallel_ . For instance multiple instances of Blender on different cores performing 1/9 of the object each or something) , then later joining them in what should be a lighter boolean union.

My interest here is how does your data come in , is it 
```python
x,y,z,radius
```
?
I'd love a sample of that data :)

**Comment by nantille** [comment] 2016-08-26 09:30
I've written quite a lot of python code already (for a designer) in the course of two years. I will open source that as soon as it's validated by management. In the meantime I can share some code about booleans and multiprocessing for instance. I suppose I should create a repo.

I have already looked at parallelisation and pulled my hair as to how I could multithread or multiprocess and I now have working code for distributing meshing to all available processors, which is quite cool as we have some beasts with 40+ cores plus some clusters to do the heavy work. When I don't use boolean union of meshes, meshing a neuron – with of course self intersecting branches – is done in a matter of mere seconds. When I use boolean operations, the same meshing takes 1min for a simple one. I have failed to use the to_mesh() method as it doesn't behave the same as the to_mesh operator. I do a recursive boolean union chain on the branches and I cannot figure out why it only works with the operator. So, at the moment, I'm forced to link neurons on the scene and then apply the convert to mesh operator.

You may have a good idea with distributing the boolean operations, which I don't do because I usually have thousands of meshes to generate, so I distribute the meshing by blocks or simply divide the number of meshes to handle by the number of procs. 

Actually, the process of meshing can be entirely done by non bpy libraries such as CGA, gmsh, you name it. I personally remain at the high level with python, otherwise if I start with C++, I do only coding and no illustration. Some guys from another institution are working on live gpu tesselation which is fine for interactive visualisation. The problem when I step over to more serious illustration/visualisation is always about uv mapping and having the least amount of polygons while keeping a good look and keeping things automated until the creative part.

I have meshed thousands of neurons and loaded them all at once in Blender but the whole bpy.context.scene is very slow. About curves, I noticed that it is so much faster for some reason to have a hundred thousand curve objects on the scene than converting them all to meshes. There is something relatively fast about nurbs in the viewport. 

I kept it simple with simulations 'cos I didn't want to write a book, but I guess this cannot be helped. We have some simulations for surface membrane potentials where neurons "express" their electric activity, that's usually done with a kind of heat map like below. The image below is made with a custom in-house software that doesn't use uv mapping but instead colours vertices. 
![neuronal_simulation](https://cloud.githubusercontent.com/assets/10866779/18000058/813fd44a-6b7c-11e6-8805-b06e501a0c88.png)


We also have molecular simulations within branches, not at the same low-level as BioBlender to which you contributed though.

Data is readily available on neuromorpho.org and it's as you say, x y z & radius. However there are advanced cases where you have xr and yr, the tubes become ovoid, a good use-case for something like a faster skin modifier.

It's worth mentioning at this point that we have a talented senior engineer, Cyrille Favreau, who used the interactive raytracing lib OSPray by Intel to create interactive visualisations of billions of polygons, which is crazy. For now it's very far from the quality of image you can make with Blender, the project is only beginning. It was recently open sourced https://github.com/bluebrain/Brayns

**Comment by zeffii** [comment] 2016-08-26 09:50
Thanks for that thorough answer, it puts a few things into perspective. I too come to programming from a designer perspective, needing tools that no-one else wanted to build for me. 

> Data is readily available on neuromorpho.org and it's as you say, x y z & radius. However there are advanced cases where you have xr and yr, the tubes become ovoid, a good use-case for something like a faster skin modifier.

When you import curves, are you generating thousands of separate curve objects, or adding thousands of subcurves (disjoint) to one main curve?

**Comment by zeffii** [comment] 2016-08-26 10:02
CGA , this : http://doc.cgal.org/latest/Mesh_3/  ?
gmsh, this : http://gmsh.info/#Documentation ?

**Comment by zeffii** [comment] 2016-08-26 11:46
Blender's skin modifier was created as an analogue of ZBrushe's 'ZSpheres' a simple way to give an edge based mesh some body. It's hardly expected to operate on heavy meshes, nor - unfortunately - is it likely to receive any speedfixing without funding or someone who can write the appropriate C/C++ .

seems like calling those two (or equivalent) Libraries from Python is where you would really gain speed and flexibility.

but you already know this.

**Comment by nantille** [comment] 2016-08-26 13:15
Funny to see someone with the same background here! I saw last year how you help Monica to sanitise BioBlender, that really helped to put their stuff online. 

I didn't know about the reason behind the skin modifier.

There is also VMTK (http://www.vmtk.org/) specialised in vasculature. But it's more for FEA or finite element analysis. Surface meshes are a special case of volume meshes.

Ah, another very cool app is a research done by Wenzel Jakob who made a presentation in our office. The app's called Instant Meshes and it does amazing retopology. Unfortunately, the output, as clean as it may be, is unusable for uv mapping. http://igl.ethz.ch/projects/instant-meshes/ 
Someone wrote a blender addon to use it easily https://github.com/VerbalTea/instantmesher 

About CGAL, the existing python bindings are a nightmare for me. Someone started an effort to recreate bindings from scratch and the result looks way more pythonic. Unfortunately, the author hasn't had the time yet to make all the interesting parts of CGAL available, I made a request here: https://github.com/wolfv/pygal/issues/1#issuecomment-238423789

**Comment by zeffii** [comment] 2016-08-26 14:58
I think this is the core of your problem..

> Instant Meshes and it does amazing retopology. Unfortunately, the output, as clean as it may be, is unusable for uv mapping

why is it unusable?

**Comment by nantille** [comment] 2016-08-26 15:50
The problem is the nature of a neuron, it's a nightmare to unwrap. 
Below are the usual attempts to auto unwrap after having a more of less clean mesh. In the case of Instant Meshes, it's quite good.

Spherical projection, no good:
![spherical_proj](https://cloud.githubusercontent.com/assets/10866779/18011311/e815b832-6bb4-11e6-8f85-072d6d74e8b6.jpg)

Cylindrical projection, interesting:
![cylindrical_proj](https://cloud.githubusercontent.com/assets/10866779/18011335/fe86bd32-6bb4-11e6-8b23-19ee56d2dda2.jpg)

...but no good:
![cylindrical_proj_above](https://cloud.githubusercontent.com/assets/10866779/18011332/fb9f0868-6bb4-11e6-9a07-22ad1c5f4ab2.jpg)

Star wars projection (smart uv), no good:
![star_wars](https://cloud.githubusercontent.com/assets/10866779/18011348/0bd8d8d0-6bb5-11e6-8de0-3283e203d9ed.jpg)


And I spare you the cube projection!

**Comment by zeffii** [comment] 2016-08-26 16:43
is the underlying problem is that it's a bit tricky to place seams automatically?

**Comment by enzyme69** [comment] 2016-08-26 18:50
I think the texturing should be using procedural shader, like OSL, or all
kind of 3D texturing method. So you don't need to worry about UV.




-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nantille** [comment] 2016-08-26 21:24
Well, if there's any acceptable method to have a usable uv from automated unwrap, I'm all for it.

Depending on the use-case, procedural shaders are clearly a good solution. I have written an OSL shader to map voltage as a heat map but that was 2D.

I will try 3d texturing with OSL and see if it gives me enough control and good results. For instance, if you look at this page http://www.fundza.com/rfm/osl/pattern3d/index.html I want the black and white lines to follow the curvature of my model, which is why UV is very useful to me.

**Comment by zeffii** [comment] 2016-08-27 08:07
@nantille if you make one of those neuron clusters and manually set the seams where they could be placed logically (if the boolean operation could set seams at the border of unioned surfaces) , how does the automatic unwrap look then?

![image](https://cloud.githubusercontent.com/assets/619340/18026133/17fab140-6c3e-11e6-9255-62f0390c91d0.png)

**Comment by zeffii** [comment] 2016-08-27 08:12
also regarding this question:

> When I don't use boolean union of meshes, meshing a neuron – with of course self intersecting branches – is done in a matter of mere seconds. When I use boolean operations, the same meshing takes 1min for a simple one. I have failed to use the to_mesh() method as it doesn't behave the same as the to_mesh operator. I do a recursive boolean union chain on the branches and I cannot figure out why it only works with the operator. So, at the moment, I'm forced to link neurons on the scene and then apply the convert to mesh operator.

I recommend you ask on BlenderStackExchange with a .blend of the neurons pre boolean. People like @cegaton @sambler @jerryno ..or lrking devs may give insight. It's tricky if you can't share the code, but then (if I were in your shoes) I would write the brain dead version of the total-unionizing code to demonstrate conceptually how you are doing it, so they have a chance to either agree (and maybe report a bug) or show a working answer.

**Comment by zeffii** [comment] 2016-08-27 08:23
note to self:  http://research.mssm.edu/cnic/swc.html

```text
n T x y z R P
n is an integer label that identifies the current point and increments by one from one line to the next.

T is an integer representing the type of neuronal segment, such as soma, axon, apical dendrite, etc. The standard accepted integer values are given below.

0 = undefined
1 = soma
2 = axon
3 = dendrite
4 = apical dendrite
5 = fork point
6 = end point
7 = custom
x, y, z gives the cartesian coordinates of each node.

R is the radius at that node.

P indicates the parent (the integer label) of the current point or -1 to indicate an origin (soma).
```

**Comment by nantille** [comment] 2016-08-27 09:02
My initial question was about doing branching structures à la skin modifier with Sverchok so I wasn't ready with the code and examples. The code is broken 'cos I'm still experimenting and refactoring. From next week on, I'll start cleaning up (in other words, making it work) and I'll prepare some images for documentation, samples and all. That should keep me busy for a while.

**Comment by zeffii** [comment] 2016-08-27 09:16
we do have a skin modifier node, but it is bound to the same limits as the underlying modifier :/

I accidentally starting writing an swc parser :/

**Comment by ly29** [comment] 2016-08-27 09:18
Me too :)

**Comment by zeffii** [comment] 2016-08-27 09:22
infact, sverchok's skin modifier node is hampered by the fact that any update to a meshe's vertex will cause al l`data.skin_vertices` to be wiped.. may not be an issue here, but pisses me off to no end :)

**Comment by nantille** [comment] 2016-08-27 09:24
I will try what you suggested with the seam but then how do I automate that? The meshing is fully automated, so the uv seams I place by hand will need to be placed automatically as well.

Just to recap', so far I have a working solution already. I use curves and auto uv mapping, I merge them with boolean union and all is good, except at the small merged parts where UV is a bit erratic. But that works. I know that my way of doing it is slow and suboptimal from a developer standpoint (but hey! I use multiprocessing to compensate :D) but the result is good and I can use that on the creative side.

Once I'm all set, I'll go back to questioning on blender.stackexchange.com (which I did already) and here.

About swc parsing it's quite easy, here's the class

`

    @classmethod
    def parse(cls, file_path):

        # If we use this, then it yields a structured array
        dtypes = {'names': ('id', 'type', 'x', 'y', 'z', 'rad', 'parent'),
                  'formats': ('i8', 'i2', 'f6', 'f6', 'f6', 'f6', 'i8')}

        data = np.loadtxt(file_path, dtype=None, delimiter=' ')
        origin = data[np.logical_and(data[:, 6] == -1, data[:, 1] == 1)]

        return data, origin`

**Comment by zeffii** [comment] 2016-08-27 09:31
![image](https://cloud.githubusercontent.com/assets/619340/18026516/9b241e48-6c49-11e6-9d97-e8f573fff13a.png)

[wonky script..](https://gist.github.com/zeffii/82d07a25365d68e58097c8eaaea8a0e1) prelims no edges implemented yet

**Comment by nantille** [comment] 2016-08-27 09:33
Here's for your impatience:

This is in swc_tree.py

@classmethod
    def shake(cls, tree):
        """
        Get properly reconstructed tree and points data
        :param swc_pts: SWC raw file content
        :return: Tree data
        """
        if tree is None:
            return

        origin_id = 1
        raw_swc = tree.raw_points

        # Set the recursion limit according to the number of points
        pts_len = len(raw_swc)
        if pts_len > sys.getrecursionlimit():
            sys.setrecursionlimit(pts_len)

        strc, pts, pts_map, depth = cls.build_structure(raw_swc, origin_id)

        tree.structure = strc
        tree.points = np.array(pts) 
        tree.origin = pts[origin_id]

        diff = len(pts) - depth
        if diff > 0:
            msg = 'Warning, SWC parser reconstructed tree and '
            msg += str(diff) + ' points were not used which reveal a '
            msg += 'structural problem in the file itself.'
            logging.warning(msg)

        return tree

@classmethod
    def build_structure(cls,
                        swc,
                        swc_id=1,
                        new_one=True,
                        branch_id=-1,
                        order=0,
                        depth=0,
                        tree=None,
                        pts=None,
                        pt_map=None):
        """
        [Recursive] Takes raw SWC data (a list of points, each pt knows its
        parent) and convert it to a tree and points data set.

        Shaker branch data description:
        0 branch id
        1 start point id
        2 end point id
        3 branch parent id
        4 branch type
        5 number of children
        6 is terminal

        Shaker point data description:
        0 x coordinate
        1 y coordinate
        2 z coordinate
        3 width <- SWC radius is applied here
        4 height <- not supported by SWC

        :param swc: Data input from SWC file
        :param swc_id: Initial point id from which to grow the structure,
        defaults to 1, the soma id in SWC standard
        :param new_one: Whether this branch is a new one
        :param branch_id: Current branch id
        :param order: Order of the branch
        :param depth: Recursion depth
        :param tree: Resulting tree data
        :param pts: Resulting points data
        :param pt_map: Comparison of input points versus newly ordered points
        :return: Tree and point data + total recursion depth
        """
        depth += 1
        # The point found must be unique otherwise the SWC file is incorrect
        swc_point = swc[swc_id - 1]

        branch_type = swc_point[1]

        new_pt = swc_point[2:6]
        if new_pt[-1] == 0:
            # Can be improved by accounting for point position on curve
            new_pt[-1] = cls.branching_thinning(order)

        if pts is None:
            pts = list()

        pts.append(new_pt)
        point_id = len(pts)

        if pt_map is None:
            pt_map = list()
        pt_map.append([swc_id, point_id])

        # Get the children of this point
        children = swc[np.logical_and(swc[:, 6] == point_id, swc[:, 1] != 1)]
        num_children = len(children)

        # If this is a new branch, register it
        if new_one:
            # Get the new point id
            start_value = point_id
            parent_value = -1

            nb_id = 0
            if tree is not None:
                nb_id = len(tree)-1
                parent_value = branch_id

            #print(nb_id, branch_id)
            # Look in function header to see what this is
            b_data = [nb_id, start_value, -1, branch_type, parent_value]
            b_data += [num_children, 0, 0]
            branch = np.asarray([b_data], dtype=int)

            # Write the branch into the tree hierarchy
            if tree is None:
                tree = branch
            else:
                tree = np.vstack((tree, branch))
            # The new branch id is the latest insertion into the hierarchy
            branch_id = len(tree)-1

        if num_children > 0:

            if num_children > 1:
                # Multiple children = new branching
                new_one = True
                # Update the current segment with its end point now that
                # we're about to branch
                tree[branch_id][2] = point_id  # len(points)-1
                order += 1
            elif num_children == 1:
                # No branching except for branches starting from the origin
                new_one = branch_id == 0

            for i in range(0, num_children):
                child = children[i]
                c_id = child[0]
                b_id = branch_id
                v = (swc, c_id, new_one, b_id, order, depth, tree, pts, pt_map)
                tree, pts, pt_map, depth = cls.build_structure(*v)
        else:
            # This is a dead end, update the current segment with its end point.
            tree[branch_id][2] = point_id
            tree[branch_id][7] = int(True)

        return tree, pts, pt_map, depth

**Comment by zeffii** [comment] 2016-08-27 09:35
*slaps forehead* I just realized the relation between n (label) and P (parent label) makes making edges almost trivial :)

**Comment by nantille** [comment] 2016-08-27 09:37
Yup edges are given automatically. :)

**Comment by zeffii** [comment] 2016-08-27 09:44
if I've come across pushy about getting code, it's because i have a weird obsession with parsing in general, and in this case I might learn something :)

**Comment by nantille** [comment] 2016-08-27 10:05
@enzyme69 Here's a quick test with 3d texture on a non-uv mapped curve. It doesn't look like it's going anywhere.

<img width="1552" alt="osl_3d_tex1" src="https://cloud.githubusercontent.com/assets/10866779/18026653/8283794c-6c4e-11e6-8302-1f4a6cff9863.png">
<img width="1552" alt="osl_3d_tex2" src="https://cloud.githubusercontent.com/assets/10866779/18026652/828218e0-6c4e-11e6-9f4a-ab4f8dcafe0c.png">


shader
sine3d(float    freq = 4,
        float   amp = 0.5,
        float   offset = 0,
        float   blur = 0.05,
        string  spacename = "object",
        output float resultF = 0,
        output color resultRGB = 0)
{
p = P

// Get the coordinates of the shading point.
float x = p[0];
float z = p[2];
  
// The arc tangent of the shading point will be in radians 
// (-3.142 to 3.142) ie -180 to 180 degress.
float theta = atan2(x,z);
  
// Generate a sine wave - remapped to 0 to 1.
float wave = (sin(theta * freq) + 1) * 0.5;
  
// Adjust the height and position of the sine wave.
resultF = wave * amp + offset;
  
// Get a filtered value of the wave height.
wave = smoothstep(resultF - blur, resultF + blur, p[1]);
  
// Control the mixing of two colors by the wave.
resultRGB = mix(color(1,1,1), color(0,0,0), wave);
}

**Comment by zeffii** [comment] 2016-08-27 10:07
thank you for the swc_tree.py .zip most interesting! nice use of np!

**Comment by zeffii** [comment] 2016-08-27 10:19
cool to see that these swc trees are also quite optimized in their raw state, no points where consecutive edges are on the same vector.

**Comment by zeffii** [comment] 2016-08-29 19:53
closing this as it isn't specific to Sverchok development, we can still add comments, but it won't appear in the open-issues list.

**Closed by zeffii** 2016-08-29 19:53 UTC
