### ISSUE TITLE
B28 - Viewer Draw edge width issue on mac (Mojave 10.16.4) 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2604] opened 2019-10-09 19:42 UTC
Changing the VD node’s edge width does not affect the line thickness in the viewport (On MacBook Pro 15”, retina display 2880 x 1800 res). The line thickness seems to be stuck at 1px.. and on retina display it seems to be also aliased and thus broken and hard to see.

![SV-B28-ViewerDraw-EdgeThinkess-Bug](https://user-images.githubusercontent.com/2083719/66514510-45087480-eaab-11e9-924f-f31c56bf837c.gif)

**Comment by zeffii** [comment] 2019-10-09 19:46
1. for now use `gl_polygon_offset` toggle.
2. not sure about the line thickness.

**Comment by zeffii** [comment] 2019-10-09 19:49
we just call `bgl.glLineWidth(width)`  ,this may not be implemented in the OSX wrapper..i'll ask around

**Comment by zeffii** [comment] 2019-10-09 19:52
https://developer.blender.org/T57570#549043  .. unlucky for now.

**Comment by DolphinDream** [comment] 2019-10-09 19:55
The gl_polygon_offset takes care of the line not being broken (good to know tip.. perhaps this setting should be ON by default?)

Also the gl_wireframe seems to have a weird effect once it’s toggled on/off. The rendering in the viewport goes to wireframe but it never goes back to normal once the gl_wireframe is untoggled.. As a matter of fact you can even delete the VD node and the rendering is not cleared.. even if you start a new file the rendering is not cleared. You need to restart blender to get rid of it.

![SV-B28-ViewerDraw-gl_Wireframe-Bug](https://user-images.githubusercontent.com/2083719/66515378-083d7d00-eaad-11e9-8a12-49c9ec77b32a.gif)

**Comment by zeffii** [comment] 2019-10-09 19:56
there might be line thickness implementations in a `vertex shader/fragment shader`  combination

You need to update your Sverchok. i pushed a fix for that a few minutes ago

**Comment by zeffii** [comment] 2019-10-09 19:56
(i mean i fixed the Wireframe bug)

**Comment by zeffii** [comment] 2019-10-09 20:11
i'm going to close this for the time being - because this issue is not directly caused by Sverchok - but rather the specs of the openGL wrapper we use. I will periodically look around for an appropriate shader that will implemented edge width (preferably with AA too. )

sorry @DolphinDream

**Comment by zeffii** [comment] 2019-10-09 20:11
but do `pull` b28_prelease_master`  to get the wireframe fix

**Closed by zeffii** 2019-10-09 20:11 UTC

**Comment by zeffii** [comment] 2019-10-09 20:25
for later..
https://stackoverflow.com/questions/15276454/is-it-possible-to-draw-line-thickness-in-a-fragment-shader

**Comment by DolphinDream** [comment] 2019-10-09 20:25
will pull. Btw, I rely on edge thickness quite a bit in my noding/developing so I really hope this issue is solved sooner than later. This could be related to the fact that annotation lines in B28 area also 1px thick no matter of what thickness I set it to (https://developer.blender.org/T57993, https://developer.blender.org/T57570)?

**Comment by zeffii** [comment] 2019-10-09 20:27
eventually i will set the polygonoffset as default. i might even do it tomorrow - fixing the wireframe stuff resolved the issue that i thought was caused by the polygonoffset (which i;m not sure it was not. )

**Comment by zeffii** [comment] 2019-10-09 20:39
i can only offer solutions for inside sverchok (a shader) - no ETA.

but... `vd basic lines` is a perfect place to start if you want to do your own fragment shader. clone it. rename it, and try some of the stackexchange solutions.  that's what i would do ( or will do eventually )

**Comment by DolphinDream** [comment] 2020-04-01 18:17
Where is the code I can look at to test how I can make the edge width greater than 1px? 

Also, I would like to be able to make smooth (antialised) lines. Any pointers to how this could be done?

**Comment by zeffii** [comment] 2020-04-01 18:43
you linked earlier to the solution by Blender devs, that code commit includes a `fragment shader` , I didn't study it yet. and I can't speculate on how it works. the `vd_basic_lines` branch is a branch I resurrected as it would be a starting point to figure out how to draw thicker lines while keeping the code to a minimum. just implementing the edge drawing. 

drawing AA tips... nope, i've not been successful with that either myself. ever.

I did collect that list of links in the VD experiments thread as a general information source, for me and others who have some "itch to scratch".  dig through it, i can't regurgitate it to anything simpler.

**Comment by zeffii** [comment] 2020-04-01 18:48
it tooks me 2 weeks to figure out how to dashed draw... so i'm not a great person for advice.

**Comment by DolphinDream** [comment] 2020-04-01 19:25
@zeffii Is there a SV vd_basic_lines branch on github ?

**Comment by DolphinDream** [comment] 2020-04-01 19:31
Actually, it seems it’s called macos_shader_test

**Comment by zeffii** [comment] 2020-04-01 20:27
ah yes :) `macos_shader_test` is a starting point. I find necessity is the best inspiration, and right now this is not a blip on my radar. If you get something going or seek help i'll be happy to look at code.

**Comment by zeffii** [comment] 2020-04-01 20:33
but look at the file history of the vd_basic_lines node.. maybe the last commit was a "commit too far" , you'll see I added a few things that seem necessary as they are present in the Blender thick lines code too, .. i just kind of stopped.

**Comment by DolphinDream** [comment] 2020-04-01 20:34
I found this.. on blender (not sure if you based your example on this or not).

https://developer.blender.org/rB014eb69cf858036816d12a4b92ffe6681978b683

**Comment by DolphinDream** [comment] 2022-02-14 16:19
Btw, I found this cool paper on rendering thick / dashed / dotted lines with shaders 🙂 ( @zeffii )

https://jcgt.org/published/0002/02/08/paper.pdf

<img width="825" alt="Shader Based anti-aliasing dotted lines" src="https://user-images.githubusercontent.com/2083719/153902904-0924d297-3211-4a0f-9a34-8ed72812d56b.png">


Published here: https://jcgt.org/published/0002/02/08/

_Note: Checkout the Supplemental MOV videos for demo.. pretty cool_ 

This was published in 2013 (9 years ago) so perhaps better techniques were invented since, but this one looks promising. They even provide the python source code. nice

**Comment by DolphinDream** [comment] 2022-02-15 17:58
Also.. there's another article (2016) I came across on the topic (https://vitaliburkov.wordpress.com) which references this paper, but claims that it's not as optimal (memory/speed) as his own solution, which presumably is a simplified/optimized version of a similar algorithm in *GPU Gem 2* (chapter 22).

https://developer.nvidia.com/gpugems/gpugems2/part-iii-high-quality-rendering/chapter-22-fast-prefiltered-lines
