### ISSUE TITLE
Viewer Draw node render not removed after connected nodes are deleted

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1317] opened 2017-03-08 01:23 UTC
Is this a bug or a feature ? If i delete nodes connected to the viewer node the rendering remains in the viewport.  I have to first toggle viewer draw to hide.. delete the connected node, then toggle back to show to make the drawing not linger around.

This is using the current master  (SHA: b49a45b6ac)

![viewernodebug-demo1](https://cloud.githubusercontent.com/assets/2083719/23685746/c657367e-0373-11e7-9a4b-5a77dbd6adcc.gif)

**Comment by ly29** [comment] 2017-03-08 08:17
Okay I see what happens. 

That should be dealt with. I guess we need an ```update``` function for that.


```python
def update(self):
    if not (s.linked for s in self.inputs):
        #turn of drawing...
```

**Comment by ly29** [comment] 2017-03-08 09:09
How it looks now.
```python
    def update(self):
        if not ("matrix" in self.inputs):
            return
        if self.inputs[0].links or self.inputs[2].links:
            callback_disable(node_id(self))
```

Should perhaps be.
```python
    def update(self):
        if not ("matrix" in self.inputs):
            return
        if not (self.inputs[0].other or self.inputs[2].other):
            callback_disable(node_id(self))
```

**Comment by zeffii** [comment] 2017-03-08 15:36
`update` is not currently called in that scenario, i think we might end up tagging along on a scene_update_pre and get all bgl nodes if they have useful sockets linked, and callback disable if not the case.

**Comment by zeffii** [comment] 2017-03-08 16:05
```python
@persistent
def sv_main_handler(scene):
    """
    Main Sverchok handler for updating node tree upon editor changes
    """
    for ng in sverchok_trees():
        # print("Scene handler looking at tree {}".format(ng.name))
        if ng.has_changed:
            print("Edit detected in {}".format(ng.name))
            for n in ng.nodes:
                if n.bl_idname in {'ViewerNode2'}:
                    n.remove_callback_if_needed()

            ng.process()

```
where the viewer implements the callback removal as @ly29 suggests
```python
    def remove_callback_if_needed(self):
        if not (self.inputs[0].other or self.inputs[2].other):
            callback_disable(node_id(self))  
```

it might be seeing things, but it seems if that function was called `update` something will filter it out, but anything else seems ok.

**Comment by zeffii** [comment] 2017-03-08 19:50
oh crap.. i didn't realize vdmk2 already had an `update` function, and so i was adding a second one. (not sure if pylinter should have cried about that..) 

OK. 

```python
    def update(self):
        if not ("matrix" in self.inputs):
            return
        if not (self.inputs[0].other or self.inputs[2].other):
            callback_disable(node_id(self))        
```
should work.. but it does need 
```python
@persistent
def sv_main_handler(scene):
    """
    Main Sverchok handler for updating node tree upon editor changes
    """
    for ng in sverchok_trees():
        # print("Scene handler looking at tree {}".format(ng.name))
        if ng.has_changed:
            print("Edit detected in {}".format(ng.name))
            for n in ng.nodes:
                if n.bl_idname in {'ViewerNode2'}:
                    n.update()

            ng.process()
```
and all nodes that have bgl callbacks will need to be included in the lookup dict.

**Comment by zeffii** [comment] 2017-03-08 20:45
well, i considered this a "feature without a purpose" not a bug..

but it is committed anyway.. and a fix for stethoscope mk2 too. https://github.com/nortikin/sverchok/pull/1323

**Closed by zeffii** 2017-03-08 20:45 UTC
Labels: bug, low priority
