### ISSUE TITLE
Small bug in otherwise EXCELLENT Tutorial #1

### ISSUE THREAD

**Issue by timbo1711** [nortikin/sverchok#3260] opened 2020-05-19 05:01 UTC
## Problem statement

Intro Lesson 1 has a bug when applied to Blender 2.82

## Steps to reproduce

1. Follow EXCELLENT tutorial instrux until instructed to put in formula for 4 edges
2. Enter either format for formula (I tried both)
3. Note the formula box looks somewhat different, I'll try to paste here

## Expected result

Should have seen edges AND THE NUMBER 4 for number of edges

## Actual result

No edges and the number was 1, not 4

## Sverchok version

I downloaded the zip, current version, and told Blender 2.82 to add add-on from zip.
![image](https://user-images.githubusercontent.com/25371113/82286549-94792200-9963-11ea-903a-60e42d84402d.png)

**Comment by zeffii** [comment] 2020-05-19 07:23
the tutorial is writen for b.279 and a much older version of sverchok. As you can see from the screenshots in the tutorial, it was working fine. As you've learned, it does not translate 1-1 to b28.

I started updating the tutorial / induction  last week, but the progress is slow .
https://github.com/nortikin/sverchok/pull/3198


closing this because, it's a duplicate of https://github.com/nortikin/sverchok/issues/3139  - and i'm working on it. :)

**Closed by zeffii** 2020-05-19 07:23 UTC

**Comment by zeffii** [comment] 2020-05-19 07:30
in the meantime you could use the "Formula+" node ` alt+Space -> formula+ `) 

![image](https://user-images.githubusercontent.com/619340/82297739-5d326180-99b3-11ea-915a-a4bdc92e6ebf.png)

**Comment by enzyme69** [comment] 2020-05-19 07:30
You rock @zeffii, and welcome @timbo1711

**Comment by timbo1711** [comment] 2020-05-19 11:29
Thanks!

________________________________
