### ISSUE TITLE
Cannot find a way to make single user duplicate of a monad node group

### ISSUE THREAD

**Issue by Alexey-Akishin** [nortikin/sverchok#2250] opened 2018-07-20 23:04 UTC
I have created a monad node group, then duplicated it. But if I change something in the duplicate group, original also changes. This is what I want most of the time, but sometimes I need to edit monad node group independently.

This is possible with Blender node groups (for example see [this](https://blender.stackexchange.com/questions/19467/how-to-make-independently-editable-copies-of-the-same-node-group)).

Sverchok version 0.5.9.6

**Comment by enzyme69** [comment] 2018-07-21 01:40
Very likely you want to make duplicate of whole node tree that makes the Monad. I have not tried it. But from Multi User sharing data to Single User, that is the logic.

Mixing the Monad between different node tree is also possible, I think...

**Comment by enzyme69** [comment] 2018-07-21 01:45
Ok... I am wrong, I think it's not as easy as copy pasting into different node tree, needs a way to "duplicate" Monad data and make it unique single user.

**Comment by zeffii** [comment] 2018-07-21 07:35
i thought we did implement this. if _not_, i will.

**Comment by zeffii** [comment] 2018-07-21 07:52
i'll think out loud here..
- [ ] a new operator for duplicate/unique (and keymap..)
- [ ] operator must make a new node_tree, a new monad node. with all same settings.

**Comment by zeffii** [comment] 2018-07-21 20:18
this will take a while btw.  and it's hot weather : /

**Comment by zeffii** [comment] 2018-08-06 14:00
i started working on this the other day by the way. this issue is not forgotten. (but warm weather just makes me open up the computer and stare into space)

**Comment by zeffii** [comment] 2018-08-15 14:31
the operator almost ready, btw. maybe tonight.

**Comment by zeffii** [comment] 2018-08-18 17:36
this is now implemented. see the PR above for details on how to activate it. (update required)

new PR opened for further features regarding usability. https://github.com/nortikin/sverchok/pull/2260

**Closed by zeffii** 2018-08-18 17:36 UTC
Labels: enhancement, maintenance
