### ISSUE TITLE
SV Skin Mesher is twisting, while Blender Skin Modifier is not twisting...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3298] opened 2020-06-01 04:45 UTC
I noticed something really strange, if I use Skin Mesher node the result is twisting, but if I output BMesh Edge and apply Skin Modifier, the result is clean:

[limited_dissolve_003.blend.zip](https://github.com/nortikin/sverchok/files/4709406/limited_dissolve_003.blend.zip)
<img width="1680" alt="Screen Shot 2020-06-01 at 2 42 59 pm" src="https://user-images.githubusercontent.com/3952687/83376681-778a2780-a416-11ea-8ab3-9d178ed88ea1.png">

**Comment by Durman** [comment] 2020-06-01 05:00
I think it looks more like proposal not a bug.

![2020-06-01_08-56-54](https://user-images.githubusercontent.com/28003269/83377254-19dde700-a3e6-11ea-8a30-e00a1ec52fa7.png)

**Comment by zeffii** [comment] 2020-06-01 08:06
@enzyme69 

skinmesher does more than you think, and there are N panel options for it.
![image](https://user-images.githubusercontent.com/619340/83388762-4ba77b80-a3ef-11ea-80a5-6055d535bba9.png)

**Comment by zeffii** [comment] 2020-06-01 09:14
unset the "mark all" and the twisting goes. 

## Some documentation

More often than not this node is is used in the scenario where there are branching paths, each branch vertex ( vertex with 3+ edges ) will be marked as a root. The setting of roots, by default isn't done in the Blender Skin Modifier, it is done manually and interactively. Because the SkinMesher must provide a way to automatically set roots it finds the branching verts and sets them as roots by default, you can switch off this behaviour in the N panel. 

There's not a lot to configure, it's a complex node and it does a lot of work in the background.

**Comment by enzyme69** [comment] 2020-06-04 23:00
I still cannot figure out the proper way to fix the Twisting of Bevel Curve extrude no matter what... so I made a video:
https://youtu.be/sK9bEzXUgFg

Skin Modifier / Skin Mesher gives no twisting. 

Is there in any way we could avoid twisting? I tried all algorithm available in SVerchok.

**Comment by enzyme69** [comment] 2020-06-04 23:10
<img width="820" alt="Screen Shot 2020-06-05 at 9 09 14 am" src="https://user-images.githubusercontent.com/3952687/83819048-3b9fdc80-a70c-11ea-8565-feb346a46d86.png">

If I use Polyline Viewer and then bringing it back as mesh, it seems to "fix" it, but is there any cleaner way without having to output a Curve?

**Comment by Durman** [comment] 2020-06-05 04:19
Agreed the node can't interpolate such shape correctly.
![2020-06-05_08-17-32](https://user-images.githubusercontent.com/28003269/83836638-1e1b4480-a705-11ea-88ec-6fe6d94dea91.png)

**Closed** 2020-06-05 08:15 UTC
Labels: Proposal

**Comment by zeffii** [comment] 2020-06-05 08:16
use a new thread, this has nothing to do with the title "Skin Mesher".
