### ISSUE TITLE
Animatable Nodes

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3128] opened 2020-04-27 14:30 UTC
Right now when the frame changes a global update is performed which is bad idea because many parts of the node tree may not change during the animation.
I propose to add a `is_animatable ` property to the nodes that can be affected by a scene change, (Objects in, F-Curve, Objects Id selector...) so when the frame change is done the system calls `process_from_animatable ` in stead of a global `process`.
This property could be exposed in the N-Panel properties (enabled by default) so the user can disable it in the desired node to make the animation faster

**Comment by Durman** [comment] 2020-04-27 15:13
I'm totally agree that update whole tree during `frame change` event is inefficient. There is no sense to update some nodes during such events. 

Detect such nodes by properties also looks good. I would suggest to create special class for such nodes (`mixin`) even if this class will have only one properties. It is good because can be documented. 
Also I would suggest to keep all `mixins` one module so it will be simple investigate them during creating new nodes.

**Comment by zeffii** [comment] 2020-05-01 09:40
@vicdoval  can you have a look at SNlite hot reload (ctrl+enter) 

https://github.com/nortikin/sverchok/blob/766eeedcbe4adc5ab380d9b05094fdb1b3c33e55/utils/text_editor_plugins.py#L60-L65

it isn't triggering a node process, i think since the animatable stuff landed.

**Comment by zeffii** [comment] 2020-05-01 09:44
hmm.. i think it's something else : )     n.load() isn't even called..

**Comment by zeffii** [comment] 2020-05-01 10:33
it seems I chopped off part of the file that registers the operator and the keymap.

**Comment by zeffii** [comment] 2020-05-01 13:23
out of curiosity @vicdoval  have you seen this error before?
```
location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 366, in update
    self.sv_update()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 237, in sv_update
    process_from_nodes(self.get_nodes())
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 457, in process_from_nodes
    node_names = [node.name for node in nodes]
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 457, in <listcomp>
    node_names = [node.name for node in nodes]
AttributeError: 'SvFCurveInNodeMK1' object has no attribute 'name'

```
This error appears when i disconnect a node, like 
![image](https://user-images.githubusercontent.com/619340/80808234-605ddd00-8bbf-11ea-84c0-84cd2a9db1c6.png)

can you think of a reason why `SvFCurveInNodeMK1` wouldn't have a name attr ? I suspect other nodes have this too.

**Comment by zeffii** [comment] 2020-05-01 13:26
i'll find another node that does this that isn't in the list of prop_search problem nodes ..

**Comment by zeffii** [comment] 2020-05-01 13:28
yeah even just unconnecting and reconnection the stethoscope here
![image](https://user-images.githubusercontent.com/619340/80808674-4c66ab00-8bc0-11ea-8e89-53951b1d792b.png)

gives 

```
ocation: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 366, in update
    self.sv_update()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 237, in sv_update
    process_from_nodes(self.get_nodes())
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 457, in process_from_nodes
    node_names = [node.name for node in nodes]
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 457, in <listcomp>
    node_names = [node.name for node in nodes]
AttributeError: 'SvStethoscopeNodeMK2' object has no attribute 'name'
```
which is pretty harmless, but somethings happening :)

**Comment by zeffii** [comment] 2020-05-01 13:29
i'll go back to my own corner now :)

**Comment by vicdoval** [comment] 2020-05-01 14:01
I will look into it :) i saw something similar when fixing #3136 it is pretty weird 👽

**Comment by zeffii** [comment] 2020-05-01 14:03
it's almost like `nodes` is populated by items that are not in fact...nodes.

**Comment by zeffii** [comment] 2020-05-01 14:07
i would temporarily explode that list comprehension..
```
node_names = [node.name for node in nodes]
```
into a forloop a
```
node_names = []
for node in nodes:
    if hasattr(node, "name"):
        node_names.append(node.name)
    else:
        print("wtf", node, type(node))
```
lol.

**Comment by vicdoval** [comment] 2020-05-01 15:48
Does it happen always? I can't reproduce the error

**Comment by zeffii** [comment] 2020-05-01 16:05
i'm happy to report it doesn't happen in master :)

**Comment by zeffii** [comment] 2020-05-01 16:10
and neither does my branch untill i hit refresh python../ f8

**Comment by zeffii** [comment] 2020-05-01 16:13
but I did just have a crash to desktop from Master, after fiddling around with a few nodes after an f8.

**Comment by zeffii** [comment] 2020-05-01 16:18
BUT that was also not something i can reproduce in the last 5 minutes

**Comment by Durman** [comment] 2020-05-01 16:39
It is probably related with the code which was removed by Vicdoval from update system with statement like - "Looks like no use". The key word is invalid link.

**Comment by zeffii** [comment] 2020-05-01 19:26
@vicdoval  woah.
```
Something not very important happend in Blender memory <bpy_struct, WM_OT_context_modal_mouse at 0x000001D8AA9ED258> <class 'sverchok.nodes.vector.math_mk3.SvVectorMathNodeMK3'>
```

**Comment by vicdoval** [comment] 2020-05-01 19:53
@zeffi Blender surprises 😄

**Comment by zeffii** [comment] 2020-05-01 20:18
it seems that for brief periods of time  `ng.nodes`  is not what we expect.

**Comment by zeffii** [comment] 2020-05-01 20:19
i don't have the patience for this anymore.

**Comment by zeffii** [comment] 2020-05-02 08:17
i get a pretty consistent blender crash to desktop for this kind of scenario.
![image](https://user-images.githubusercontent.com/619340/80859043-006a4380-8c5e-11ea-9bcd-2e17a1b28516.png)
1. cut those links / or manually unlink them,
2. refresh python
3. try to relink verts
4. boom.

**Closed** 2020-05-03 11:10 UTC
Labels: Proposal
