### ISSUE TITLE
Points Inside Solid wrong result

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4939] opened 2023-07-03 18:23 UTC
I stumbled upon a case with a closed solid and a point outside it where the point is considered inside. Here's a blend file with the problem :
[Points Inside Solid problem.zip](https://github.com/nortikin/sverchok/files/11940071/Points.Inside.Solid.problem.zip)
Enabling the refine solid option solves the problem, however, sometimes refining a solid causes the Mesh to Solid node to crash, so I cannot enable the option.

**Comment by satabol** [comment] 2023-08-18 11:15
@Durman, @ArpegorPSGH I think this is not a bug. The problem is in source mesh shape. Some faces with different normals are merged. If you turn on face orientation you will see some faces are merged:
![image](https://github.com/nortikin/sverchok/assets/14288520/b416ba59-3420-4a35-800b-c15079b3be46)

If you move this vertex a little then result is good:
![issue_4939](https://github.com/nortikin/sverchok/assets/14288520/93ad90b3-09eb-43fd-ae49-6aef06498f5b)

**Closed** 2023-08-19 12:16 UTC
Labels: bug :bug:
