### ISSUE TITLE
Nodes (red /error) don't automatically revert to non-error state/color when copied

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2456] opened 2019-06-16 00:00 UTC
Random copy with list item everything works but there is one node that turns red with blender 2.8 
If i do the same with blender 2.79  then i don't have this problem , is this normally or must i change something ? 

![image](https://user-images.githubusercontent.com/49908008/59557436-7f20a880-8fda-11e9-958c-36192ff051a9.png)

**Comment by zeffii** [comment] 2019-06-16 10:14
i can reproduce this only in one scenario, namely if the node is red/error state and then you copy it, the copy can not be returned to the default colour.  
![image](https://user-images.githubusercontent.com/619340/59562688-fcc2d380-902f-11e9-8d18-5dd94c6a49d3.png)

there are more nodes that do this,  but from your description of events I think this might not be the same (known...)  bug.

**Comment by zeffii** [comment] 2019-06-16 10:19
related #2241 #2081

**Comment by zeffii** [comment] 2019-06-16 10:20
yeah :) i would like this to be fixed.

**Comment by BennyGovaerts** [comment] 2019-06-16 11:56
yes , you are right if i add a new list item node and remove the red one then it works , thanks for the tip

**Comment by zeffii** [comment] 2019-06-16 13:18
i don't fully understand the error, and haven't had much quiet time to think about it. no ETA.

it does bug me :)

**Comment by zeffii** [comment] 2019-06-17 12:35
note to self:

as the node in the error state is copied, the new node is not added to the `ng['error_nodes']` because it has not been told to process yet (and has no input sockets that would force it to do that..)

**Comment by zeffii** [comment] 2019-06-17 13:39
cool. i think this will be added to the `node base class`

```python
    def copy(self, node):
        """
        if the node being copied currently is listed in the error_nodes dict
        then copy two properties from the dict ( use_custom_color, color ) and apply those
        to the copy.
        """
        ng = self.id_data
        try:
            import ast
            error_dict = ast.literal_eval(ng["error nodes"])
            error_item = error_dict.get(node.name)
            if error_item:
                self.use_custom_color, self.color = error_item
            
        except Exception as err:
            print('cosmetic error during copy', err)
            
```

**Comment by Durman** [comment] 2019-06-17 17:28
In this case code something like `super().copy(self, node)` should be inserted into overrided method of base class in some nodes.

**Comment by zeffii** [comment] 2019-06-17 18:23
durman, instead:  ` SverchCustomTreeNode.copy(self,, node) `

**Comment by zeffii** [comment] 2019-06-17 18:30
altho `super().<function>(args)`  should indeed be the way to go.

for some reason it didn't work https://github.com/nortikin/sverchok/issues/2444#issuecomment-501152982 .

i'm just happy to find a reasonable fix for this longstanding bug :)

**Comment by zeffii** [comment] 2019-06-20 09:02
i think what i'll do is make a new SverchCustomTreeNode method caller inside `def copy`, to call a function defined in any node subclass, in particular `sv_copy`

```python
class SverchCustomTreeNode:
    ...
    def copy(self, node):

        ... <standard copy code> standard copy behaviour for all nodes

        # this is used for nodes that require quite a bit of extra work to make good copies.
        if hasattr(self, "sv_copy"):
            try:
                self.sv_copy(self, node)
            except Exception as err:
                print(f'sv_copy failed in {self.name} with error {err})


```
that way all i have to add `sv_` infront of the copy code of any node that currently defines its own `copy` function. 

- incidentally, most nodes that do define their own `copy function`, only reset their `self.n_id` , this too could be `self.reset_node_id` (attr)

**Comment by Durman** [comment] 2019-06-20 09:56
In this case I'm voting for `sv_free` and `sv_insert_link` as well. Even if does not use this methods yet.))
Code from material node by the way:
```Python
    def copy(self, node):
        self.material_name = ''
        self.n_id = ''
        self.material = None
        self.shader_node_group = None
        self.children.clear()

    def free(self):
        # We have to call this method for keeping Blender database in actual condition
        del self.main_material
```

**Comment by zeffii** [comment] 2019-06-20 11:05
yes to `sv_free`,    not sure about `insert_link` yet :)

**Closed** 2019-11-17 11:52 UTC
Labels: SV for b2.8, bug
