### ISSUE TITLE
Build NURBS Curve - Cyclic

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4674] opened 2022-09-21 05:26 UTC
## Problem statement

It seems cyclic mode does not work properly

![image](https://user-images.githubusercontent.com/28003269/191421191-234e7dc5-bb6c-4baa-98b7-0b0b0f828f7f.png)

[untitled.zip](https://github.com/nortikin/sverchok/files/9613235/untitled.zip)

**Comment by portnov** [comment] 2022-11-04 14:46
This is actually a duplicate of #3717. The problem here is not with "cyclic", but with "normalize knots": if you disable it, problem disappears.

**Closed** 2022-11-04 14:52 UTC
Labels: bug :bug:, NURBS
