### ISSUE TITLE
"Arbitrary frame" option for "Curve Frame" node doesn't work

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3424] opened 2020-07-24 20:09 UTC
Worked previously. Now it doesn't.

![arbitrary_frame_fail](https://user-images.githubusercontent.com/66558924/88431111-59331d80-ce02-11ea-8dc2-8340be6b06ce.jpg)

**Comment by zeffii** [comment] 2020-07-24 20:39
some back history?  https://github.com/nortikin/sverchok/issues/3307

if the node is red, you can view the error either
-  in the Terminal ( Console ) or
-  in the sverchok n panel, turn on Show Error in Tree
   
![image](https://user-images.githubusercontent.com/619340/88433484-7960dd80-cdfe-11ea-8b93-037c609398ea.png)

i don't know what that error means : )

**Comment by zeffii** [comment] 2020-07-24 20:48
`ZeroCurvatureException` is located in utils.curve.algorithms.py  and is raised in utils.curve.core.py without being imported. @portnov  ?

**Comment by rendetto** [comment] 2020-07-24 21:03
I've never noticed the option for viewing the error in the tree - that's cool :)
Thanks for the suggestion.

**Comment by zeffii** [comment] 2020-07-24 21:06
@rendetto   not everyone likes it, that's why it's optional :)

@portnov , maybe `ZeroCurvatureException` should be moved into `core.py` ?

**Comment by zeffii** [comment] 2020-07-24 21:16
it's not clear to me if it makes sense to pass a "Line curve" to the Curve Frame node.

**Comment by rendetto** [comment] 2020-07-24 21:37
This particular case is to demonstrate the node option operation that is broken. 
In general the option "arbitrary frame" is one way to bypass the error that halts the calculations in case you have a part of a curve(or surface) that have zero curvature.
Imagine you need to read many curvatures along a curve simultaneously and the curve had a flat region in the middle. If that option for skipping is not available the node will fail because of the zero curvature in just one region.

**Comment by zeffii** [comment] 2020-07-24 21:41
cool, i have almost no experience with the curve/surface class, so i also await @portnov 's view :)

**Comment by portnov** [comment] 2020-07-25 07:39
ZeroCurvature means that the curve, literally, has zero curvature at the given point — this is obviously the case for straight line, also it is the case for curves that change direction of their curvature (S-shaped curves, for example). It is not possible to mathematically calculate the normal of such curve at such point, so there is an exception.

**Comment by portnov** [comment] 2020-07-25 07:41
What I can do, is to skip the particular value of T in case there are several T's provided and only some of them give error. This can also be unexpected: for example, you've passed 5 values of T, and as a result you have only 4 frames, because one of T values results in error...

**Comment by portnov** [comment] 2020-07-25 07:57
Well, this node appears to work "as designed". For specific cases, for example for extrusion of one curve along another, there are several modes that are usable in some other cases.
Probably I'll add some of such modes into "curve frame" too; at least "Householder" and "Tracking", and probably "track normals"... some day... :)

**Comment by rendetto** [comment] 2020-07-25 08:28
Skipping values of T doesn't sound useful for me either. 
The problem I got now is - no matter I'm using "Raise Error" or "Arbitrary frame", the node always throws an error and the whole tree just stuck on that node. Previously it was fine, working like that:

![arbitrary_frame_succsess](https://user-images.githubusercontent.com/66558924/88452681-60d9dd00-ce69-11ea-96d6-ace86222e828.jpg)

**Comment by portnov** [comment] 2020-07-25 09:01
Ah, I see

**Comment by portnov** [comment] 2020-07-25 09:05
@rendetto I've pushed a fix into master. Please check.

**Comment by rendetto** [comment] 2020-07-25 09:36
It's working even better now.
Thanks a lot!

**Closed** 2020-07-25 12:03 UTC
