### ISSUE TITLE
Monad issue: not saved correctly?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1485] opened 2017-04-08 12:51 UTC
I'm working for the noise/random tutorial, for convenience i would save some groups of nodes into monad and save them in .json format. I saved monad like this in the image:
![rand_monad01](https://cloud.githubusercontent.com/assets/1275858/24828995/d8b43c72-1c69-11e7-964e-8a282962b1c0.png)
the re-imported in another node-tree it appears in this way:
![rand_monad02](https://cloud.githubusercontent.com/assets/1275858/24829000/f775b1a4-1c69-11e7-8732-79ed150e4121.png)
The monad should be connected to be imported properly? Since i didn't use so much the monads i'm not sure if i'm making the right thing, Any enlighting is appreciated...
You can grab the random_monad [here](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/json/tutorial_noise/random_monad.json)

**Comment by zeffii** [comment] 2017-04-08 13:22
you should share the .blend instead.. if you want us to debug what's happening to the monad.

**Comment by zeffii** [comment] 2017-04-08 13:43
sometimes the nodes internal to the monad will turn orange based on the fact that it's not getting any data.. yet it is connected. as soon as you hook some content into the monad interface (from the outside) it should work.

**Comment by zeffii** [comment] 2017-04-08 14:18
![image](https://cloud.githubusercontent.com/assets/619340/24829692/0fdf58a0-1c77-11e7-90f5-6368b32ca971.png)

**Comment by zeffii** [comment] 2017-04-08 14:20
![image](https://cloud.githubusercontent.com/assets/619340/24829698/3c9da6c6-1c77-11e7-842c-098b1b912428.png)

**Comment by zeffii** [comment] 2017-04-08 14:21
removed the Line and Texture node..  exported as gist  - https://gist.github.com/e5eee9a3fcc5586b57cb129b3fd9245d

**Comment by zeffii** [comment] 2017-04-08 18:06
did this answer the question?

**Comment by kalwalt** [comment] 2017-04-08 18:08
yes and no, i don' understand why my monad is not imported as i espect. Your instead is imported fine. Probably i saved it in the wrong way?

**Comment by kalwalt** [comment] 2017-04-08 18:12
there are two option for save as group, i think i used the first option: Groups -> make groups (+relink) but maybe is not appropriate.

**Comment by portnov** [comment] 2017-04-08 18:21
Do we have an option to export only selected monad node (with contents) to json and then import?

**Comment by zeffii** [comment] 2017-04-08 18:21
not sure what you did..

- don't export gist while inside a monad

**Comment by zeffii** [comment] 2017-04-08 18:28
@portnov the code doesn't make a distinction between a selected regular node ..or a selected Monad Node.

**Comment by zeffii** [comment] 2017-04-08 18:30
Monads are definitely things you need to experiment with, they have little documentation - because despite the complexity of the code... the user facing functionality isn't very mysterious.

oh btw. Object sockets are not supported (fully )

**Comment by kalwalt** [comment] 2017-04-08 18:33
> Monads are definitely things you need to experiment with, they have little documentation - because despite the complexity of the code... the user facing functionality isn't very mysterious.

yes, this is sure,i will make a reserach in this sense.

**Comment by zeffii** [comment] 2017-04-09 12:05
of you can share a screencast / of make a reproducable step by step walkthrough, i'd be happy to investigate - until such time i will close this.

**Closed by zeffii** 2017-04-09 12:05 UTC

**Comment by kalwalt** [comment] 2017-04-09 12:44
ok i will see. Thanks again!

**Comment by zeffii** [comment] 2017-04-09 12:46
i'm happy to fix any monad related stuff, but i need to know what you did :)
