### ISSUE TITLE
New nodes?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#517] opened 2015-01-09 05:34 UTC
Hi all.
After playig with Sverchok a bit, it seems to me it lack some number of higher-level nodes. I wonder why? Is it like in contradiction with Sverchok's philosophy or just because no one managed to implement them yet? In last case, i beleive i can help :)
Most of these can be implemented via combination of existing nodes. But such implementation will cause maintainability problems (it's harder to work with a 100-nodes tree than with a 20-nodes), and, potentially, performance problems. Moreover, i beleive such nodes could become sort of higher-level building blocks, and used several times even in one tree.
So here a propose a list of such nodes. Let's discuss, maybe some of this functionality will be better to have in some of existing nodes, or split one item into two to have more orthogonal set of nodes.
Order is random, i put numbers only for futher reference.

1. "N-Gon". Generate a regular polygon with N sides. This is, in my mind, a generalization of Circle node. Added features: 1) optional randomization of vertices location, with separate control over randomization amplitude in R (radius) and Phi (angle) directions; 2) option to connect n'th vertex not with (n+1), but with (n+k) — this will create star-shaped polygons. The last option, in most cases, will be usable only in combination with existing "Intersect Edges" node. I have an implementation of this — i'll do a pull request if you wish.
2. "Zip vertices". Given two lists of vertices, produce a list of edges, which connects n'th vertex from first list with n'th vertex from second (obviously, it will need to re-enumerate vertices first). Now it can be implemented with "Range Int" + "List Length" + "List shift" + "List match" + "List Zip". Probably, it will be enough to add new output slot to List Match node, which will output pairs of indicies of matched items (not items themselve, but their indicies).
3. "Shuckhov". Given two lists of vertices, produce a list of edges, which connects n'th vertex from first list with (n+k)'th and with (n-k)'th vertex from second list (do `wrap' if needed). For example, for two circles of 10 vertices each and with k=3 or 4 this will produce some part of one-sheet hyperboloid (smth like Shukhov's tower http://dic.academic.ru/pictures/wiki/files/83/Shukhov_tower_by_Sergei_Arsenyev.jpg) 
![shukhov](https://cloud.githubusercontent.com/assets/284644/5678747/35144e8c-9817-11e4-85be-35dfdaa5d623.png)
. Useful mostly in comibnation with "Intersect Edges". I have an implementation of this as a ScriptNode.
4. "Fibonacci". Produce Fibonacci's sequence. Inputs: number of items to produce, first and second items (default 1.0). Maybe also Maximum (to rescale whole created sequence so that last number will be equal to given maximum)? Output: N float numbers. I have an implementation of this as a ScriptNode.
5. Exponential sequence. Given x_0 and alpha, produce sequence with x_n = x_0 * exp(alpha*n) for given range of n (from .. to). Or maybe better specify exponent's base explicitly (x_n = x_0 * base^n) ? (this can be implemented with Range Float + Math, but why do we need two nodes instead of one?...). Maybe better add this as an option to Range Float node.
6. "Cartesian product". Given two sets of vertices (V1 of M vertices and V2 of N vertices), produce a (concatenated) set of copies of V1, each of which is translated (moved) to location of one of vertices from V2. So that will produce M*N vertices. For example, given V1 = output from Line node, and V2 = 90-degrees rotated output from the same Line node, this will produce output like of Plane node. Given V1 = output from Plane and V2 = (rotated) output from Line, this will produce 3-dimensional cartesian grid. And so on. (currently this can be implemented with ~4 nodes).
7. "Randomize". Given set of vertices, a random seed and range (3 ranges for 3 dimensions), produce the same set with each vertex moved randomly in 3 dimensions. Currently can be implemeted with Random vector + Vector out + (3* Math or Formula) + Vector In + Move.
8. "Iterate". In the ideal world, this would take a set of vertices V and an arbitary transformation F, and produce set of vertices as V + F(V) + F(F(V)) + F(F(F(V))) + ... (N times). In terms of Sverchok, let's begin with affine transformations only — in this case F can be represented with Matrix input slot.
9. Re-implementation of Blender's usual primitive meshes as Generators: IcoSphere, Cone, Torus. By the way, what about Susanne? :) It would be nice to have it, or a "traditional" teapot, or another "mascot" - may be, low-poly 3d model of cricket? :)

**Comment by nortikin** [comment] 2015-01-10 10:24
Put your nodes to beta nodes. in fork or new branch here.

As usual i make new node exactly when it is needed for me in my job, so it is slow-motion, but exact what i need.
If you need duplicate uvconnection node, lets think of implementing shifting ir pattern in existing node, not to make new one. My idea is make less tools, but that working for many cases. flexible.
Noone will stop you if you make other specific node, but it has to be usable nonthe lessthat general node.

**Comment by portnov** [comment] 2015-01-11 06:45
About No.6, "Carthesian product". After thinking a bit i found that it is almost the same as we have in "Matrix Apply Node" with two exceptions:

1. With Matrix Apply, you have to pass recipient vertices through Matrix In node. This is not a big deal, i think. Moreover, if you are using Matrix In, then you can not only translate donor objects, but also rotate and scale them, which is good.
2. Matrix Apply only transforms vertices. This is OK when we have one matrix on input. But if we pass one set of M vertices (from one mesh) and a series of N matrices, then Matrix Apply will produce N series of M vertices each. N*M is obviously bigger than just M. So, who will make edges and faces between all these new vertices!?

So, i'd say we need to add a function to Matrix Apply node to process not only vertices, but also edges and faces. With only one matrix supplied at input, it should just pass edges and faces from input to output as is. With several matrices, it should "copy" all edges and faces for newly created vertices.
How do you like this proposal?

**Comment by yanivg101** [comment] 2015-01-11 07:26
I was trying to make an "Modifier" that will make a mesh to be made of tubes, I'm using the "Pipe Tube Node" to get the tubes but still need the joints.
I duplicate balls on every verices of the input mesh and need to make them as only one object.
I'm using the "Matrix Apply Node" for that and make some nodes to solve the problem above.

see if it help.
https://www.dropbox.com/s/s02pgfq7lzj8urc/Make%20Tubes.json?dl=0

and also if there is a way to get a nice and clean mesh without the need to fix it in 3rd party software.

**Comment by portnov** [comment] 2015-01-11 07:41
yanlvg101, yeah, i managed to duplicate faces also, see
http://home.iportnov.ru/files/www/duplicate1.blend.gz
("Duplicate frames" nodes).
But, why should we use 4 additional nodes instead of just one?

**Comment by yanivg101** [comment] 2015-01-11 08:00
I will check the example.
in my file I want to be able to change the shape (the Ball) so the number of vertices and faces are changeable.
and... It's the first time I'm using Sverchok...

**Comment by portnov** [comment] 2015-01-11 08:08
I updated example file, please check it again if you downloaded it already.
There i use "List length" node to calculate number of vertices in donor mesh. But again, IMHO that's a nasty magic :) that can be avoided by adding one relatively simple feature to Matrix Apply node.

**Comment by portnov** [comment] 2015-01-11 08:11
Or maybe zefii or nortikin will suggest simpler solution...

**Comment by yanivg101** [comment] 2015-01-11 08:17
I can't download it.

**Comment by portnov** [comment] 2015-01-11 08:27
That's strange. Re-uploaded it to Dropbox: https://www.dropbox.com/s/af919x2zw7fxk0z/duplicate1.blend.gz?dl=0

**Comment by yanivg101** [comment] 2015-01-11 08:29
I'm on windows and using 7z, still can't open.

**Comment by portnov** [comment] 2015-01-11 08:40
ah :) it's gzip. Doesn't blender on windows open .blend.gz files? Afaik gzip is built-in. Just try not to unpack it manually, but open it with blender.

**Comment by portnov** [comment] 2015-01-11 08:41
Re-uploaded it just in case: https://www.dropbox.com/s/8f71qv32k4hsfzh/duplicate1.blend?dl=0 try this.

**Comment by zeffii** [comment] 2015-01-11 10:39
@portnov regarding the edges/faces output of _matrix apply_. If I understand what you are saying, this is a valid point. We might want a more convenient way to also get repeated lists of edges and faces, if we want to further process this data before hitting the Viewers. This is one of those scenarios where we would use the same/similar chain of nodes to achieve the copying (List Length -> List Repeat ).

Right now both Viz nodes are designed to _list repeat_ at the last possible moment. For ViewerDraw this means avoiding the extra copies entirely and referencing previous edge/face lists. For the BMesh viewer all expected geometry is generated up front doing `fullList` before doing a `bmesh_from_pydata(verts, edges, faces)`.

As it stands adding sockets to the Matrix Apply node has negative practical implications. One; because those are the kind of changes to sockets that tend to break all existing .blends that use Matrix Apply. Two; because often we can let the Viewer Nodes make up the edges/faces for us.

On occasion I fantasize about a edges+face repeater that takes a length input or a vertices input and figures out the length by its own or a levels slider.

**Comment by portnov** [comment] 2015-01-11 10:49
That's not only repeating, it's also addition (see my example file above as example). In simplest case, let's say we have two vertices 0 and 1, and one edge (0,1). Then I apply MatrixApply with 3 matrices. As a result, i will have 6 vertices 0..5. Correspondingly, i want to have 3 edges: (0,1), (2,3), (4,5). New edges can be calculated by iteratively adding 2 (which is number of initial vertices) to initial edge (0,1).

**Comment by portnov** [comment] 2015-01-11 10:54
If adding new inputs and outputs to existing node is too complex, i'd suggest a new node like "edges/faces repeater". Inputs: vertices; edges; faces; number of repeats. "vertices" input used only to calculate number of vertices. Outputs: edges, faces.
?

**Comment by yanivg101** [comment] 2015-01-11 10:56
All I need is a simple "Join Mesh" node...

**Comment by zeffii** [comment] 2015-01-11 10:57
I think it's more convenient to show images (can be pasted directly) than .blends. So you are looking for functionality that is both `List Length - > List Repeat (edges, faces)-> [Mesh Join](http://nikitron.cc.ua/sverch/html/nodes/modifier_change/mesh_join.html) (offsets)`

**Comment by zeffii** [comment] 2015-01-11 11:03
I agree fully that `Mesh Join` deserves another iteration, to take Verts+Edges+Faces and counts how many sets of Verts, and (repeats + auto offsets) the Indices of the incoming Edges/Faces I prefer Edges and Faces to have separate sockets incase we want to mix polygon meshes that also have areas with only edges.

**Comment by portnov** [comment] 2015-01-11 11:13
That's better a bit...
![duplicate](https://cloud.githubusercontent.com/assets/284644/5695034/b521c6fe-99ac-11e4-99af-74be99027e60.png)

**Comment by portnov** [comment] 2015-01-11 11:18
zeffii, so do you think that Mesh Join node should do repetition of input edges (current work of List Repeater) automatically by the number of input vertex sets?
Talking about separate input, willn't it cause the same probles as new inputs for Apply Matrix node?

**Comment by nortikin** [comment] 2015-01-11 11:24
Now you can modify vertices, use list join nodes for vertices and edges separately and mesh join modifier to join mesh @yanivg101 
Also to pipe tubes with interjoin - use `close` boolean flag. If you have not this, just install new version, update. i will change version for you now.
@portnov 
And about multiplying edges and polygons when changing vertices in range of values. join mesh should have multysocket, that is all

**Comment by zeffii** [comment] 2015-01-11 11:33
![image](https://cloud.githubusercontent.com/assets/619340/5695069/bf83e916-998d-11e4-8189-ee2a82915e06.png)
@portnov this is functionally equivalent to your layout https://www.dropbox.com/s/dba46ep2w541usu/duplicate1_rv.blend?dl=0

**Comment by portnov** [comment] 2015-01-11 11:49
@zeffii , yes, it is, but offten we want to have duplicated objects not as a final result, but as an intermediate. For example, maybe i want to apply Wireframe to duplicated objects, or whatever else. In this case, Mesh Join will be needed.
So. Will someone update Mesh Join node? :)

**Comment by zeffii** [comment] 2015-01-11 12:07
.Free free to draw up the design spec of code it. Suggest you make `SvMeshJoinMK2` instead to avoid breaking old layouts and not get in the way of progress

**Comment by zeffii** [comment] 2015-01-11 12:17
The less atomic a node type is, the more difficult it becomes (in general) to give it a descriptive name  which doesn't hide at least one or two of its strong features

**Comment by zeffii** [comment] 2015-01-11 12:48
Because ViewerDraw has a merged `edg_pol` socket, it isn't possible to send it a mesh that has a mix of edges and faces. It determines if a stream is faces only or edges only and processes accordingly.

My ideal would be:
`svMeshRepeatAndJoin` 

Inputs | options | outputs |
 ---- | ---- | ---
vertices | auto offset  | vertices
edges |   | edges
faces |  | faces

But functionally, for sverchok, this would be just as useful 

Inputs | options | outputs |
 ---- | ---- | ---
vertices | auto offset  | vertices
edg_pol |   | edg_pol

I wouldn't resist, but I can't speak for @nortikin and @ly29 , to letting the node have a matrix socket too.

**Comment by yanivg101** [comment] 2015-01-11 20:06
@zeffii, when I duplicate a lot of Balls, I have a lot of objects. I want only one BEFORE I send it to BMesh and/or join the objects with other.
@portnov, Thanks for the List Repeater node, work great with much less nodes (I still don't know how it's work...)
and @nortikin, I didn't understand what is the different between the new version and the old one.

**Comment by nortikin** [comment] 2015-01-11 20:37
@yanivg101 pipes can close between each other. If you had that version allready, than i dont know what is wrong and why you cannot join pipes?

**Comment by nortikin** [comment] 2015-01-11 20:39
@yanivg101 or you need edges to be from start to end tubed? This is other story, but i can add such mode

**Comment by yanivg101** [comment] 2015-01-11 21:10
I need to make this but it isn't close nor clean mesh:
http://s26.postimg.org/wdnyy360p/Up_Setup.png

**Comment by zeffii** [comment] 2015-01-11 21:19
@yanivg101 You are talking about a few separate things here. 

_Sphere at points._
In that case what you really want is a DupliVert node, I implemented such a node some time ago but it has limitations caused by missing features in Blender API. The limitation is that you can't scale duplicated objects individually, only rotate. See images : https://github.com/nortikin/sverchok/issues/470

_Edges with Thickness_
I gather that this is the end result you are seeking anyway, like pipes with filleted corners. Sverchok currently doesn't offer this, executing code that would allow this would be quite slow for anything other than simple low quantity geometry.

I've been meaning for a while to implement a Curves node, which sort of like the BMesh node outputs Curve objects to the scene when given edges+vertices. That in combination with the DupliVert Object node would allow at least reasonably passable renderable geometry, but topologically of course it would still just be a faux solution.

**Comment by yanivg101** [comment] 2015-01-11 23:33
I wish there is a way to duplicate thing on the edge.
I need it for other reasons like to make something like that:
http://www.creativeapplications.net/openframeworks/kinematics-system-for-3d-printing-complex-foldable-forms
and for duplication of Metaball (or capsules). that will fix the issue for good.

**Comment by zeffii** [comment] 2015-01-12 00:15
Some time ago I also experimented with a MetaBall node, metaballs are remarkably slow
You might be interested in the Adaptive Polygons node. (We should add more elaborate content to the documentation for that node.. it doesn't do it justice)

**Comment by portnov** [comment] 2015-01-12 04:36
@yanivg101 
about "duplicate things on the edge". Please look at https://github.com/portnov/sverchok/issues/6 . Isn't it what you were looking for?

**Comment by portnov** [comment] 2015-01-12 06:46
Just note about current state:

1. done.
2. Not decided. Will it be OK to add new output to List Match node?
3. @nortikin will it be better to add such function to UV Connect node? or create a new node?
4. Done.
5. done.
6. Under discussion.
7. done.
8. done.
9. I saw @zeffii 's branch with ico-sphere node. It would be nice to have it in master some day. With other - not started yet.

**Comment by zeffii** [comment] 2015-01-12 08:37
@portnov I'm leaning towards making a generic shell for bmesh.primitives, like a script node but instead purely for these primitives, all in one node and pickable from dropdown. That way one could keep the output connected and switch through primitives, the inputs I guess would stay connected only if the previous and current primitive (between switches) have params that could somehow be considered congruent. Like Cube size might be translatable to Sphere radius ( or /2) ,etc.

Regarding the mesh primitive a low poly cricket instead of suzanne, is something we discussed briefly a while back. I'd quite like to model it, but haven't found the right reference images yet.

**Comment by zeffii** [comment] 2015-01-12 08:41
@yanivg101 
> I wish there is a way to duplicate thing on the edge.

Isn't this what Adaptive Edges node already does? Duplicate a donor mesh onto each edge of the recipient. Likewise Adaptive Polygons duplicates a donor mesh onto each Polygon of a recipient.

**Comment by portnov** [comment] 2015-01-12 08:44
@zeffii , Adaptive Edges places only one copy of donor mesh at each edge, doesn't it? Also, in my experiments i was not able to make it properly align donor objects — it seems to decide how to rotate objects on its own, and that decision looks very odd to me.

**Comment by zeffii** [comment] 2015-01-12 08:47
> the base mesh must be composed by quadrilateral faces. Triangles and polygons can give some weird results;

it is from : https://sketchesofcode.wordpress.com/2013/11/11/

I think we'd welcome a new implementation, well I would :)

**Comment by zeffii** [comment] 2015-01-12 09:06
@portnov 
>  Adaptive Edges places only one copy of donor mesh at each edge, doesn't it?
yep:

![image](https://cloud.githubusercontent.com/assets/619340/5700741/b73276e6-9a42-11e4-88ff-838a887863b4.png)

**Comment by zeffii** [comment] 2015-01-12 09:20
Adaptive Polygon in its current implementation is weak. 
![image](https://cloud.githubusercontent.com/assets/619340/5700857/41bf1ec6-9a44-11e4-9ad4-684f5bb39688.png)
After seeing the _Nervous System_ 3d printed dress I also think we deserve a better implementation of this Donor / Recipient concept, until then I was ambivalent.

**Comment by zeffii** [comment] 2015-01-12 09:27
@portnov 
From what I gather their software is written in JS which can execute around 10 times faster than Python (depending on factors).are you familiar with numpy?

**Comment by portnov** [comment] 2015-01-12 10:28
more ore less.

**Comment by portnov** [comment] 2015-01-12 11:52
@zeffii , about analog of Adaptive Edges module: please look at portnov#6. I started an implementation, but not finished it yet. Maybe you can add or clarify some requirements. I'll push what i have now today or tomorrow to my repo.
About Adaptive Polygon/DupliFaces — these imho have much more complex mathematics inside, since they do some nonlinear transformations of donor mesh. I'm not sure if i can do better implementation than existing ones.

**Comment by zeffii** [comment] 2015-01-12 12:11
For DupliFace/Objects (loosly Adapative Polygons) I imagine that the Object-Donor should perhaps itself be a parametric object which can adapt parts to prevent stretching of components (like hinges), and react to the shape it is donated to. Also some suggestion should exist in advance that the donation shape will be useful to the recipient polygon.

regarding portnov#6 I think the description makes sense, but where is the code?

**Comment by portnov** [comment] 2015-01-12 12:20
will push it today or tomorrow :)

**Comment by portnov** [comment] 2015-01-12 20:10
@zeffii, you can take a look at progress by my comments in portnov#6 and in "objects_along_edge" branch in my repo.

**Comment by zeffii** [comment] 2015-01-12 20:47
Quite nice to read code like that. I do have one style recommendation:

Instead of
```python
count_ = IntProperty(name='Count', description='Number of copies',
                        default=3, min=1,
                        update=updateNode)

    scale_all = BoolProperty(name="Scale all axes", description="Scale donor objects along all axes or only along orientation axis",
                             default=False,
                             update=updateNode)

    apply_matrices = BoolProperty(name="Apply matrices", description="Apply generated matrices to generated objects internally",
                             default=True,
                             update=updateNode)
```
this.
```python
count_ = IntProperty(name='Count',
    description='Number of copies',
    default=3, min=1,
    update=updateNode)

scale_all = BoolProperty(name="Scale all axes",
    description="Scale donor objects along all axes or only along orientation axis",
    default=False,
    update=updateNode)

apply_matrices = BoolProperty(name="Apply matrices",
    description="Apply generated matrices to generated objects internally",
    default=True,
    update=updateNode)
```

**Comment by nortikin** [comment] 2015-01-12 22:18
nice idea

**Comment by portnov** [comment] 2015-01-13 04:19
Ok, i will do some testing, then code cleanup and formatting, and then will create a pull request.

**Comment by ly29** [comment] 2015-01-13 07:32
@portnov @zeffii 
Yeah, adaptive edges needs a new mk2 implementation with the additions you ask for. It would be in beta if we had had at the time.

**Comment by portnov** [comment] 2015-01-13 07:47
@ly29, please take a look at requirements in portnov#6; maybe I missed something?

**Comment by nortikin** [comment] 2015-01-15 20:10
will post on vk.com sverchok group

**Comment by portnov** [comment] 2015-01-18 17:12
About No.6, I started with Mk2 of Matrix Apply for now. See also portnov#9.

**Closed** 2015-05-09 19:21 UTC
