### ISSUE TITLE
Sverchok does not work in latest builder.blender.org 2.79 Blender builds

### ISSUE THREAD

**Issue by retsyo** [nortikin/sverchok#1819] opened 2017-10-18 03:18 UTC
sverchok is just cloned from here 
it works fine with official Blender 2.79  on my win 7 64bits

but when I try to enable it in `Windows 64 bit  Official  blender-2.79-1cb884b-win64.zip 118M Wed Oct 18 02:54:35 2017 ` from https://builder.blender.org/download/, Blender crashes when I try to toggle sverchok everytime

**Comment by zeffii** [comment] 2017-10-18 07:44
thanks for the report. We try to keep up with recent builder.blender.org builds every week or two to ensure minimum disruption. Nothing in the release logs over this period made me want to test a builderbot built, but ... i suppose now i'll have to :)   fingers crossed for good error messages.

**Comment by zeffii** [comment] 2017-10-18 08:13
i'm loading the same zip on windows 10 64bit `Wed Oct 18 02:54:35 2017` , and Sverchok works OK.

mind you all version of 2.79 will load the same startup file stored somewhere in 
```text
AppData/Roaming/Blender Foundation/Blender/2.79/config
```
so if I have Sverchok enabled by default in the official builds, and then try a nightly builderbot build then i'm not enabling Sverchok by hand - I have yet to try starting `2.79 1cb884b-win64.zip` without sverchok enabled in the startup.  It could be the add-on enabling code that has changed.

**Comment by zeffii** [comment] 2017-10-18 08:23
I can also enable it from a clean startup file. This puzzles me then. As I can not reproduce the crash I can't be certain what's going on. Are you using a local Python (3.5? ) blender is now using/assuming 3.6.

**Comment by zeffii** [comment] 2017-10-18 14:39
i can't reproduce, if it's a general problem we'll get more reports.. 

it may be worth starting blender with more verbose debug information, to hint what's up
```text
blender.exe --debug-all
.\blender.exe --debug-all
```

**Comment by retsyo** [comment] 2017-10-19 09:04
please check out.txt on
https://github.com/retsyo/sverchok_bug

My processing is
```bash
D:\tmp\blender-2.79.0-git.c64e515-windows64>set path=
D:\tmp\blender-2.79.0-git.c64e515-windows64>set pythonpath=
D:\tmp\blender-2.79.0-git.c64e515-windows64>.\blender.exe  --debug-all >out.txt
```

**Comment by zeffii** [comment] 2017-10-19 13:02
It might be worth renaming the sverchok-master to just sverchok. The dump doesn't suggest. Any immediate issue.

**Comment by zeffii** [comment] 2017-10-19 13:47
If you search that debug file for the words "found bundeled python" it seems to suggest it uses a different blender's python dir...a different hash.

**Comment by zeffii** [comment] 2017-10-19 16:19
i see you are using the newer `c64e515` now.  I am none the wiser. sorry.

**Comment by zeffii** [comment] 2017-10-19 21:16
(it works for me in that build too.. )

**Comment by zeffii** [comment] 2017-10-20 09:10
what does this return when you run it in the console/text editor of the nightly build?
```python
import os
os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok'))
```

**Comment by retsyo** [comment] 2017-10-20 10:00
```bash
E:\greensoft\3d\blender\blender-2.79.0-git.1cb884b-windows64\2.79\datafiles\sverchok
```

**Comment by retsyo** [comment] 2017-10-20 10:26
aha, I found that sverchok crashes blender-2.79-cb957fd-win64.zip, but works well with blender-2.79-cb957fd-win64-vc14.zip
but it is so strange. does sverchok depends on any binary modules?

**Comment by zeffii** [comment] 2017-10-20 10:29
Parts of Python and numpy are compiled, wouldn't suprise me if the compiled stuff doesn't work on all systems. but it's still a little weird :)

**Comment by zeffii** [comment] 2017-10-20 10:29
try `import numpy as np` on your crashing binary/blender and see what that returns

**Comment by retsyo** [comment] 2017-10-20 10:34
```python
import numpy as np 
a = np.arange(10)
print(a)
```
works without problem on both blender-2.79-cb957fd-win64.zip(which crashes when I try to eanble sverchok) and blender-2.79-cb957fd-win64-vc14.zip( which can work with sverchok)

**Comment by zeffii** [comment] 2017-10-20 10:46
the only other module we import is that is not standard is the `requests` module, this is only invoked when the user pressed "check updates" or load/upping gists, but it will still be interpreted during the sverchok initialization.

still no insight into the cause, I can't really offer solutions with blindfolds on :/

**Comment by zeffii** [comment] 2017-10-20 10:48
i am tempted to add more granularity to our initialization process, but whether that would track this kind of crash is far from certain.

**Comment by zeffii** [comment] 2017-10-21 07:43
if you want to help us figure it out, i will make a debug version of sverchok and gradually add more reporting events. Else i'll close this issue as a Blender compilation related bug (i'm still interested, and it bothers me )

**Comment by zeffii** [comment] 2017-10-21 08:40
clone this: https://github.com/nortikin/sverchok/tree/sv_debugmode
in blender console `bpy.app.debug = True` before trying to enable Sverchok, then i'd like to see the printouts

**Comment by retsyo** [comment] 2017-10-21 13:44
```bash
E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64>blender.exe
found bundled python: E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64\2.79\python
ED_undo_push: Run Script
<sverchok> importing analyzer
<sverchok> importing bmesh_nodes
<sverchok> importing generator
<sverchok> importing generators_extended
<sverchok> importing layout
<sverchok> importing list_main
<sverchok> importing list_masks
<sverchok> importing list_mutators
<sverchok> importing list_struct
<sverchok> importing logic
<sverchok> importing matrix
<sverchok> importing modifier_change
<sverchok> importing modifier_make
<sverchok> importing network
<sverchok> importing number
<sverchok> importing object_nodes
<sverchok> importing scene
<sverchok> importing script
<sverchok> importing text
<sverchok> importing transforms
<sverchok> importing vector
<sverchok> importing viz
<sverchok> registering node sverchok-sv_debugmode.settings
<sverchok> registering node sverchok.menu

** Sverchok loaded with 247 nodes **
<sverchok> registering node sverchok.node_tree
<sverchok> registering node sverchok.sockets
<sverchok> registering node sverchok.core.handlers
<sverchok> registering node sverchok.core.update_system
<sverchok> registering node sverchok.core.monad
<sverchok> registering node sverchok.utils.text_editor_submenu
<sverchok> registering node sverchok.utils.text_editor_plugins
added keyboard items to Text Editor.
<sverchok> registering node sverchok.utils.sv_panels_tools
<sverchok> registering node sverchok.utils.sv_IO_panel_tools
<sverchok> registering node sverchok.utils.sv_load_zipped_blend
<sverchok> registering node sverchok.utils.monad
<sverchok> registering node sverchok.utils.sv_macro_utils
<sverchok> registering node sverchok.utils.sv_extra_search
<sverchok> registering node sverchok.utils.sv_3dview_tools
<sverchok> registering node sverchok.utils.debug_script
<sverchok> registering node sverchok.utils.sv_update_utils
<sverchok> registering node sverchok.ui.color_def
<sverchok> registering node sverchok.ui.sv_IO_panel
<sverchok> registering node sverchok.ui.sv_templates_menu
<sverchok> registering node sverchok.ui.sv_panels
<sverchok> registering node sverchok.ui.nodeview_space_menu
<sverchok> registering node sverchok.ui.nodeview_keymaps
<sverchok> registering node sverchok.ui.monad
<sverchok> registering node sverchok.ui.sv_icons
<sverchok> registering node sverchok.ui.development

Blender crashes here

E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64>
```

**Comment by zeffii** [comment] 2017-10-21 14:13
interesting. it appears at this point most of sverchok is loaded.. but some things still happen in `__init__`

can you do that again please? i've pushed a few more tests

**Comment by retsyo** [comment] 2017-10-21 14:20
```bash
E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64>set path=

E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64>set pythonpath=

E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64>blender
found bundled python: E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows
64\2.79\python
Info: Total files 0 | Changed 0 | Failed 0
ED_undo_push: Run Script
<sverchok> importing analyzer
<sverchok> importing bmesh_nodes
<sverchok> importing generator
<sverchok> importing generators_extended
<sverchok> importing layout
<sverchok> importing list_main
<sverchok> importing list_masks
<sverchok> importing list_mutators
<sverchok> importing list_struct
<sverchok> importing logic
<sverchok> importing matrix
<sverchok> importing modifier_change
<sverchok> importing modifier_make
<sverchok> importing network
<sverchok> importing number
<sverchok> importing object_nodes
<sverchok> importing scene
<sverchok> importing script
<sverchok> importing text
<sverchok> importing transforms
<sverchok> importing vector
<sverchok> importing viz
<sverchok> completed make_node_list
<sverchok> registering node sverchok-sv_debugmode.settings
<sverchok> registering node sverchok.menu

** Sverchok loaded with 247 nodes **
<sverchok> registering node sverchok.node_tree
<sverchok> registering node sverchok.sockets
<sverchok> registering node sverchok.core.handlers
<sverchok> registering node sverchok.core.update_system
<sverchok> registering node sverchok.core.monad
<sverchok> registering node sverchok.utils.text_editor_submenu
<sverchok> registering node sverchok.utils.text_editor_plugins
added keyboard items to Text Editor.
<sverchok> registering node sverchok.utils.sv_panels_tools
<sverchok> registering node sverchok.utils.sv_IO_panel_tools
<sverchok> registering node sverchok.utils.sv_load_zipped_blend
<sverchok> registering node sverchok.utils.monad
<sverchok> registering node sverchok.utils.sv_macro_utils
<sverchok> registering node sverchok.utils.sv_extra_search
<sverchok> registering node sverchok.utils.sv_3dview_tools
<sverchok> registering node sverchok.utils.debug_script
<sverchok> registering node sverchok.utils.sv_update_utils
<sverchok> registering node sverchok.ui.color_def
<sverchok> registering node sverchok.ui.sv_IO_panel
<sverchok> registering node sverchok.ui.sv_templates_menu
<sverchok> registering node sverchok.ui.sv_panels
<sverchok> registering node sverchok.ui.nodeview_space_menu
<sverchok> registering node sverchok.ui.nodeview_keymaps
<sverchok> registering node sverchok.ui.monad
<sverchok> registering node sverchok.ui.sv_icons
<sverchok> registering node sverchok.ui.development
branch check 1 - start

crashes here !!! 

E:\greensoft\3d\blender\blender-2.79.0-git.cb957fd-windows64>
```

**Comment by zeffii** [comment] 2017-10-21 14:24
try again? :) i've commented out some code

**Comment by zeffii** [comment] 2017-10-21 14:29
if this localizes the problem i'm tempted to leave that commented code out, seen as the second procedure to get the branch should always get it if there's a `.git` folder locally.

**Comment by zeffii** [comment] 2017-10-21 14:31
whereas this bit  :  
```python
      res = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                           stdout=subprocess.PIPE,
                           cwd=os.path.dirname(sverchok.__file__),
                           timeout=2)
```
also doesn't trigger the except clause of the try/except ( which bugs the living crap out of me )

**Comment by retsyo** [comment] 2017-10-21 14:34
congratulations! this time sverchok can be enabled

but for a simple sverchok node link `number - int` linking with `debug print`, when I change the int value the output does not change at the same time on both `blender-2.79.0-git.cb957fd-windows64` (which has this sverchok-debugmode) and `blender-2.79.0-git.cb957fd-windows64-vc14` (which has sverchok)
is it right?

```bash
Read blend: R:\untitled.blend
ED_undo_push: Run Script
<sverchok> importing analyzer
<sverchok> importing bmesh_nodes
<sverchok> importing generator
<sverchok> importing generators_extended
<sverchok> importing layout
<sverchok> importing list_main
<sverchok> importing list_masks
<sverchok> importing list_mutators
<sverchok> importing list_struct
<sverchok> importing logic
<sverchok> importing matrix
<sverchok> importing modifier_change
<sverchok> importing modifier_make
<sverchok> importing network
<sverchok> importing number
<sverchok> importing object_nodes
<sverchok> importing scene
<sverchok> importing script
<sverchok> importing text
<sverchok> importing transforms
<sverchok> importing vector
<sverchok> importing viz
<sverchok> completed make_node_list
<sverchok> registering node sverchok-sv_debugmode.settings
<sverchok> registering node sverchok.menu

** Sverchok loaded with 247 nodes **
<sverchok> registering node sverchok.node_tree
<sverchok> registering node sverchok.sockets
<sverchok> registering node sverchok.core.handlers
<sverchok> registering node sverchok.core.update_system
<sverchok> registering node sverchok.core.monad
<sverchok> registering node sverchok.utils.text_editor_submenu
<sverchok> registering node sverchok.utils.text_editor_plugins
added keyboard items to Text Editor.
<sverchok> registering node sverchok.utils.sv_panels_tools
<sverchok> registering node sverchok.utils.sv_IO_panel_tools
<sverchok> registering node sverchok.utils.sv_load_zipped_blend
<sverchok> registering node sverchok.utils.monad
<sverchok> registering node sverchok.utils.sv_macro_utils
<sverchok> registering node sverchok.utils.sv_extra_search
<sverchok> registering node sverchok.utils.sv_3dview_tools
<sverchok> registering node sverchok.utils.debug_script
<sverchok> registering node sverchok.utils.sv_update_utils
<sverchok> registering node sverchok.ui.color_def
<sverchok> registering node sverchok.ui.sv_IO_panel
<sverchok> registering node sverchok.ui.sv_templates_menu
<sverchok> registering node sverchok.ui.sv_panels
<sverchok> registering node sverchok.ui.nodeview_space_menu
<sverchok> registering node sverchok.ui.nodeview_keymaps
<sverchok> registering node sverchok.ui.monad
<sverchok> registering node sverchok.ui.sv_icons
<sverchok> registering node sverchok.ui.development
branch check 2 - start
branch check 2 - done
<sverchok> registering node sverchok.nodes.analyzer.area
<sverchok> registering node sverchok.nodes.analyzer.bbox
<sverchok> registering node sverchok.nodes.analyzer.bvh_overlap_polys
<sverchok> registering node sverchok.nodes.analyzer.distance_pp
<sverchok> registering node sverchok.nodes.analyzer.edge_angles
<sverchok> registering node sverchok.nodes.analyzer.image_components
<sverchok> registering node sverchok.nodes.analyzer.kd_tree_edges_mk2
<sverchok> registering node sverchok.nodes.analyzer.kd_tree_MK2
<sverchok> registering node sverchok.nodes.analyzer.mesh_filter
<sverchok> registering node sverchok.nodes.analyzer.mesh_select
<sverchok> registering node sverchok.nodes.analyzer.normals
<sverchok> registering node sverchok.nodes.analyzer.points_inside_mesh
<sverchok> registering node sverchok.nodes.analyzer.polygons_centers
<sverchok> registering node sverchok.nodes.analyzer.polygons_centers_mk3
<sverchok> registering node sverchok.nodes.analyzer.proportional
<sverchok> registering node sverchok.nodes.analyzer.raycaster_lite
<sverchok> registering node sverchok.nodes.analyzer.select_similar
<sverchok> registering node sverchok.nodes.analyzer.volume
<sverchok> registering node sverchok.nodes.bmesh_nodes.bmesh_in
<sverchok> registering node sverchok.nodes.bmesh_nodes.bmesh_out
<sverchok> registering node sverchok.nodes.bmesh_nodes.bmesh_props
<sverchok> registering node sverchok.nodes.bmesh_nodes.bmesh_to_element
<sverchok> registering node sverchok.nodes.generator.basic_3pt_arc
<sverchok> registering node sverchok.nodes.generator.basic_spline
<sverchok> registering node sverchok.nodes.generator.box
<sverchok> registering node sverchok.nodes.generator.bricks
<sverchok> registering node sverchok.nodes.generator.circle
<sverchok> registering node sverchok.nodes.generator.cylinder
<sverchok> registering node sverchok.nodes.generator.formula_shape
<sverchok> registering node sverchok.nodes.generator.icosphere
<sverchok> registering node sverchok.nodes.generator.image
<sverchok> registering node sverchok.nodes.generator.line_mk2
<sverchok> registering node sverchok.nodes.generator.ngon
<sverchok> registering node sverchok.nodes.generator.plane_mk2
<sverchok> registering node sverchok.nodes.generator.random_vector_mk2
<sverchok> registering node sverchok.nodes.generator.script1_lite
<sverchok> registering node sverchok.nodes.generator.sphere
<sverchok> registering node sverchok.nodes.generator.torus
<sverchok> registering node sverchok.nodes.generator.torusKnot
<sverchok> registering node sverchok.nodes.generators_extended.box_rounded
<sverchok> registering node sverchok.nodes.generators_extended.edge_split
<sverchok> registering node sverchok.nodes.generators_extended.generative_art
<sverchok> registering node sverchok.nodes.generators_extended.hexa_grid
<sverchok> registering node sverchok.nodes.generators_extended.hilbert
<sverchok> registering node sverchok.nodes.generators_extended.hilbert3d
<sverchok> registering node sverchok.nodes.generators_extended.hilbert_image
<sverchok> registering node sverchok.nodes.generators_extended.mesh_eval
<sverchok> registering node sverchok.nodes.generators_extended.profile_mk2
<sverchok> registering node sverchok.nodes.generators_extended.ring
<sverchok> registering node sverchok.nodes.generators_extended.script
<sverchok> registering node sverchok.nodes.generators_extended.script3
<sverchok> registering node sverchok.nodes.generators_extended.script_mk2
<sverchok> registering node sverchok.nodes.layout.converter
<sverchok> registering node sverchok.nodes.layout.wifi_in
<sverchok> registering node sverchok.nodes.layout.wifi_out
<sverchok> registering node sverchok.nodes.list_main.decompose
<sverchok> registering node sverchok.nodes.list_main.func
<sverchok> registering node sverchok.nodes.list_main.join
<sverchok> registering node sverchok.nodes.list_main.length
<sverchok> registering node sverchok.nodes.list_main.levels
<sverchok> registering node sverchok.nodes.list_main.match
<sverchok> registering node sverchok.nodes.list_main.sum_mk2
<sverchok> registering node sverchok.nodes.list_main.zip
<sverchok> registering node sverchok.nodes.list_masks.mask
<sverchok> registering node sverchok.nodes.list_masks.mask_convert
<sverchok> registering node sverchok.nodes.list_masks.mask_join
<sverchok> registering node sverchok.nodes.list_mutators.modifier
<sverchok> registering node sverchok.nodes.list_struct.flip
<sverchok> registering node sverchok.nodes.list_struct.index_to_mask
<sverchok> registering node sverchok.nodes.list_struct.item
<sverchok> registering node sverchok.nodes.list_struct.numpy_array
<sverchok> registering node sverchok.nodes.list_struct.repeater
<sverchok> registering node sverchok.nodes.list_struct.reverse
<sverchok> registering node sverchok.nodes.list_struct.shift_mk2
<sverchok> registering node sverchok.nodes.list_struct.shuffle
<sverchok> registering node sverchok.nodes.list_struct.slice
<sverchok> registering node sverchok.nodes.list_struct.slice_lite
<sverchok> registering node sverchok.nodes.list_struct.sort_mk2
<sverchok> registering node sverchok.nodes.list_struct.split
<sverchok> registering node sverchok.nodes.list_struct.start_end
<sverchok> registering node sverchok.nodes.logic.logic_node
<sverchok> registering node sverchok.nodes.logic.neuro_elman
<sverchok> registering node sverchok.nodes.logic.switch
<sverchok> registering node sverchok.nodes.matrix.apply_and_join
<sverchok> registering node sverchok.nodes.matrix.deform
<sverchok> registering node sverchok.nodes.matrix.euler
<sverchok> registering node sverchok.nodes.matrix.input
<sverchok> registering node sverchok.nodes.matrix.interpolation
<sverchok> registering node sverchok.nodes.matrix.matrix_in_mk2
<sverchok> registering node sverchok.nodes.matrix.matrix_normal
<sverchok> registering node sverchok.nodes.matrix.matrix_out
<sverchok> registering node sverchok.nodes.matrix.matrix_track_to
<sverchok> registering node sverchok.nodes.matrix.shear
<sverchok> registering node sverchok.nodes.modifier_change.bevel
<sverchok> registering node sverchok.nodes.modifier_change.delete_loose
<sverchok> registering node sverchok.nodes.modifier_change.edges_intersect_mk2
<sverchok> registering node sverchok.nodes.modifier_change.extrude_edges
<sverchok> registering node sverchok.nodes.modifier_change.extrude_multi_alt
<sverchok> registering node sverchok.nodes.modifier_change.extrude_region
<sverchok> registering node sverchok.nodes.modifier_change.extrude_separate
<sverchok> registering node sverchok.nodes.modifier_change.flip_normals
<sverchok> registering node sverchok.nodes.modifier_change.holes_fill
<sverchok> registering node sverchok.nodes.modifier_change.iterate
<sverchok> registering node sverchok.nodes.modifier_change.limited_dissolve
<sverchok> registering node sverchok.nodes.modifier_change.mesh_join
<sverchok> registering node sverchok.nodes.modifier_change.mesh_separate
<sverchok> registering node sverchok.nodes.modifier_change.mesh_separate_mk2
<sverchok> registering node sverchok.nodes.modifier_change.objects_along_edge
<sverchok> registering node sverchok.nodes.modifier_change.offset
<sverchok> registering node sverchok.nodes.modifier_change.polygons_boom
<sverchok> registering node sverchok.nodes.modifier_change.polygons_to_edges
<sverchok> registering node sverchok.nodes.modifier_change.randomize
<sverchok> registering node sverchok.nodes.modifier_change.recalc_normals
<sverchok> registering node sverchok.nodes.modifier_change.remove_doubles
<sverchok> registering node sverchok.nodes.modifier_change.smooth
<sverchok> registering node sverchok.nodes.modifier_change.subdivide
<sverchok> registering node sverchok.nodes.modifier_change.transform_select
<sverchok> registering node sverchok.nodes.modifier_change.triangulate
<sverchok> registering node sverchok.nodes.modifier_change.triangulate_heavy
<sverchok> registering node sverchok.nodes.modifier_change.vertices_mask
<sverchok> registering node sverchok.nodes.modifier_make.bisect
<sverchok> registering node sverchok.nodes.modifier_make.convex_hull
<sverchok> registering node sverchok.nodes.modifier_make.convex_hull_mk2
<sverchok> registering node sverchok.nodes.modifier_make.cross_section
<sverchok> registering node sverchok.nodes.modifier_make.csg_booleanMK2
<sverchok> registering node sverchok.nodes.modifier_make.edges_adaptative
<sverchok> registering node sverchok.nodes.modifier_make.inset_special
<sverchok> registering node sverchok.nodes.modifier_make.join_tris
<sverchok> registering node sverchok.nodes.modifier_make.lathe
<sverchok> registering node sverchok.nodes.modifier_make.matrix_tube
<sverchok> registering node sverchok.nodes.modifier_make.pipe_tubes
<sverchok> registering node sverchok.nodes.modifier_make.polygons_adaptative
<sverchok> registering node sverchok.nodes.modifier_make.solidify
<sverchok> registering node sverchok.nodes.modifier_make.uv_connect
<sverchok> registering node sverchok.nodes.modifier_make.voronoi_2d
<sverchok> registering node sverchok.nodes.modifier_make.wafel
<sverchok> registering node sverchok.nodes.modifier_make.wireframe
<sverchok> registering node sverchok.nodes.network.udp_client
<sverchok> registering node sverchok.nodes.number.easing
<sverchok> registering node sverchok.nodes.number.exponential
<sverchok> registering node sverchok.nodes.number.fibonacci
<sverchok> registering node sverchok.nodes.number.float
<sverchok> registering node sverchok.nodes.number.float_to_int
<sverchok> registering node sverchok.nodes.number.formula2
<sverchok> registering node sverchok.nodes.number.integer
<sverchok> registering node sverchok.nodes.number.list_input
<sverchok> registering node sverchok.nodes.number.mix_numbers
<sverchok> registering node sverchok.nodes.number.numbers
<sverchok> registering node sverchok.nodes.number.random
<sverchok> registering node sverchok.nodes.number.random_num_gen
<sverchok> registering node sverchok.nodes.number.range_float
<sverchok> registering node sverchok.nodes.number.range_int
<sverchok> registering node sverchok.nodes.number.range_map
<sverchok> registering node sverchok.nodes.number.scalar
<sverchok> registering node sverchok.nodes.number.scalar_mk2
<sverchok> registering node sverchok.nodes.object_nodes.closest_point_on_mesh2
<sverchok> registering node sverchok.nodes.object_nodes.filter_blenddata
<sverchok> registering node sverchok.nodes.object_nodes.getsetprop
<sverchok> registering node sverchok.nodes.object_nodes.get_asset_properties
<sverchok> registering node sverchok.nodes.object_nodes.object_raycast2
<sverchok> registering node sverchok.nodes.object_nodes.scene_raycast2
<sverchok> registering node sverchok.nodes.object_nodes.sculpt_mask
<sverchok> registering node sverchok.nodes.object_nodes.set_blenddata2
<sverchok> registering node sverchok.nodes.object_nodes.sort_blenddata
<sverchok> registering node sverchok.nodes.object_nodes.vertex_colors_mk2
<sverchok> registering node sverchok.nodes.object_nodes.weightsmk2
<sverchok> registering node sverchok.nodes.scene.3dview_props
<sverchok> registering node sverchok.nodes.scene.blenddata_to_svdata2
<sverchok> registering node sverchok.nodes.scene.BMOperatorsMK2
<sverchok> registering node sverchok.nodes.scene.cache
<sverchok> registering node sverchok.nodes.scene.dupli_instances_mk4
<sverchok> registering node sverchok.nodes.scene.frame_info_mk2
<sverchok> registering node sverchok.nodes.scene.group
<sverchok> registering node sverchok.nodes.scene.instancer
<sverchok> registering node sverchok.nodes.scene.monad
<sverchok> registering node sverchok.nodes.scene.node_remote
<sverchok> registering node sverchok.nodes.scene.objects_in_lite
<sverchok> registering node sverchok.nodes.scene.objects_mk3
<sverchok> registering node sverchok.nodes.scene.obj_edit
<sverchok> registering node sverchok.nodes.scene.obj_remote_mk2
<sverchok> registering node sverchok.nodes.scene.particles
<sverchok> registering node sverchok.nodes.scene.particles_MK2
<sverchok> registering node sverchok.nodes.scene.text
<sverchok> registering node sverchok.nodes.scene.uv_texture
<sverchok> registering node sverchok.nodes.script.multi_exec
<sverchok> registering node sverchok.nodes.text.debug_print
<sverchok> registering node sverchok.nodes.text.gtext
<sverchok> registering node sverchok.nodes.text.note
<sverchok> registering node sverchok.nodes.text.stethoscope_mk2
<sverchok> registering node sverchok.nodes.text.viewer_text_mk2
<sverchok> registering node sverchok.nodes.transforms.apply
<sverchok> registering node sverchok.nodes.transforms.deform
<sverchok> registering node sverchok.nodes.transforms.mirror
<sverchok> registering node sverchok.nodes.transforms.move
<sverchok> registering node sverchok.nodes.transforms.rotation
<sverchok> registering node sverchok.nodes.transforms.scale
<sverchok> registering node sverchok.nodes.vector.attractor
<sverchok> registering node sverchok.nodes.vector.axis_input_mk2
<sverchok> registering node sverchok.nodes.vector.color_in
<sverchok> registering node sverchok.nodes.vector.color_out
<sverchok> registering node sverchok.nodes.vector.drop
<sverchok> registering node sverchok.nodes.vector.fractal
<sverchok> registering node sverchok.nodes.vector.homogenous_vector_field
<sverchok> registering node sverchok.nodes.vector.interpolation
<sverchok> registering node sverchok.nodes.vector.interpolation_mk2
<sverchok> registering node sverchok.nodes.vector.interpolation_mk3
<sverchok> registering node sverchok.nodes.vector.interpolation_stripes
<sverchok> registering node sverchok.nodes.vector.lerp
<sverchok> registering node sverchok.nodes.vector.line_evaluate
<sverchok> registering node sverchok.nodes.vector.math_mk2
<sverchok> registering node sverchok.nodes.vector.noise
<sverchok> registering node sverchok.nodes.vector.noise_mk2
<sverchok> registering node sverchok.nodes.vector.normal
<sverchok> registering node sverchok.nodes.vector.turbulence
<sverchok> registering node sverchok.nodes.vector.variable_lacunarity
<sverchok> registering node sverchok.nodes.vector.vector_in
<sverchok> registering node sverchok.nodes.vector.vector_out
<sverchok> registering node sverchok.nodes.vector.vector_polar_in
<sverchok> registering node sverchok.nodes.vector.vector_polar_out
<sverchok> registering node sverchok.nodes.vector.vector_rewire
<sverchok> registering node sverchok.nodes.vector.vertices_delete_doubles
<sverchok> registering node sverchok.nodes.vector.vertices_sort
<sverchok> registering node sverchok.nodes.viz.empty_out
<sverchok> registering node sverchok.nodes.viz.texture_viewer
<sverchok> registering node sverchok.nodes.viz.texture_viewer_lite
<sverchok> registering node sverchok.nodes.viz.viewer_bmesh_mk2
<sverchok> registering node sverchok.nodes.viz.viewer_curves
<sverchok> registering node sverchok.nodes.viz.viewer_curves_2d
<sverchok> registering node sverchok.nodes.viz.viewer_gp
<sverchok> registering node sverchok.nodes.viz.viewer_indices
<sverchok> registering node sverchok.nodes.viz.viewer_matrix
<sverchok> registering node sverchok.nodes.viz.viewer_mk2
<sverchok> registering node sverchok.nodes.viz.viewer_polyline_mk1
<sverchok> registering node sverchok.nodes.viz.viewer_skin_mk1
<sverchok> registering node sverchok.nodes.viz.viewer_typography
** version:  (0, 5, 9, 6)  **
** Have a nice day with sverchok  **

 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.
```

**Comment by zeffii** [comment] 2017-10-21 14:41
Excellent. I'll work in a fix into master.

As for your second question, start a new issue + elaborate. i don't quite understand.

**Closed by zeffii** 2017-10-21 14:41 UTC
Labels: unconfirmed

**Comment by zeffii** [comment] 2017-10-21 14:48
but no the `A Number ( Int ) -->  Debug Print`  should print updated values instantly.  It's quite possible that already the update system of 2.79x is being adjusted in anticipation for the 2.8 series.

**Comment by zeffii** [comment] 2017-10-21 14:50
but it works here in `blender-2.79.0-git.c64e515-windows64`

**Comment by zeffii** [comment] 2017-10-21 14:55
i've pushed https://github.com/nortikin/sverchok/commit/47eadecf957272571b62b0496d559be487ee9888

**Comment by retsyo** [comment] 2017-10-21 15:03
sorry, I misunderstood the `Debug Print`. it works ok. 

I am wrong to think that it prints the results on `Debug Print` node

**Comment by zeffii** [comment] 2017-10-21 15:04
yep. it prints to the terminal when it can.
you want Text->Stethoscope

**Comment by retsyo** [comment] 2017-10-21 15:06
thanks and this issue can be closed safely :)

**Comment by zeffii** [comment] 2017-10-21 15:08
ok. enjoy!

**Comment by zeffii** [comment] 2017-10-22 10:12
flattened the thread a little.
