### ISSUE TITLE
Testing Circle inside Monad, degree is not right

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#812] opened 2016-08-18 07:34 UTC
![prtscr capture_9](https://cloud.githubusercontent.com/assets/3952687/17765551/dec9ed4e-6569-11e6-89a6-fd8450f56639.png)

I just make a simple Monad group, placing Circle node, and then plug all the inputs and outputs. The result of Circle is incorrect. The degree seems to become Radian?

**Comment by ly29** [comment] 2016-08-18 07:35
That is a correct observation,  it is not an intended behavior. Somewhat tricky to resolve however... Hmm.

**Comment by zeffii** [comment] 2016-08-18 07:50
the offending code...
```python
    degr_ = FloatProperty(name='Degrees', description='Degrees',
                          default=pi*2, min=0, max=pi*2, subtype='ANGLE',
                          options={'ANIMATABLE'}, update=updateNode)
```

**Comment by ly29** [comment] 2016-08-18 07:53
The solution is convert it back to degrees automatically, I am not certain of how to make that happen in a good way...

**Comment by zeffii** [comment] 2016-08-18 08:46
weird that the subtype is correct, and still this problem?
```python
>> getattr(monad.rna_type, 'degr_')
(<built-in function FloatProperty>, {'description': 'Degrees', 'name': 'Degrees', 'options': {'ANIMATABLE'}, 'min': 0, 'attr': 'degr_', 'update': <function updateNode at 0x000002CE40B04EA0>, 'max': 6.283185307179586, 'subtype': 'ANGLE', 'default': 6.283185307179586})
```

**Comment by zeffii** [comment] 2016-08-18 08:50
i'd motion to make CircleMK2 which drops the Angle subttype, -- as far i can tell the only userfacing difference is that it would drop the Degree symbol...

**Comment by zeffii** [comment] 2016-08-18 08:51
Circle is the only node that uses this subtype.

**Comment by zeffii** [comment] 2016-08-18 08:58
or edit the prop_dict, substitute those values..
```python

if other.node.bl_idname == 'SvCircleNode':
     ...
     prop_dict = prop_dict.copy()
     substitute(prop_dict, replace={min=0, max=360}, remove='subtype')
```

**Comment by ly29** [comment] 2016-08-18 09:03
It is a nice thing to have displayed, would be nice if one could attach a converter function to the socket... 
Since it is the only case let us think for a little while before doing it.

**Comment by ly29** [comment] 2016-08-18 09:14
Was reading through the I/O yesterday and the last thing I want to do is introduce all the checks for specific nodes, I rather introduce a interface for it and deal with it in each node/socket. 

Circle Node could do with some overhaul anyway.

**Comment by ly29** [comment] 2016-08-18 11:10
The proper solutions would of course be to have a proper socket hierarchy for these kinds of events.
Anyway put code into the StringsSocket to deal with this subtype and removed from it circle.

**Comment by ly29** [comment] 2016-08-18 11:53
Should be fixed, update available

**Closed by ly29** 2016-08-18 11:53 UTC
Labels: bug

**Comment by nortikin** [comment] 2016-08-18 16:13
fixed one more - not connected degrees did not work.
