### ISSUE TITLE
bmesh ops and props error.

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#677] opened 2015-06-03 16:02 UTC
cannot take vertices manifold, index 16 out of range.
https://gist.github.com/nortikin/2b4af38fe3fb15f91800
this layout. What i did wrong?

**Comment by Kosvor** [comment] 2015-06-03 18:35
At some point dissolve verts stops working, depending on the original number of vertices:
![15](https://cloud.githubusercontent.com/assets/7894950/7968153/8f9f2286-0a37-11e5-9376-66422ae00668.png)
I do not understand what could be causing this. Perhaps it should happen at some point when the vertex indices are fed into the operator in sorted order

**Comment by Kosvor** [comment] 2015-06-03 19:11
idx socket works well for other ops so i guess it is bmesh bug or intended behavior of dissolve operators.

![256](https://cloud.githubusercontent.com/assets/7894950/7969112/5ca2758a-0a3d-11e5-9589-724f4b85488e.png)

**Comment by Kosvor** [comment] 2015-06-04 08:11
I realized what the problem is- node attempts to select by index not only edges but also vertices with polygons even when it is not necessary. Now I will think how to fix it

**Comment by Kosvor** [comment] 2015-06-04 08:28
https://github.com/nortikin/sverchok/commit/d0214ad5399518f8ceafb391718e724b5459ab77

Это должно помочь, но не тестил

**Comment by Kosvor** [comment] 2015-06-04 09:07
Merged.
Your .json is working now with current master.

**Closed** 2015-06-04 15:20 UTC
Labels: bug

**Comment by nortikin** [comment] 2015-06-04 15:59
оки, спасибо, друг
