### ISSUE TITLE
"Re-update all nodes" causes Blender to freeze.

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4236] opened 2021-07-22 17:27 UTC
I'm working on a file that worked fine before the introduction of the new update system.
While new NURBS features were introduced recently, I desided to update to latest Sverchok master.

I have noticed two things - Live Update is not updating anything ...again (like it was here https://github.com/nortikin/sverchok/issues/4176)

But the thing that makes Sverchok completely unusable this time is that when I pressed "Re-update all nodes" Blender freezes for about half an hour(or maybe more), while before it was making the update for miliseconds. I found that it does not matter if the particular tree is very simple or a complex one. Also before this operation I'm excluding all other trees from the processing.

This work file is really huge. It contains about 70 node trees(some of which very complex and others fairly simple). The tree I'm trying to update is really simple though:
![labels](https://user-images.githubusercontent.com/66558924/126680182-f675c641-19c1-488a-b2fe-50819f9571c3.jpg)

So I can guess that the problem is not in the complexity of the tree itself, or in the node setup, or in the type of nodes that it contains. 

I'm using the latest Blender 2.93.2 (https://builder.blender.org/download/daily/blender-2.93.2-candidate+v293.9e64fd461ac3-windows.amd64-release.zip).

Please help.

**Comment by portnov** [comment] 2021-07-23 04:08
Please attach an example of blend file with such a problem.

**Comment by Durman** [comment] 2021-07-23 04:22
First problem should gone now.
Can confirm the second problem too. Now `Re-update all nodes` operator also check other trees. If `Life update` options of a tree is disabled and tree has some changes since last update then it also will be update even if the update operator was triggered from another tree. This is not what is expected.

**Comment by Durman** [comment] 2021-07-23 05:12
@rendetto Can you update Sverchok from the master and check whether the fixes solved your problems?

**Comment by rendetto** [comment] 2021-07-23 07:33
I updated to latest. The above mentioned problems are solved - "Live update" works as expected and also "Re-update all nodes". Thank you @Durman. Even I got a fraction of a second better performance (from 5.11fps before -> now to 4.89fps).

But here's a third problem I'm experiencing now (I didn't tested it before) - "Update all trees" also causes Blender to freeze. 
Only one tree is enabled to be "processed" and "animated", and several are just "display" enabled. 
When I open the file and first test Live Update and Re-update everything works fine, the moment I press "Update all trees" - Blender freezes.

**Comment by Durman** [comment] 2021-07-23 07:41
Well, if execution of all 70 trees takes half an hour then freezing is expected. `Update all trees` operator updates all trees regardless to their `Live update` state. I think this behaviour was not changed since previous update system.

**Comment by rendetto** [comment] 2021-07-23 08:29
Previously I could choose which trees to update simultaneously and which not by enabling the "P" button, which was very handy.
![update_only_live](https://user-images.githubusercontent.com/66558924/126755921-df28bc1c-81ab-478e-9f4c-1e3147c02306.jpg)

So in the above screenshot if I press "Update all trees", with the previous update system only two trees will be updated.

With the current setup, if it does not matter which trees are marked to be processed, and all trees are processed simultaneously no matter "P" is disabled - if I want to update, say, 20 from all 70 trees, I need to Re-Update all 20 trees one by one, which is not practical.

**Comment by Durman** [comment] 2021-07-23 09:12
I think if `Live update` property of a tree is enabled then it means that it's already updated isn't it? Then it probably doesn't have to much sense to update trees which are already updated. Why do you want to update only updated trees?))

**Comment by rendetto** [comment] 2021-07-23 09:55
Well, do you guarantee that if the "P" is on, all "P-enabled" trees are always and already up to date?

Because I was using "Update all trees" like a "Re-update" operation but for multiple selected trees. In some cases (at least with the previous update system) even with the "P" enabled, a node setup could need some push, which "Update all trees" does (the same way as Re-Update does). And if you have several trees which need this force update - you got it just with one click.

In this sence - if we have now a method to update all trees with "Update all trees", why we do not have a method to "Update only selected trees"?

Now I tested another approach to replicate the previous behavior - enable "animate" only for the trees I want to simultaneously force update, and then change to the next frame in the timeline. 
![update_only_animate](https://user-images.githubusercontent.com/66558924/126764980-be077cec-19b6-4276-bc4e-a238a89769e0.jpg)
It does the job, but somehow I got used to the previous behaviour - using the "Update all trees" button to update only the "P-enabled" trees.

**Comment by Durman** [comment] 2021-07-23 10:25
According my experience current update system is more robust. There of cause can be some cases when it won't update properly but this cases are considered as bugs which should be fixed. For now `Live update` indicates that a tree is in updated state. 

`Update all` button interpolates logic of `Re-update all nodes` button to all trees. Last one updates tree regardless to its state and states of its nodes. `Update all` button is doing the same but for all trees. I don't see purpose of blindly copying logic from previous update system because in new one it does not have much sense. I'm rather up to implement some new feature if there is some problem which current update system does not solve.

**Comment by rendetto** [comment] 2021-07-23 14:19
I understand, thank you. I'll report if there are cases where the trees doesn't update as expected. 

Last questoin - can we expect speed gain or speed drop with the new update system? Notice the edit of the comment I did above about the performance gain I mentioined first (in fact the performance is a bit lower). I tripple checked it, for the same tree and the same settings the old update system gave me 6.60fps, and the new one gave me 6.20fps.

**Comment by Durman** [comment] 2021-07-23 14:30
Yes I can confirm, according my estimation, that new update system is a beat slower. There are plans to improve performance about  10-50% for big trees, trees which use loop nodes and for animation. #4227

**Comment by rendetto** [comment] 2021-07-23 14:37
Thanks, sounds great! Keep up the good work.
I guess this issue could be closed.

**Closed** 2021-07-23 14:40 UTC
Labels: bug

**Comment by rendetto** [comment] 2021-07-23 16:51
I just got a thought. What if you accidentally press the "Update all trees" button - it will freeze or event crash your file, especially in my case with so many and heavy trees. It's too close to Live update button - which I use a lot. 

In terms of UI usability it's not a good solution to have such dangerous button next to frequently used one. 

On the other hand - the old way of updating only the "P-enabled" trees is more user safe.

**Comment by gerroon** [comment] 2021-08-10 22:51
I can confirm this, sometimes it is slower than other times but there is a considerable impact with startup and reloads.
