### ISSUE TITLE
Adding Nodes from Presets panel differs from the other panels

### ISSUE THREAD

**Issue by Ribel78** [nortikin/sverchok#2088] opened 2018-01-24 23:45 UTC
## Problem statement

Created node groups and nodes in Presets panel in Tool shelf after clicking are added to some predefined location as opposed to the nodes on other panels which are in grab mode and move with the mouse.

## Steps to reproduce

1. Click on the node or node group in the Presets panel - the nodes are added to the node workspace but don't move with the mouse.
2. Click on node from any other nodes panel - the nodes are added to the work space but are not released yet from the mouse.

## Expected result

Nodes created through Presets panel should be in grab mode and move under the mouse pointer.

## Actual result

Nodes are placed always in predefined location which can be outside the current node view.
Still they are selected so if the user has enabled Continuous Grab mode by pressing G can move the node even if it is not in the view.
It could be a problem if a group node is added on top of existing node tree and accidentally deselected.

## Sverchok version

SV 0.5.9.6 (b546794)

**Comment by portnov** [comment] 2018-01-25 03:59
Yes, there is such kind-of-problem. I do not know how to solve it currently.
If anyone knows blender python API to initiate moving mode, please fill free to help :)

**Comment by zeffii** [comment] 2018-01-25 09:09
i think this might be two problems that compound eachother.

- when a node / set of nodes is stored as json, their locations are also stored. It's not clear whether it would be desirable to transform the nodes to 0,0, or make the select+active node the 0,0 of the nodes. 
     - let's not even discuss Framed nodes..
- the import from json code (import silent?) does not expect the user to need to grab/transform the nodes as you might expect from a singular step of adding a single node to the tree

it's broken in this sense, but it's not a bug... it's just an incomplete feature implementation.

**Comment by zeffii** [comment] 2018-01-25 09:34
somewhere in 
https://github.com/nortikin/sverchok/blob/de93d4ca72bf6520bd1e061f358983c73f5a70bb/ui/presets.py#L161-L163

you can pass several parameterse to the translate_attach operator ( `NODE_OT_insert_offset` .. might be handly.. )

**Comment by zeffii** [comment] 2018-01-25 09:51
hmmm
```
wm_macro_exec: 'NODE_OT_attach' cant exec macro
wm_macro_exec: 'NODE_OT_insert_offset' cant exec macro

```

**Comment by zeffii** [comment] 2018-01-25 09:54
relevant.. if we really want to do this.. :)  https://blender.stackexchange.com/questions/44971/how-to-use-bpy-ops-macro-defining-macro-steps

**Comment by zeffii** [comment] 2018-01-25 19:01
something [like this](https://gist.github.com/zeffii/59b0f8a443e4afd49f2cf861ad0ffd78) (parking it here so i don't lose it) -- but I suspect there's a simpler (and working) solution. .. maybe nodewrangler is worth delving into..

**Comment by zeffii** [comment] 2018-01-25 20:10
cool.. the grabbing automatically is simple enough @portnov 
```python
                def execute(operator, context):
                    # please not be confused: "operator" here references to
                    # SverchPresetAddOperator instance, and "self" references to
                    # SvPreset instance.  
                    ntree = context.space_data.node_tree
                    id_tree = ntree.name
                    ng = bpy.data.node_groups[id_tree]

                    # Deselect everything, so as a result only imported nodes
                    # will be selected
                    bpy.ops.node.select_all(action='DESELECT')
                    import_tree(ng, self.path)
                    bpy.ops.transform.translate('INVOKE_DEFAULT')
                    return {'FINISHED'}
```
but the preset collector might have to null out the node locations in the .json upon saving.

**Comment by portnov** [comment] 2018-02-07 16:27
@Ribel78 #2094 is merged to the master. The behavior of presets adding operator is not exactly the same as node adding, but I believe it is now much more sane and intuitive that it was:
* Moving mode is automatically initiated when the preset is added
* Initial location of imported nodes is adjusted so that center of newly imported nodes is near to either center of nodes that were selected before adding preset (if there were some nodes selected), or center of all nodes in the tree (if there were no selected nodes).

**Closed by portnov** 2018-02-07 16:27 UTC

**Comment by Ribel78** [comment] 2018-02-08 01:03
@portnov 
Tested it.
Works really well.
Thank you!
