### ISSUE TITLE
Texture viewer node proposal

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1248] opened 2017-02-18 16:34 UTC
I'm trying to implement a simple "texture viewer node" very useful to display data from noise, fractals, ect. nodes. This should help to build complex tree nodes with multiple noise nodes. I started from the easing.py node, not sure if it's a good idea, I added all the code to display the texture but as a result i get displayed only a 64x64 black square , the code is in  [my repo](https://github.com/kalwalt/sverchok/blob/texture_viewer_node/nodes/viz/texture_viewer.py) , but  i dont send yet a pull request. I tryed different combination of type format, and i'm not sure on some bgl OpenGL calls, i think blender treat OpenGl  in a particular manner ( probably i missed something or there is another approach in doing this).
in particular im not sure:

1. how i initialized the `Buffer `,
2. texname = 0 ---> bgl.glBindTexture(bgl.GL_TEXTURE_2D, texname)
                          from Opengl docs:  void glBindTexture( GLenum target, GLuint texture);  you can set texture in this way: static GLuint texName
3. if glTexCoords are correct

Any help is welcome and really appreciated.
Walter

**Comment by zeffii** [comment] 2017-02-18 19:25
The `easing.py` is a good place to start..
http://blender.stackexchange.com/questions/51465/why-is-texture-colour-changing-in-bgl
http://blender.stackexchange.com/questions/23465/how-to-add-backdrop-images-for-py-nodes

for the time being you could draw 64*64 verts :)

**Comment by kalwalt** [comment] 2017-02-18 19:48
@zeffii I think the links you posted are crucials!

**Comment by zeffii** [comment] 2017-02-18 19:52
sadly my familiarity with drawing _texture_ in bgl is superficial at best.

**Comment by kalwalt** [comment] 2017-02-18 20:07
YESSS! it works!
![text viewer-test](https://cloud.githubusercontent.com/assets/1275858/23096485/e8813c80-f61d-11e6-99b0-c322008e0d95.png)

the issue was here: 

````python

bgl.glBegin(bgl.GL_QUADS)
        '''
        for coord in [(x, y), (x, y+1), (x+1, y+1), (x+1, y)]:
            bgl.glTexCoord2f(*coord)
        for coord in [(x, y), (x+w, y), (w+x, y-h), (x, y-h)]:
            bgl.glVertex2f(*coord)
        '''
        bgl.glNormal3f(0, 0, 1)
        bgl.glTexCoord2d(0, 0); bgl.glVertex3f( 0, 0, 0)
        bgl.glTexCoord2d(1, 0); bgl.glVertex3f( 64 , 0, 0)
        bgl.glTexCoord2d(1, 1); bgl.glVertex3f( 64, 64, 0)
        bgl.glTexCoord2d(0, 1); bgl.glVertex3f( 0, 64, 0)

        bgl.glEnd()


````

Tomorrow if i have time i will clean the code, some other testing and maybe i will send a pull request.

**Comment by zeffii** [comment] 2017-02-18 21:36
add https://github.com/nortikin/sverchok/blob/master/nodes/number/easing.py#L181-L182
to your node

```python
    def free(self):
        nvBGL2.callback_disable(node_id(self)) 
```
to remove the drawing if the node is deleted.

**Comment by kalwalt** [comment] 2017-02-18 22:59
another screenshot:
![text viewer--bands-test](https://cloud.githubusercontent.com/assets/1275858/23097515/280b7880-f636-11e6-971f-bf47dc284e3b.png)

**Comment by kalwalt** [comment] 2017-02-19 17:41
Texture of the `Vector fractal node` now can be displayed!
![text-viewer-noise-test](https://cloud.githubusercontent.com/assets/1275858/23104679/d1b016f6-f6d2-11e6-857b-aa44aaa7f962.png)

more to come...

**Comment by kalwalt** [comment] 2017-02-19 17:42
![text-viewer-noise-test01](https://cloud.githubusercontent.com/assets/1275858/23104698/2cd5e466-f6d3-11e6-93d1-8203cd68f3b2.png)

**Comment by zeffii** [comment] 2017-02-19 17:58
cooool :)   you could make a sparse matrix , and prefil all sockets with pink (like missing texture), if the input doesn't have enough data to generate the full matrix

**Comment by zeffii** [comment] 2017-02-19 17:58
cooool :) you could make a sparse matrix , and prefil all elements with pink (like missing texture), if the input doesn't have enough data to generate the full matrix

**Comment by zeffii** [comment] 2017-02-19 17:59
i think numpy works nicely with bgl, and it offers convenient reshaping.

**Comment by kalwalt** [comment] 2017-02-19 18:09
> cooool :) you could make a sparse matrix , and prefil all elements with pink (like missing texture), if the input doesn't have enough data to generate the full matrix

Thank's for the input @zeffii i will look for the sparse matrix, i'm really happy for this node!

**Comment by kalwalt** [comment] 2017-02-19 18:14
another screenshot with bigger texture:
![text-viewer-noise-test02](https://cloud.githubusercontent.com/assets/1275858/23104949/a8b740a8-f6d7-11e6-88b0-58f232113d43.png)

**Comment by zeffii** [comment] 2017-02-19 18:18
are you going to make an operator for it to generate a png ?

**Comment by kalwalt** [comment] 2017-02-19 19:04
> are you going to make an operator for it to generate a png ?

yes, should be quite easy to implement, I'will also consider other image format, and maybe export to `.ter` (Terragen) because the https://developer.blender.org/T18572  Ter2Blend_new.py is quite old and unusable at the moment because rely on old blender API. But for this i will think in a second moment.

**Comment by kalwalt** [comment] 2017-02-19 19:13
i discovered a semi  'issue' ( depend from the point of view...): if you increase octaves in the fractal node the float values increase (of course) but over the range of 1.0, so the image appear more and more white,( because the openGL color range is also 0.0 to 1.0), i think that this not happens while you use a fractal texture in blender. Maybe the output values should be mapped? i have to investigate on this, looking into the blender code. i will found an answer.

**Comment by kalwalt** [comment] 2017-02-19 19:28
to be clear, with fractal node and octaves=1
![text-viewer-noise-test -oct01](https://cloud.githubusercontent.com/assets/1275858/23105589/f3387a84-f6e1-11e6-868b-2ada0dadce2d.png)

**Comment by kalwalt** [comment] 2017-02-19 19:29
octaves=3
![text-viewer-noise-test-oct03](https://cloud.githubusercontent.com/assets/1275858/23105596/094b699e-f6e2-11e6-9c6e-49e3c7234c3c.png)

**Comment by kalwalt** [comment] 2017-02-19 19:30
octaves=6
![text-viewer-noise-test03](https://cloud.githubusercontent.com/assets/1275858/23105621/4508b27a-f6e2-11e6-8597-05da424b580e.png)

**Comment by kalwalt** [comment] 2017-02-19 19:40
we simply can use a `Map range` node before the `Texture viewer` node like in the picture:
![text-viewer-noise-test-map-range](https://cloud.githubusercontent.com/assets/1275858/23105702/7a1c4b7e-f6e3-11e6-936e-f271ae1bcaa9.png)

**Comment by zeffii** [comment] 2017-02-19 19:47
```
import numpy as np

M64_64 = np.random.rand(64,64)   # make a 64*64 matrix
M64_64 -= 0.4  # remove 0.4 from all elements
M64_64 *= 12.0   # multiply each element with 12  to emulate wider 'dynamic' range of pixels
# >>> M64_64    # printing will give a nice concise output too
'''
array([[-1.15660738, -1.04326605,  6.37598547, ..., -1.42415713,
        -1.91208079,  1.81606599],
       [-0.91319606, -0.79191945, -2.71362149, ...,  6.18011012,
         2.29748745, -4.27123536],
       [ 1.55174295,  3.07922017,  4.83449761, ...,  2.54197689,
         1.62176886,  2.1161857 ],
       ..., 
       [-1.72551698,  6.61608313,  5.5984367 , ...,  3.66619624,
         5.80349214, -4.58764623],
       [ 3.60968598, -1.56250354,  5.86323753, ..., -4.66153406,
        -2.27648887,  2.2344777 ],
       [ 4.26722319, -1.06838128, -2.26463052, ..., -3.65690541,
         1.53628724,  3.31683496]])
'''
# now normalize to 0...1 range
N64_64 = M64_64.flatten()

current_range = [np.min(M64_64), np.max(M64_64)]
new_range = [0.0, 1.0]
out = np.interp(M64_64, current_range, new_range)
print(out)

```

**Comment by zeffii** [comment] 2017-02-19 20:15
and
```python
import numpy as np

# regular python array 
my_array = [
   [0.2, 0.3, 0.5],
   [0.6, 0.1, 0.8],
   [0.3, 0.4, 0.6]
]

# push it into a numpy array
new_np_array = np.array(my_array).reshape(1,-1)    #  -1 is magic for 'whatever makes sense just make it 1 row'

print(new_np_array)
# >>> [[ 0.2  0.3  0.5  0.6  0.1  0.8  0.3  0.4  0.6]]
```

**Comment by ly29** [comment] 2017-02-20 08:29
Does the actual buffer shape matter? It just creates a flat buffer with a certain size right, you describe for OpenGL anyway right.

So just make sure to have enough values...

I think limiting this to one texture is totally okay

This creates a penalty when the incoming data isn't the correct size but gives a faster path when works.
I would create the buffer object outside of the callback.

```python
data = socket.sv_get(deepcopy=False)[0]
if len(data) != width * height:
    default_value = 0
    new_data = [default_value for j in range(width * height)]
    new_data[:len(data)] = data[:]
    data = new_data

# and then in init texture
texture = bgl.Buffer(bgl.GL_FLOAT, width * height, data)
```

**Comment by kalwalt** [comment] 2017-02-20 09:32
> Does the actual buffer shape matter? It just creates a flat buffer with a certain size right, you describe for OpenGL anyway right.

I think it also depends on the OpneGl version you are using, for older versions the minor size is 64x64 pixels and squared, newer versions let you more freedom.  

> So just make sure to have enough values...

yes this is the point. I will try your code @ly29 

> I would create the buffer object outside of the callback.

 also the init_texture function or only the Buffer?

**Comment by kalwalt** [comment] 2017-02-20 09:33
@zeffii  thanks for the matrix tips, it's a field i should improve...

**Comment by ly29** [comment] 2017-02-20 09:37
What I meant is as long as the texture buffer is the right total size (64*64 => 4096 etc) , does the shape of the ```bgl.Buffer``` object matter?

```
Buffer = bgl.Buffer(bgl.GL_FLOAT, [width,height], data)
# vs
Buffer = bgl.Buffer(bgl.GL_FLOAT,  width * height, data)
```
Is there any difference for OpenGL ?

The shape of the buffer is still described in,
```
        bgl.glTexImage2D(
               bgl.GL_TEXTURE_2D, 0, bgl.GL_LUMINANCE, width, height, 0,
               bgl.GL_LUMINANCE, bgl.GL_FLOAT, Buffer
           )
```

**Comment by kalwalt** [comment] 2017-02-20 09:43
```
Buffer = bgl.Buffer(bgl.GL_FLOAT, [width,height], data)
# vs
Buffer = bgl.Buffer(bgl.GL_FLOAT,  width * height, data)
```
yes you are right this make a BIG difference, sorry, i didn't realize it...

**Comment by kalwalt** [comment] 2017-02-20 09:59
> I would create the buffer object outside of the callback.

@ly29 what does it mean 'outside' here?

```
A ... put the code here

nvBGL2.callback_disable(n_id)

B... put the code here 

nvBGL2.callback_enable(n_id, draw_data)
```

**Comment by ly29** [comment] 2017-02-20 10:00
So I tested a bit, the answer is no, the shape of the buffer doesn't matter, allowing us to skip the split node.

![texture](https://cloud.githubusercontent.com/assets/6241382/23120137/7e01bdf0-f75b-11e6-8a55-9d0640679c8a.PNG)

The texture could be done outside of the callback it would be better.

Would also like the size to be visible in the dropdown, 512x512 is more helpful than large.

**Comment by kalwalt** [comment] 2017-02-20 10:05
![text-viewer-noise-test-reshape](https://cloud.githubusercontent.com/assets/1275858/23120373/5e73f240-f75c-11e6-9988-22e94f705a08.png)
@ly29 yes it works!

**Comment by kalwalt** [comment] 2017-02-20 10:07
> Would also like the size to be visible in the dropdown, 512x512 is more helpful than large.

yes not only in the tooltips, small or large is relative... better a pixel dimension.

**Comment by zeffii** [comment] 2017-02-20 10:08
you have to make `game of life` now.

**Comment by ly29** [comment] 2017-02-20 10:08
```python

    def process(self):
        p = self.inputs['Float'].sv_get(deepcopy=False)
        n_id = node_id(self)

        # end early
        nvBGL2.callback_disable(n_id)

        data = p[0]
        #print(_data)
        if self.activate:

            size_tex = size_tex_dict.get(self.selected_mode)
            total_size = size_tex * size_tex
            if len(data) < total_size:
                default_value = 0
                new_data = [default_value for j in range(total_size)]
                new_data[:len(data)] = data[:]
                data = new_data
            elif len(data) > total_size:
                data = data[:total_size]
            # and then in init texture
            texture = bgl.Buffer(bgl.GL_FLOAT, total_size, data)

            palette = palette_dict.get(self.selected_theme_mode)[:]
            x, y = [int(j) for j in (self.location + Vector((self.width + 20, 0)))[:]]
            #size_tex = size_tex_dict.get('SMALL')
            #size_tex = size_tex_list[0][4]
            print(size_tex)
            #print(self.selected_mode[1])

            draw_data = {
                'tree_name': self.id_data.name[:],
                'mode': 'custom_function',
                'custom_function': simple_screen,
                'loc': (x, y),
                'args': (palette, texture, size_tex)
                #'args': (palette, _data)
            }
            nvBGL2.callback_enable(n_id, draw_data)
```

**Comment by kalwalt** [comment] 2017-02-20 10:11
> you have to make game of life now.

@zeffii lol, yes, but i did it with OpenFrameworks https://github.com/patriciogonzalezvivo/ofxFX/tree/master/example-conway

@ly29 it's clear now!

**Comment by enzyme69** [comment] 2017-02-20 10:16
@kalwalt I am reading the thread with awe. Cannot wait to test this!

So is this really fast that we can kind of use it like OSL?

**Comment by ly29** [comment] 2017-02-20 10:20
@enzyme69 
Now, it is sadly not that fast.

@kalwalt 
The texture should done outside of draw call as well I guess, so the callback only has to draw the relevant parts.

**Comment by kalwalt** [comment] 2017-02-20 10:23
> So is this really fast that we can kind of use it like OSL?
 
@enzyme69  i agree with @ly29  but it's worth to implement, and faster than build a geom.

> The texture should done outside of draw call as well I guess, so the callback only has to draw the relevant parts.

ok understood. i'm going to rearrange the code

**Comment by ly29** [comment] 2017-02-20 10:33
@kalwalt 
Totally worth it, 
@zeffii 
This is a case where Redux should shine
![texture_sincos](https://cloud.githubusercontent.com/assets/6241382/23121334/46ed2494-f760-11e6-8c35-2820c6bae7eb.PNG)

**Comment by ly29** [comment] 2017-02-20 10:46
@zeffii 
5.9 seconds vs 0.12 seconds. 😄 for the same path until the texture viewer. 49x times faster.

**Comment by zeffii** [comment] 2017-02-20 11:11
if that updates in 6 seconds on your machine, i shudder to think how long it would take on my low end lenovo.

**Comment by ly29** [comment] 2017-02-20 11:16
By rearranging and moving it around a bit I could get it down to 3 seconds with some extra ```deepcopy=False```, was also think plane directly would be quicker than splitting and doing some of the other stuff but plane node is very slow. it should be possible to speed it up a lot, but due to doing to many things in there I rather not touch it...

**Comment by ly29** [comment] 2017-02-20 14:18
This really is very nice, will rip it of to redux quickly after it is finished more or less.

**Comment by ly29** [comment] 2017-02-20 15:11
Made script that assigns to the image viewer for view for redux.

**Comment by enzyme69** [comment] 2017-02-21 11:14
@ly29 This seems pretty hires on the viewer!? So far I tried 500x500 points, 1000 x 1000 a bit slow, still work ok.

I am staring and studying this one.

**Comment by enzyme69** [comment] 2017-02-21 11:17
This Texture Viewer is node visible here yet, so I will wait....

**Comment by ly29** [comment] 2017-02-21 11:17
@enzyme69 
Yeah it is slow but I was testing how slow and compared to redux. I hope we get it in soon as well.

**Comment by enzyme69** [comment] 2017-02-21 11:26
@ly29 Thanks so much!

Interesting technique with list split in Y to make grid and this pattern, btw! 

![screen shot 2017-02-21 at 22 25 27](https://cloud.githubusercontent.com/assets/3952687/23162978/ae898212-f884-11e6-801f-0091fdc32c82.png)

**Comment by ly29** [comment] 2017-02-23 15:47
So it is in master! 🎆 🍾 

Still needs some work.
Things I would like to see.

- Constant output to image viewer
- Color mode
- Sorting out saving, but less important if we can output to image editor and save from there until resolved.

**Comment by ly29** [comment] 2017-02-23 18:33
Yes.

**Comment by enzyme69** [comment] 2017-02-24 08:34
Thanks for this node @kalwalt , few feedback:
- can we have notification of "file saved at this path" when it is saving image.
- can we actually have multiple texture viewers, I tested but seems like it does not work if I have multiple of this node. Unless I cannot duplicate the node, need to make new ones.

**Comment by zeffii** [comment] 2017-02-24 08:37
>  can we actually have multiple texture viewers, I tested but seems like it does not work if I have multiple of this node. Unless I cannot duplicate the node, need to make new ones.

Did you only duplicate, or did you also try adding the second one from the menu?

**Comment by enzyme69** [comment] 2017-02-24 08:38
I only duplicate.

**Comment by zeffii** [comment] 2017-02-24 08:38
try creating new. too.

**Comment by enzyme69** [comment] 2017-02-24 08:39
@zeffii Issue, persist, seems that it will "update" to latest data it got plugged, but all viewer displaying the same thing.

**Comment by enzyme69** [comment] 2017-02-24 08:40
Got GIST:
https://gist.github.com/153bead73fd96139dcfc7fb4f1e5d782

And also, I am not 100% sure why I am getting error when trying to save bmp

> Traceback (most recent call last):
>   File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 68, in execute
>     getattr(context.node, self.fn_name)()
>   File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/sverchok-master/nodes/viz/texture_viewer.py", line 247, in save_bitmap
>     np_buff[:, :] = np.array(buf)[:, np.newaxis]
> ValueError: could not broadcast input array from shape (1048576,1) into shape (65536,4)

**Comment by enzyme69** [comment] 2017-02-24 08:42
![texture_viewer_002](https://cloud.githubusercontent.com/assets/3952687/23296466/4d5a2e5a-fac9-11e6-9e9a-6b8795acd2df.gif)

**Comment by zeffii** [comment] 2017-02-24 08:43
ok, well it's not the callback, because that works in the `Easing node..` you can have any number of independant calls.

**Comment by zeffii** [comment] 2017-02-24 08:45
it's this `     texture = []  `  as declared in the node's class.

**Comment by zeffii** [comment] 2017-02-24 08:46
problem:  
this means all instances of the node will be using the same texture to read and write from.

solution:
use a node dict

**Comment by zeffii** [comment] 2017-02-24 08:47
```python
class SvTextureViewerNode(bpy.types.Node, SverchCustomTreeNode):
    '''Texture Viewer node'''
    bl_idname = 'SvTextureViewerNode'
    bl_label = 'Texture viewer'
    texture = {}

```
where we should store the `node_id` along with a texture instead of just the texture.

**Comment by ly29** [comment] 2017-02-24 08:47
> it's this `texture = []` as declared in the node's class.

That is never used as far as I can see.

**Comment by zeffii** [comment] 2017-02-24 08:51
it doesn't look like it, i agree.

**Comment by zeffii** [comment] 2017-02-24 08:52
is it the deepcopy?

**Comment by zeffii** [comment] 2017-02-24 08:53
```python
    def get_buffer(self):
        data = self.inputs['Float'].sv_get(deepcopy=False)[0]
        size_tex = size_tex_dict.get(self.selected_mode)
        total_size = size_tex * size_tex
        if len(data) < total_size:
            default_value = 0
            new_data = [default_value for j in range(total_size)]
            new_data[:len(data)] = data[:]
            data = new_data
        elif len(data) > total_size:
            data = data[:total_size]

        texture = bgl.Buffer(bgl.GL_FLOAT, total_size, data)
        return texture
```
that is modifying the original data.

**Comment by ly29** [comment] 2017-02-24 08:55
I think I know
https://docs.blender.org/api/blender_python_api_2_78_release/bgl.html?highlight=glgentextures

**Comment by enzyme69** [comment] 2017-02-24 08:55
If this node can view and output Texture Image... at some point somebody will request: sequence of images output. Maybe some kind of functionality that can bake per frame.

**Comment by zeffii** [comment] 2017-02-24 08:56
`texname = 0 ` indeed.

**Comment by kalwalt** [comment] 2017-02-24 08:56
i think if ypu want another texture you need another texture slot

**Comment by ly29** [comment] 2017-02-24 08:59
So fixed now.
![snipp](https://cloud.githubusercontent.com/assets/6241382/23297010/fa8abdda-fa77-11e6-937c-3e1a87bdab28.PNG)

**Comment by ly29** [comment] 2017-02-24 09:00
We might want some cleanup after textures as well...

**Comment by ly29** [comment] 2017-02-24 09:07
Okay so now we delete textures as needed as well, everybody please update and test.

**Comment by kalwalt** [comment] 2017-02-24 09:14
![multi texture-viewer](https://cloud.githubusercontent.com/assets/1275858/23297499/0d105954-fa7a-11e6-80b5-42223d106d9c.png)
it seems to work

**Comment by zeffii** [comment] 2017-02-24 09:15
i'll add a generic Directory selector.

**Comment by ly29** [comment] 2017-02-24 09:16
I added ```img.scale``` so it changes the size of images as needed.

Also the images are drawn upside down.

**Comment by ly29** [comment] 2017-02-24 09:17
```python
        bgl.glTexCoord2d(0, 0)
        bgl.glVertex2f(x, y)
        bgl.glTexCoord2d(1, 0)
        bgl.glVertex2f(x + w, y)
        bgl.glTexCoord2d(1, 1)
        bgl.glVertex2f(x + w, y - h)
        bgl.glTexCoord2d(0, 1)
        bgl.glVertex2f(x, y - h)
```

**Comment by ly29** [comment] 2017-02-24 09:18
Ok really need to do other stuff now @zeffii will leave it to you

**Comment by zeffii** [comment] 2017-02-24 09:18
( no such thing as `/tmp/` on windows. )

**Comment by kalwalt** [comment] 2017-02-24 09:19
> Also the images are drawn upside down.
i didn't notice before. 
yeah the texture coords
>( no such thing as /tmp/ on windows. )
my bad i developed in linux, no tested in windows

**Comment by zeffii** [comment] 2017-02-24 09:22
it still saves correctly to `c:/tmp/` , which is ..a miracle.

**Comment by enzyme69** [comment] 2017-02-24 09:34
Yes, it default to c:/tmp Windows stuff :) I probably need to update again.
Will test this, will live noding it, and looking forward for future update!
:D

**Comment by kalwalt** [comment] 2017-02-24 09:50
This node i think will have an incredible development!

**Comment by zeffii** [comment] 2017-02-24 09:55
@enzyme69  be sure to read  https://github.com/nortikin/sverchok/blob/master/docs/nodes/viz/texture_viewer.rst  and ask for clarification if needed

The more info those docs have the better.

**Comment by ly29** [comment] 2017-02-24 09:59
@enzyme69 
Wait a day or two until some small further bugs are fixed.

**Comment by enzyme69** [comment] 2017-02-24 10:03
@kalwalt Confirmed, multiple viewer seems to work after latest update. So it is a WIP, I will mention.
@zeffii Yes, documentation is key
@ly29 Will do.

**Comment by ly29** [comment] 2017-02-24 10:11
Texture cords fixed

**Comment by enzyme69** [comment] 2017-02-24 10:14
Interesting... Where did I do wrong. Maybe Texture Coordinates thing. 

@ly29 "Ok really need to do other stuff now @zeffii will leave it to you" :)

https://gist.github.com/c0779187b01ba578b26e229d18dacc95

![screen shot 2017-02-24 at 21 12 55](https://cloud.githubusercontent.com/assets/3952687/23299547/06426aa2-fad6-11e6-9a3f-c72195eae1e6.png)

**Comment by enzyme69** [comment] 2017-02-24 10:14
I'll test.

**Comment by kalwalt** [comment] 2017-02-24 10:17
@enzyme69  in plane try with smaller values in step ( but size need to increase) you will have nicer result.

**Comment by enzyme69** [comment] 2017-02-24 10:17
Ooh ... CLAMPING! Who would have thought...
![screen shot 2017-02-24 at 21 16 55](https://cloud.githubusercontent.com/assets/3952687/23299680/9bd3e2ee-fad6-11e6-86d6-6a241a0ea0cd.png)

Which means the map is 2D and not 16 bit :D yet

**Comment by enzyme69** [comment] 2017-02-24 10:18
Got it!

**Comment by kalwalt** [comment] 2017-02-24 10:20
> Which means the map is 2D and not 16 bit :D yet
yes is set to GL_LUMINANCE id est a grayscale not RGB or RGBA or other format.

**Comment by zeffii** [comment] 2017-02-24 10:23
![image](https://cloud.githubusercontent.com/assets/619340/23299916/ac144714-fa83-11e6-9992-fb95e515725b.png)

**Comment by enzyme69** [comment] 2017-02-24 10:24
![screen shot 2017-02-24 at 21 24 25](https://cloud.githubusercontent.com/assets/3952687/23299968/a398d560-fad7-11e6-8b23-7aa1514384fc.png)

https://gist.github.com/f8fab10e63c1161630e49640432947f0

Export PNG, brought in as Displacement.

**Comment by enzyme69** [comment] 2017-02-24 10:25
CLAMP off:

![screen shot 2017-02-24 at 21 25 12](https://cloud.githubusercontent.com/assets/3952687/23299995/c15ebd1c-fad7-11e6-8f37-d202ad0ee340.png)

**Comment by enzyme69** [comment] 2017-02-24 10:26
I can see something that would become like "Mountain SOP" layered texture terrain generator ala Houdini.

**Comment by kalwalt** [comment] 2017-02-24 10:26
> I can see something that would become like "Mountain SOP" layered texture terrain generator ala Houdini.

this is the same impression and feeling!

**Comment by ly29** [comment] 2017-02-24 10:27
@enzyme69 @kalwalt 
Wait until you see in redux 😄
 where the larger texture sizes will be workable.

**Comment by kalwalt** [comment] 2017-02-24 10:28
we could open a separate node sections for terrain generation @zeffii @ly29 @enzyme69 what do you think?

> Wait until you see in redux :smile:
where the larger texture sizes will be workable.

ok!

**Comment by enzyme69** [comment] 2017-02-24 10:32
![screen shot 2017-02-24 at 21 27 23](https://cloud.githubusercontent.com/assets/3952687/23300064/0f6daf0e-fad8-11e6-8bbe-031a98005d37.png)

Modulo is a funky stepped terrain, nice one @zeffii .

@ly29 Yes! Redux.

@kalwalt I went to Houdini 16 and they borrowed lots of Blender UI, Pie Menu, Boolean madness level ... but Houdini is of course a bit crazy with Terrain, and lots of complex solvers.

Anyhow, this node is nice!

@kalwalt Separate node for terrain involving Normal Push, etc? Then it's like Displace Modifier a bit, ... but can have "Clipping"?

Currently Viewer is nice, I can see viewer at 256 x 256 (hires points) for 256 x 256, but perhaps user want to see 64 x 64 viewer for 1024 x 1024 or perhaps 256 x 256 viewer for 16x16.

My brain didn't compute, but I'll make a live noding video first now :)

**Comment by kalwalt** [comment] 2017-02-24 10:43
@enzyme69 Unfortunately i dont know so much Houdini, i always use [Terragen](http://planetside.co.uk/) that i love and [world-machine](http://www.world-machine.com/) should be nice has some tools for terrain production. This is one of the reasons for my interest in this node.

> Separate node for terrain involving Normal Push, etc? Then it's like Displace Modifier a bit, ... but can have "Clipping"?

i think they has lot of this features, plus erosion alghorithm, slope selector and so on...

 But maybe better open a separate issue for this

**Comment by kalwalt** [comment] 2017-02-24 10:45
> Currently Viewer is nice, I can see viewer at 256 x 256 (hires points) for 256 x 256, but perhaps user want to see 64 x 64 viewer for 1024 x 1024 or perhaps 256 x 256 viewer for 16x16.

maybe adding mipmapping should add this feature.

**Comment by enzyme69** [comment] 2017-02-24 11:07
I realized normalizing the value to fit certain range, and it works best for displacement texture. Interesting! I finally have better understanding about displacement boundary.

**Comment by zeffii** [comment] 2017-02-24 11:07
(the directory saving isn't fixed yet.. )

**Comment by ly29** [comment] 2017-02-24 12:01
@zeffii 
This would be cool for avoid dealing with blenders images.
http://stackoverflow.com/a/19174800

**Comment by zeffii** [comment] 2017-02-24 12:25
yes. agreed - definitely.

**Comment by ly29** [comment] 2017-02-24 12:27
Anyway two now issues are needed. 
1 issues with texture viz node
2 experiments with viz node

This is long enough now.

**Closed by ly29** 2017-02-24 12:27 UTC
