### ISSUE TITLE
Grease Pencil 1 frame lag

### ISSUE THREAD

**Issue by adamwparker** [nortikin/sverchok#1400] opened 2017-03-21 16:19 UTC
When outputting points of Grease Pencil strokes as vertices, the current frame lags behind by one frame. It would be great if it updated along with the current frame.

**Comment by zeffii** [comment] 2017-03-21 17:02
It requires making a dedicated node to have useful control over gp ,  else we are limited to only modifying points not adding. The 1 frame lag might be down to some throttling in the event handler for frame change. It was observed but not investigated, pending addition of a dedicated node.

I ask for patience.

**Comment by adamwparker** [comment] 2017-03-21 18:01
Thanks for all your hard work. You are great!

**Comment by zeffii** [comment] 2017-03-21 19:31
i'm closing this because the issue is a symptom of slightly unfavourable update system, specifically related to datablocks. When that's resolved this issue will be too.

**Closed by zeffii** 2017-03-21 19:31 UTC
