### ISSUE TITLE
IOJson for monads - doesn't recreate slider names if manually renamed

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1596] opened 2017-04-28 06:39 UTC
![bug export group node](https://cloud.githubusercontent.com/assets/28003269/25517033/9ee3859e-2bfe-11e7-845d-ed799a1bb6eb.gif)

`Traceback (most recent call last):
  File "C:\Users\SLAVE\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\sverchok-master\utils\sv_IO_panel_tools.py", line 689, in execute
    layout_dict = create_dict_of_tree(ng)
  File "C:\Users\SLAVE\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\sverchok-master\utils\sv_IO_panel_tools.py", line 241, in create_dict_of_tree
    socket = node.inputs[socket_name]
KeyError: 'bpy_prop_collection[key]: key "Float" not found'

location: <unknown location>:-1
`

**Comment by zeffii** [comment] 2017-04-28 07:42
interesting.. i will investigate and fix!  Thanks for bringing it up.

**Comment by zeffii** [comment] 2017-04-28 08:49
A few debug things here..

- it works if you don't rename the socket
- is not related to wheter the initial socket has a `name= field`

**Comment by zeffii** [comment] 2017-04-28 09:02
am tempted to go with 
```python
    for idx, (socket_name, socket_type, prop_dict) in enumerate(node.input_template):
        socket = node.inputs[idx]
```
because (and i'll check this ) i think `.input_template` is itself enumerated that way when generated)

**Comment by zeffii** [comment] 2017-04-28 09:15
https://github.com/nortikin/sverchok/pull/1597
should be fixed now.

**Comment by Durman** [comment] 2017-04-28 09:28
I do not see names of inputs after import. :(
![2017-04-27_09-24-43](https://cloud.githubusercontent.com/assets/28003269/25523079/81a86c70-2c16-11e7-8d08-7895cd8ede56.png)

**Comment by zeffii** [comment] 2017-04-28 09:36
ok. will look at that

**Comment by zeffii** [comment] 2017-04-28 09:39
show me the .json for that file please.  (use the gist feature to upload )
- either manually https://gist.github.com/
- or  automatic with 
![image](https://cloud.githubusercontent.com/assets/619340/25523548/57da67d6-2c07-11e7-95bc-58e6b879fb45.png) and paste the url here

**Comment by Durman** [comment] 2017-04-28 09:46
[https://gist.github.com/ed906661bd5873694626d0784db66313](url)

**Comment by zeffii** [comment] 2017-04-28 09:49
ok i see now, it isn't using the renamed socketname, but the original..

: /  i will have to think about this for a while.  The is just a problem with the IO/Json stuff .. not necessarily the monad system itself.

**Comment by zeffii** [comment] 2017-04-28 11:41
`input_template` found in the json (exported) 
is the same as `nodes['Monad'].input_template` (pre export)

**Comment by zeffii** [comment] 2017-04-28 12:06
https://github.com/nortikin/sverchok/blob/master/utils/monad.py#L129-L135

will need to be added.   Soon :)

**Comment by zeffii** [comment] 2017-04-28 17:37
this is taking a bit longer than I had anticipated . thanks for your patience.

**Comment by zeffii** [comment] 2017-04-28 17:46
get_all_props(self) might be needed

**Comment by zeffii** [comment] 2017-04-29 14:10
i've modularized the monad IO code so both are in the same file, easier to handle.  (still not fixed...but this needed to be done anyway)

**Comment by zeffii** [comment] 2017-04-29 16:40
OK. it's working now.. will push later.

**Comment by zeffii** [comment] 2017-04-29 18:08
pushed - update !    find other broken stuff :)

**Comment by Durman** [comment] 2017-04-29 18:55
Now after import I have names of first input everywhere . Must be: name1, name2, name3, name4
![2017-04-29_22-51-51](https://cloud.githubusercontent.com/assets/28003269/25558005/d770ce04-2d2e-11e7-9ae9-ebf85919a495.png)

**Comment by zeffii** [comment] 2017-04-29 19:28
please share the gist. /json

**Comment by zeffii** [comment] 2017-04-29 19:29
![image](https://cloud.githubusercontent.com/assets/619340/25558244/ecacde54-2d22-11e7-8ee5-12d9b8c2a76f.png)

**Comment by zeffii** [comment] 2017-04-29 19:32
btw, @Durman   this will only work on json that you exported after i did the last update. Jsons that you exported before that will not have enough information to rebuild the monad.

**Comment by zeffii** [comment] 2017-04-29 19:49
set_all_props(self, data)   might need a `self.float_props.clear()` and `self.int_props.clear()` ..

**Comment by zeffii** [comment] 2017-04-29 20:47
@Durman  link a non-working recently made gist/json here and i'll know more..

**Comment by Durman** [comment] 2017-04-30 02:46
@zeffii 
[https://gist.github.com/bcfbe9d3bad4a2e9d21d6fe552271b28](url)

**Comment by zeffii** [comment] 2017-04-30 05:37
@Durman you can just paste the url without manually adding tag,.

Looks like the json does store the renames correctly now,  but reloading needs more attention.

**Comment by zeffii** [comment] 2017-04-30 07:48
I have a vague understanding of what's happening now, can't promise this will be fixed soon.

**Comment by zeffii** [comment] 2017-04-30 16:47
it's giving the correct identifier (name) to the sockets but not pushing the correct prop_name
```python
import bpy

nodes = bpy.data.node_groups['NodeTree'].nodes
mon = nodes['Monad']


mmm = {
 "all_props": {
    "cls_bl_idname": "SvGroupNodeMonad_882974319",
    "float_props": {
        "float_": {    "default": 0.0,  "name": "Name1"   },
        "float_2": {   "default": 0.0,  "name": "Name2"   },
        "float_3": {   "default": 0.0,  "name": "Name3"   },
        "float_4": {   "default": 0.0,  "name": "Name4"   }
    },
    "int_props": {},
    "name": "Monad"
  }
}

jii = mmm["all_props"]

def get_valid_socket(proposed_name):
    for i in mon.inputs:
        if i.name == proposed_name:
            return i.index

for k, v in jii['float_props'].items():
    prop_var_name = k
    prop_prop_name = v["name"]
    idx = get_valid_socket(prop_prop_name)
    mon.inputs[idx].prop_name = prop_var_name
```

**Comment by zeffii** [comment] 2017-05-02 08:38
I've stared at this for a couple of hours over the last few days, and have a fair idea of what the monad storage / to json / from json should look like, but it will involve making a small adjustment to the monad system, to allow per socket index cataloguing (as opposed to per property type without socket index).

I can not guarantee this won't affect existing json files that store monads (poorly - but may work in simple cases..) -- but this might be the price of progress, and make it easier for to fix this .  Seen as @ly29  must focus on other things at the moment.

**Comment by zeffii** [comment] 2017-05-02 09:54
```python
import bpy
import pprint

nodes = bpy.data.node_groups['NodeTree'].nodes
monad_node = nodes['Monad']

def gather_props(monad_node):

    socket_storage = {'inputs': [], 'outputs': []}

    def info(kind_name, s):
        socket_data = {kind_name: s.index, 'socket_name': s.name}
        
        if hasattr(s, 'prop_name') and s.prop_name:
            socket_data.update({'prop_name': s.prop_name})
        elif hasattr(s, 'prop_type') and s.prop_type:
            socket_data.update({'prop_type': s.prop_type})

        return socket_data

    for kind_name in ('inputs', 'outputs'):
        sockets = getattr(monad_node, kind_name)
        for idx, socket in enumerate(sockets):
            socket_storage[kind_name].append(info(kind_name, socket))

    pprint.pprint(socket_storage)
    return socket_storage

gather_props(monad_node)
```
this is the output when i don't rename any sockets
```text
{'inputs': [{'inputs': 0, 'socket_name': 'Location'},
            {'inputs': 1, 'prop_name': 'count_', 'socket_name': 'Stop'}],
 'outputs': [{'outputs': 0, 'socket_name': 'Vertices'}]}
```
but if I rename sockets we get this
```
{'inputs': [{'inputs': 0, 'socket_name': 'loco1'},
            {'inputs': 1, 'prop_name': 'count_', 'socket_name': 'terminator'}],
 'outputs': [{'outputs': 0, 'socket_name': 'vert_out'}]}
```
and 
`monad_node.monad.get_all_props()`
outputs
```
{'cls_bl_idname': 'SvGroupNodeMonad_1921650826890', 
'name': 'Monad', 
'float_props': {}, 
'int_props': 
    {'count_': {
        'default': 10, 'description': 'huh', 'name': 'terminator', 'min': 1}}}
```

**Comment by zeffii** [comment] 2017-05-02 10:11
now.. it becomes interesting when we have multiple similar nodes connected to inputs and outputs.
```
-----
{'inputs': [{'inputs': 0, 'socket_name': 'loco1'},
            {'inputs': 1, 'prop_name': 'count_', 'socket_name': 'terminator'},
            {'inputs': 2, 'prop_name': 'start_', 'socket_name': 'Start'},
            {'inputs': 3, 'prop_name': 'count_', 'socket_name': 'Stop'}],
 'outputs': [{'outputs': 0, 'socket_name': 'vert_out'},
             {'outputs': 1, 'socket_name': 'Range'}]}
{'cls_bl_idname': 'SvGroupNodeMonad_1921650826890',
 'float_props': {'start_': {'default': 0.0,
                            'description': 'start',
                            'name': 'start'}},
 'int_props': {'count_': {'default': 10,
                          'description': 'huh',
                          'min': 1,
                          'name': 'terminator'},
               'count_2': {'default': 10,
                           'description': 'num items',
                           'min': 1,
                           'name': 'count'}},
 'name': 'Monad'}



```

**Comment by Durman** [comment] 2017-05-02 10:16
@zeffii 
There are too many bugs with group nodes. Group nodes are useful but not necessary. May be better it will be fixed later.
https://gist.github.com/977ce2cd5c1e6b0cdc30de5da8fcbfea
![bug](https://cloud.githubusercontent.com/assets/28003269/25613982/359228c0-2f41-11e7-8c29-bee06a8f6ffe.gif)

**Comment by zeffii** [comment] 2017-05-02 10:19
@Durman   the problem is not so much the Group node (monad) .. but the import/export of the node. The import / export  is not fully coded yet.  

I can only suggest not using IO if your .blend uses Monads for now.

**Comment by zeffii** [comment] 2017-05-02 10:23
let me put it this way

if you use group nodes / monad 

then don't use this panel.

![image](https://cloud.githubusercontent.com/assets/619340/25614342/e08e46b0-2f31-11e7-9252-1a7f814bafa1.png)

**Comment by zeffii** [comment] 2017-05-02 10:25
except for 'Save Blend as Zip`. that's fine to use.

**Comment by enzyme69** [comment] 2017-05-02 10:56
That's a good point to remember, for now. I am ok with it.

**Comment by zeffii** [comment] 2017-05-02 12:19
closing this in favour of a new Issue where i enumerate all the issues with Monad IO.

**Closed by zeffii** 2017-05-02 12:19 UTC
Labels: beta, bug, maintenance
