### ISSUE TITLE
ViewerDraw in b28

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2372] opened 2019-02-26 14:39 UTC
The current implementation ( VD_Experimental ) is a first attempt at using the new API/shader stuff. , and has helped debug the porting of nodes. It is quite limited in its current form, but might serve as a reference implementation for other openGL nodes in Sverchok.

I want to talk about implementing a VDMK2 port

**Comment by vicdoval** [comment] 2019-04-25 13:24
It is almost there isn't it?  
Apart of the fact that it does not draw anything if  only vertices input is connected,
The bake operator is missing and some other minor options, 
Are there any features you would like to discuss?

**Comment by zeffii** [comment] 2019-04-25 15:28
i'm undecided about how the automatic geometry extending should happen, we could offer several approaches..

```python
if len(verts)< len(edges):
    ...
    extend verts count to match edges, but also make sure there are enough verts in each new set to 
    create a valid edge net (no invalid indices, 
           - auto repeat with zero vectors would be optional
           - or... 
           - drop edges that reference invalid vertices indices  

if len(verts) <len(faces):
   ...    
   same idea
```
and ..should we merge all incoming geometry and create only 1 massive drawing call, or generate multiple calls to the shader (to match number of incoming objects sets) , i suspect one of those options is fast, and the other is by far the simpler to maintain :)

**Comment by zeffii** [comment] 2019-04-25 15:37
also....  it would be possible to accept a color input, and handle this like the vertex_colors node

but first perhaps a rewrite of the logic, and then refine the draw functions.

**Comment by vicdoval** [comment] 2019-04-25 17:43
I would drop the references to invalid_vertex indices printing something to the log.
And about the calls to the shader I think the "one call" is the cleaner and probably faster method.

the color input could be handy.
Another idea would be to have some verts, edges  and matrix display types, (cross, cross with circle...,dotted line, axis only...)
But first the logic :)

**Comment by zeffii** [comment] 2019-05-03 10:20
here's a table to help me relate to this problem in future

   n             |  verts in | edges in | faces in | matrix in
---------------- | --------- | -------- | -------- | ---------
show verts       |     x     |          |          |          
show edges       |     x     |     (x)    |   x    |          
show faces       |     x     |          |    x     |          
display matrices |           |          |          |     x     
display smooth   |     x     |          |    x     |          
display facet    |     x     |          |    x     |          
display glsl     |     x     |          |    x     |          

the parenthesis (x) shows that edges can be inferred from faces, where edges is optional, but if edges is not connected the faces is mandatory to be able to infer edge display

**Comment by zeffii** [comment] 2019-05-03 11:18
plainly

```python
def draw_geometry(mode, socket_data):
    if mode == 'v':                       | requires verts
        # draw verts only                 

    if mode == 've':                      | reguires verts and (edges or faces)
        # draw verts and edges

    if mode == 'vf':                      | requires verts and faces
        # draw verts and faces          

    if mode == 'vef':                     | requires verts and faces, but edges is inferrable if ommitted
        # draw verts, edges, and faces

    if mode == 'e':                       | requires verts and (edges or faces, if faces only then infer, if edges_in then use edges)
        # draw only edges

    if mode == 'f':                       | requires verts and faces
        # draw only faces

    if mode == 'ef':                      | requires verts and faces, infer edges from faces if no edge_in 
        # draw edges and faces

    if mode == 'm':                       | requires only matrices
        # draw only matrices
```

**Comment by zeffii** [comment] 2019-05-03 11:28
only modes that include `f`  can be used for display flat / facetted / smooth / glsl

**Comment by javismiles** [comment] 2019-05-14 11:03
good day friends, Im really looking forward to Viewer Draw working on 2.8, any forecast as to when it will be functional? thank you so much :)

**Comment by zeffii** [comment] 2019-05-14 11:28
in the meantime `VD_Experimental` should/might fulfill most of your needs, it's been slightly updated this week by @vicdoval

**Comment by javismiles** [comment] 2019-05-14 11:48
Thank you Zeffii, on what branch? on b28_prelease_master branch? or in another?

**Comment by zeffii** [comment] 2019-05-14 11:54
@javismiles   .blend files made in b2.79 are not going to work perfectly in b2.8 . Some blends will load ok, some blends will miss a few nodes: 
  - (either nodes are renamed, 
  - or classes are renamed.. 
  - or the blender API in  the new Blender version doesn't yet have certain operators

**Comment by javismiles** [comment] 2019-05-14 12:09
I got it yes Zeffii, but I started a brand new 2.8 project, from zero, and its all working great, the only thing missing for me is to join into a smooth mess the points of the point cloud I have, and for that I understand I would need Viewer Draw, in what branch is the very lastest VD_Experimental ? thank you :)

**Comment by javismiles** [comment] 2019-05-14 12:14
@zeffii  so this is a brand new 2.8 project, it all works perfect, I would just need to, if I understand correctly, replace the Viewer bMesh node, with the VD_experimental in order to try to transform the output point cloud (that now uses spherical spheres in each point) into a continuous mesh
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/nodes.jpg "Logo Title Text 1")

would that be possible? and in what branch is the latest VD_experimental? thank you :)

**Comment by zeffii** [comment] 2019-05-14 12:36
@javismiles :  
> to join into a smooth mess the points of the point cloud I have

you don't need a viewer draw if all you want is to merge all points into a single "object". there are Mesh Join nodes.

**Comment by zeffii** [comment] 2019-05-14 12:38
even the Matrix Apply node will merge all incoming geometry, when the Join option is ticked (assuming you pass the same number of matrices as verts/edge/face sets/  .. IIRC )

**Comment by zeffii** [comment] 2019-05-14 12:40
>   what branch is the latest VD_experimental   

that should be the `b28_prelease_master` (the vd changes were merged the other day)

**Comment by javismiles** [comment] 2019-05-14 12:40
thank you @zeffii, what I need is to literally unite the points to form a smooth continuous shape without gaps in between. I tried the Join option and that didnt work

**Comment by javismiles** [comment] 2019-05-14 12:41
so what I need is if I have 400 points in a point cloud with gaps in between, I need them to join each other to form a continuous sooth shape that has no holes or gaps in between, that´s the thing

**Comment by zeffii** [comment] 2019-05-14 12:47
you are trying to automatically topologize a point cloud ?  sverchok has no feature/node that will do that. (don't get me wrong, it's an interesting problem... and there are dedicated software packages that implement algorithms that do exactly that) 

there are ways to combine several sverchok nodes to get some topology into the point cloud, but it's a bit lenghty to explain.

**Comment by zeffii** [comment] 2019-05-14 12:49
what might work is  transforming the point cloud (normalizing it ) so it becomes a sphere, then applying a convex hull to mesh the outside, then transform the points back to their original state, and if you're lucky you'll have something usable.

**Comment by javismiles** [comment] 2019-05-14 12:50
@zeffii  Now I can show you exactly what I need to do, check this picture please:
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/this.jpg "Logo Title Text 1")

That´s exactly what I need to do, on the left is the point cloud I have,
on the right is what I need, to make it continuous and smooth,
how do I do that with the Sverchok nodes in 2.8? thank you so much :)

**Comment by javismiles** [comment] 2019-05-14 12:51
oh I see, so this below is not possible? what a pity, this can be done easily with matplotlib in python

![alt text](https://raw.githubusercontent.com/javismiles/torch/master/this.jpg "Logo Title Text 1")

**Comment by javismiles** [comment] 2019-05-14 12:59
the code to do that in python matplotlib is this:
  fig = plt.figure(figsize=(10,10))
  ax = fig.gca(projection='3d')
  surf = ax.plot_surface(X, Y, losses, cmap=cm.Spectral,linewidth=0, antialiased=True)
  plt.show()

but I basically need to do that within blender,
I already managed following the tutorial to import a set of .csv files that using the great Sverchok allows me to create an animation of the point cloud through time with a different frame of the point cloud on each frame in blender, and it all works perfect in blender 2.8, only thing left is to find out how to do what matplotlib does in python to transform the point cloud into the continuous surface you see above

**Comment by portnov** [comment] 2019-05-14 13:15
Most probably the "UV connector" node will do the job in your case. Probably you will need to apply "List split" before.

**Comment by vicdoval** [comment] 2019-05-14 13:15
Do you have a flat list? 
Is your point cloud regular?
If this is the case this will help:
If you have a list of 100 points and you know the surface is defined by 10 x 10 point grid you would need to split the list in 10 lists and with the "split list" node and plug the output to "UV Connection" Node to create the polygons you need.

If your list is not well sorted you can use the Vector Sort node before splinting

**Comment by zeffii** [comment] 2019-05-14 13:30
can you share the pointcloud as a gist ? @javismiles

**Comment by zeffii** [comment] 2019-05-14 13:32
that particular kind of point cloud would not be hard to topologize, it's a very specific kind of point data.

**Comment by javismiles** [comment] 2019-05-14 13:35
@zeffii  @vicdoval  @portnov thank you so much friends, its very simple, the point cloud is just a series of 
x, y, z
rows, csv file, each row has 3 numbers separated by commas, the three points are the x, y and z of the point

Here is an example point cloud file, please ignore the 4th column, it has no meaning and it will be deleted, only the first 3 columns matter (x,y,z)
https://github.com/javismiles/torch/blob/master/1.csv

thank you again :)

**Comment by javismiles** [comment] 2019-05-14 13:37
this https://github.com/javismiles/torch/blob/master/1.csv is just a fragment of the example of the tutorial Ive been following, my final .csv files in any case will be similar, x number of rows, each row 3 numbers separated by commas, X, Y and Z of each point in the point cloud,

and then 1 csv file for each frame of the animation, so the point cloud gets animated, thats the whole point,
so imagine 200 frames, 200 csv files with the 200 frames of the point cloud,
each of them 1 csv file, each with say 20x20 X, Y, Z points, 400 points in total,

the animation of the point cloud already works in 2.8

**Comment by javismiles** [comment] 2019-05-14 13:43
@zeffii @vicdoval @portnov here is a final example of the csv point cloud that I will use, this is the exact same thing I showed in the pictures above, let me know what u think, this is the point cloud, now imagine 200 csv files with same thing as this but with the shape changing in each one of course
https://github.com/javismiles/torch/blob/master/point-cloud-final-example.csv

**Comment by javismiles** [comment] 2019-05-14 13:44
as you can see, both X and Y go between -1 and 1, creating a regular grid of coordinates, and then the Z is the coordinate that creates the shape going to different heights

**Comment by zeffii** [comment] 2019-05-14 13:51
I think you might only need to generate the topology for that pointcloud once, if the only change to the cloud is the z component.. ,   actually, you might be able to use the Plane node to output faces..

**Comment by javismiles** [comment] 2019-05-14 13:56
thank you @zeffii , do you mean that here I could replace the viewer mesh node with plane node? o put it somewhere else mmm
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/nodes.jpg "example")

**Comment by zeffii** [comment] 2019-05-14 14:00
![image](https://user-images.githubusercontent.com/619340/57703957-574bc700-7661-11e9-8691-2dd7e0b94f6f.png)

**Comment by javismiles** [comment] 2019-05-14 14:01
@zeffii  WOW that´s it! that´s what I need! :D is that in 2.8? I will try to test it in 2.8 to see if I can add it to these nodes
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/nodes.jpg "example")

**Comment by zeffii** [comment] 2019-05-14 14:04
i hesitate to call the example set of points a 'point cloud'.  it's a 'surface of grid vectors without topology' .  as soon as you try to 'mesh' some random point cloud that you might obtain from a lidar scanner, this approach will instantly fail.

**Comment by zeffii** [comment] 2019-05-14 14:06
yes its b2.80  , i don't have 2.79 anymore : )   since .. november 2018 :)

**Comment by javismiles** [comment] 2019-05-14 14:07
thank you @zeffii  that´s great news because all I need is to work with what you call a surface of grid vectors yes, great point you are right this is not a complex proper point cloud yeah, Im trying now to see if I can copy what you created mixing it with my existing nodes

**Comment by javismiles** [comment] 2019-05-14 14:11
@zeffii for some reason I cannot search the nodes in my 2.8, where is that component-wise node you used? cant find it in the menus, in which section is it? and looking at this image, where would you insert that component-wise node? thank you :)

![alt text](https://raw.githubusercontent.com/javismiles/torch/master/comp.jpg "example")

**Comment by zeffii** [comment] 2019-05-14 14:12
@javismiles   it' s the Vector Math node, set to Component wise multiplication

**Comment by zeffii** [comment] 2019-05-14 14:15
not sure about the `search` thing. something may have changed in recent Blender 2.8 builds... i will have a look later.

**Comment by javismiles** [comment] 2019-05-14 14:17
@zeffii thank you, tried to imitate what you did but not working so far mmm, can you see in the picture where the error may be? :)
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/comp2.jpg "example")

**Comment by javismiles** [comment] 2019-05-14 14:24
@zeffii still nothing, zeffii could you pass me the .blend file of what you did there with my csv please please?

**Comment by javismiles** [comment] 2019-05-14 14:33
looks like I had to increase number of verts and I think now its beginning to work, its the colour gradient gradations something automatic, can it be controlled?

**Comment by javismiles** [comment] 2019-05-14 16:46
@zeffii still cant make it work like what you did, see this image, this is what I get, not what you get and also strangely all the points get tied to the 0,0,0 as well, any chance to get the blender file of your test? would help a lot, thank u so much
![alt text](https://github.com/javismiles/torch/blob/master/likethis.jpg?raw=true "example")

**Comment by javismiles** [comment] 2019-05-14 16:55
@zeffii  I see that eliminating my move, rotate, scale nodes and increasing verts, I now get this,
however its not like yours, the shape is wrong, it´s closing it and looks totally wrong,
how did you manage to make yours look so great? maybe if i see your blend file will finally understand, thank you :)
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/likethis2.jpg "example")

**Comment by javismiles** [comment] 2019-05-14 16:59
@zeffii it´s wrong because as you see in this pic it´s closing the hole in the middle connecting all the verts, how did u manage to keep the hole in the middle and also to get the colors well by the way because my colors are a mess, how are those controlled also, and yes, the verts are just connecting in the wrong ways
![alt text](https://raw.githubusercontent.com/javismiles/torch/master/likethis3.jpg "example")

**Comment by javismiles** [comment] 2019-05-14 17:04
@zeffii as you see in this image, the surface cloud is all good, but it´s linking the points in the wrong way, covering the gap in the middle, so yes I wonder how you did it to look so great
![alt text](https://github.com/javismiles/torch/blob/master/likethis4.jpg?raw=true "example")

**Comment by javismiles** [comment] 2019-05-14 17:11
@zeffii  this is the exact one that you did, and the mystery yes is how did you manage to prevent it from connecting the dots around the hole covering it, tell me please or send me the blend, now Im really curious how did you prevent that from happening :D 
![alt text](https://github.com/javismiles/torch/blob/master/likethis5.jpg?raw=true "example")

**Comment by javismiles** [comment] 2019-05-14 17:20
@zeffii  by the way, I have noticed that your VD Experimental node has the icon of a photo camera instead of an eye, mine has an eye, yours has a photo camera, and I cannot get a photo camera in there at all, so does that mean that you have a different version of VD Experimental than mine? I have the latest one as far as I know, 

anyway looking forward to knowing how you managed to avoid what happened to me, thank you :)

**Comment by zeffii** [comment] 2019-05-14 19:38
correct  the `Plane` node  , would only output the correct topology if it is told to generate the grid for the correct number of `X , Y`

the gradient there is done using a default glsl shader, kind of beyond the scope of my answers here (tonight) - i suggest you look at the pull request for `b28_prelease_master`, i show a few examples of how you could make a custom GLSL shader (just in the form of a text file))

you could also just use BMESH viewer, and give it a cycles material or whatever.

**Comment by zeffii** [comment] 2019-05-14 19:41
I think you might be `off-by-one`, in the number verts `xy`  , else i suggest just using a `gist` to give me a look at one of the frames of that csv..

mess around with the number of verts `x  y `, you'll probably figure it out.

**Comment by javismiles** [comment] 2019-05-14 19:45
thank you @zeffi, and thank you really for all you advice, so Im changing the number of x and y verts but mmm still same problem, it continues to connect the wrong vertexes, maybe i send you the .blend file then to see if you can spot the issue

**Comment by javismiles** [comment] 2019-05-14 19:47
I think there is something else, because I move the x and y vert numbers gradually from zero up and no matter what values they have it keeps on connecting the points wrong

**Comment by javismiles** [comment] 2019-05-14 19:50
@zeffi, the number of x and y vertexes is 25 and 25, what you put in yours, but I put that and I get the same issue again, there is some other problem, will share the blend with u I guess lets see

**Comment by javismiles** [comment] 2019-05-14 19:53
@zeffii it works, now it works, yes it was the number of vertexes, now it works ;) so next is to make a nicer shader, because the distribution of the colors is odd, I would like the colors to correlate with the Z, different amounts of Z have different colors in a gradient, like bands of smooth colors in different ranges of Z yeah

**Comment by javismiles** [comment] 2019-05-14 19:57
@zeffii  and yes I see how using a viewer BMesh I can assign a material,  I did with standard nodes in the past this thing of assigning certain colors to points in certain Z height values, is it possible to combine Sverchok nodes with standard ones or is this something easy to do also with sverchok? thank you ;)

**Comment by zeffii** [comment] 2019-05-14 20:08
my Sverchok is a few commits behind, this explains minor cosmetic differences.

regarding the parametric control of the cycles/eevee material, i think it is possible with the `execnode`,  i don't recall if i've ever done that or not.

**Comment by javismiles** [comment] 2019-05-14 20:52
@zeffii great news, managed to do it all, I made a shader with the shader nodes and all is cool now, than you so much for your help, my only problem now is that I can render individual frames, but when I try to render the animation blender crashes, must be a memory issue, im using an xps 15 9550 of dell, with 16GB RAM and Nvidia 2GB card but I guess it´s not enough, will upgrade laptop soon and hopefully then I will be able to render the animation, if you know of any tricks to decrease memory when rendering these let me know please ;)

![alt text](https://github.com/javismiles/torch/blob/master/yeah2.jpg?raw=true "example")

**Comment by javismiles** [comment] 2019-05-14 21:23
@zeffii , do you think that the crash that happens when I try to render the animation could be because of memory or because of an issue with sverchok and/or blender 2.8, because it´s weird that rendering single frames goes all well , and rendering an animation crashes immediately after frame 1, that´s odd, and in a powerful laptop, maybe there is some issue or bug in one of the parties involved here what do u think

**Comment by javismiles** [comment] 2019-05-14 21:33
@zeffii , rendering single frames all good at any size, etc but I´ve tried to render the animation with Eevee, with cycles, with all, at all sizes, with different parameters, and it always crashes after 1 frame, should I raise an issue with Sverchok about this? feels like an issue with it maybe, as with blender 2.8 I´ve done way more complex animations with no issue, what do u think :)

**Comment by javismiles** [comment] 2019-05-14 21:45
@zeffii , cause my initial reactions to the crashes when rendering animations were to blame memory issues but today after I solved the other issues I tried all sorts of different combinations and now I´m pretty convinced that it´s not a memory issue but a code issue, just not sure if its a code issue within Sverchok or in the interaction between Sverchok and blender 2.8, etc, 
because rendering single frames works at all times in all settings, and rendering animations fails at all times after frame 1 and in all sorts of settings,
now I´m totally conscious that sverchok for blender 2.8 is still in development, but if I can help by reporting to the team this issue and helping to test it or etc let me know, I am not a super big fan of Sverchok, the best Blender add-on I have ever seen! amazing! :D so happy to help if i can :)
thank you again for your help ;)

**Comment by zeffii** [comment] 2019-05-14 21:49
rendering animations is not something i've tested..  
i would avoid updated the material on everyframe ( just as an experiment )

if you are outputting to BMesh Viewer then that's probably offtopic on this thread. It's OK to start a new thread about b28 crash during animation. (preferably with a downloadable .zip so i can just load and observe without having to do a setup first )

**Comment by zeffii** [comment] 2019-05-14 21:54
it's not impossible that the most recent blender build has a bug, it is however not as likely as sverchok just doing something stupid (like triggering nodetree update event that sprials into an infinite loop upon frame change)

not likely a memory issue, especially if you can't make it ' not crash ' by passing it a simpler animation driven by sverchok.

**Comment by javismiles** [comment] 2019-05-14 21:56
@zeffii thank you, so maybe if that part is not tested maybe its somewhere in there the issue, how could I test not to update the material on every keyframe? how is that done? will also look following your advice to open a new thread on b28 crash during animation

**Comment by zeffii** [comment] 2019-05-14 21:57
just don't reference the material from the sverchok node tree. that way sverchok is not updating the material, and that update event in-turn will not cause sverchok to update (and send it down the spiral )

**Comment by javismiles** [comment] 2019-05-14 22:00
@zeffii yes, I just did this test
- I deleted the material from the sverchok bmesh node
- I also disconnected the material from the normal shading nodes

so the shape renders totally black

and same crash happens and again exactly after first frame like always, same issue yeah, we gotta try something else

**Comment by javismiles** [comment] 2019-05-14 22:02
@zeffii , yes now I got useful info!!
- I delete the Exec Node Mod and no crash!
but now I dont get the update each frame of the new shape

**Comment by javismiles** [comment] 2019-05-14 22:04
The exec node Mod executes these lines
csvdata=V1[0]
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text=csvdata

which at each frame change the csv data to the next frame and show the next shape that corresponds to the next frame, without that the animation makes no sense

but yes deleting that node the crash didnt happen

**Comment by javismiles** [comment] 2019-05-14 22:09
@zeffii , wait no, I repeated the test eliminating it and now it still crashes,
so its not that,

**Comment by javismiles** [comment] 2019-05-14 22:22
@zeffii  I got new info!
I replaced the BMesh node back to the VD Experimental node and no crash because it renders nothing then, because the BMesh renders continuously but the VD Experimental renders when you bake it and that´s fixed, it won´t animate
so there seems to be an issue with the BMesh node I would say at the moment, 

seems like VD Experimental when baked doesnt crash but doesnt animate either,
BMesh animates but crashes after 1st frame, so I would say issue with BMesh

how do I disconnect again change of material after each frame? I think i didnt do that correctly earlier, let me know please

**Comment by javismiles** [comment] 2019-05-14 22:25
@zeffii more useful info

BMesh Node
- When disabling the LIVE button, no crash when rendering animation but no changes between frames, shape remains static of course!
- When enabling LIVE button, Crash again when animating

obviously there is an issue in the BMesh node when it changes between frames

**Comment by javismiles** [comment] 2019-05-14 22:27
@zeffii new test
- I selected the BMesh object and deleted its material completely, Crash still happens after 1,2 frames
seems clear an issue with BMesh node when changing from one frame to another within an animation

**Comment by javismiles** [comment] 2019-05-14 22:29
@zeffii  hopefully we can find where the issue is and fix it because BMesh I see it now as essential allowing me to do shading and render live changes of the shape each frame,  VD Experimental is not useful for this as it will render when baked and remain static so BMesh is the way to do this

**Comment by javismiles** [comment] 2019-05-14 22:40
opened issue at https://github.com/nortikin/sverchok/issues/2417

**Closed** 2019-08-09 13:18 UTC
Labels: SV for b2.8
