### ISSUE TITLE
"Triangulate Mesh" node turn red after hooking up the output node

### ISSUE THREAD

**Issue by sfire** [nortikin/sverchok#741] opened 2015-11-21 08:31 UTC
Hi nortikin,
I'm learning sv recently, it's really an awesome addon. But I encounter one problem when I follow the manual to learn the usage of "Triangulate Mesh" node: 
https://cloud.githubusercontent.com/assets/284644/6314915/4fb6a9c0-ba12-11e4-9600-4d08a5d67f86.png
After I hooked up the nodes, the "Triangulate Mesh" node turn red and I can't get any output even with the  "stethoscope" node. You can find the Screenshots below:
![sv_error](https://cloud.githubusercontent.com/assets/5409756/11317521/424e905a-906c-11e5-9099-dfaf8abe2d2c.jpg)
I tried to restart Blender to solve this problem, but it just failed again and again. And other users in our community also found the same problem. So I think there might be an bug here.
My Blender version is 2.76b, and sverhcok version is 0.5.3.8.
I hope this to be solved asap, and thanks again for your efforts.

**Comment by ly29** [comment] 2015-11-21 09:18
A node is marked red is because it fails, that halts the execution of the node graph.

Yeah probably a bug in triangulate mesh, perhaps caused by the form of output from box. 
@portnov perhaps could take a look, otherwise I will try later today.

**Comment by ly29** [comment] 2015-11-21 16:40
The bug appears to be somewhere in the decorators created by @portnov, I do not want go through them right now. They look very promising for the the approach of sverchok. Have they been tested?

Other things seems more temping to me... 

Since @nortikin merged this I think it falls on him.

```
data_structure.py", line 330, in <listcomp>
    results = [list(method(node, *d)) for d in zip(*data)]
Node Triangulate had exception real_process() takes 1 positional argument but 5 were given
```

**Comment by nortikin** [comment] 2015-11-22 02:19
yeah, tomorrow will look. Portnov... Ok i not tested well this node.

**Comment by nortikin** [comment] 2015-11-22 12:47
What do you mean hooking up?

**Comment by sfire** [comment] 2015-11-22 12:52
![screenshot](https://cloud.githubusercontent.com/assets/5409756/11323874/d11d63ee-915a-11e5-988f-27c38b11be1b.gif)
I mean connect it like this....

**Comment by nortikin** [comment] 2015-11-22 13:02
@sfire ok, suceed in recreating bug, go on

**Comment by nortikin** [comment] 2015-11-22 13:03
strange, in other branch it worked well. will compare

**Comment by nortikin** [comment] 2015-11-22 13:08
https://github.com/nortikin/sverchok/blob/interpol_np/nodes/modifier_change/triangulate.py this works...

**Comment by portnov** [comment] 2015-11-22 15:22
Yes, the problem is somewhere in the decorators. In order to have working master, i'd suggest rollback the last refactoring of triangulate.py. I'll investigate the problem - i hope, during the next week.

**Comment by zeffii** [comment] 2015-11-27 15:33
https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/triangulate.py references the with_bmesh decorator
`from sverchok.utils.sv_bmesh_utils import with_bmesh`  but it doesn't exist

**Comment by zeffii** [comment] 2015-11-27 15:34
```python
def with_bmesh(method):
    '''Decorator for methods which can work with BMesh.
    Usage:
        @with_bmesh
        def do_something(self, bm, other_args):
            ...
            return new_bmesh, other_results
        This will be transformed to method like
        def do_something(self, verts, edges, faces, other_args):
            bm = bmesh_from_pydata(..)
            ...
            return pydata_from_bmesh(bm), other_results
    '''

    def real_process(*args):
        if len(args) == 2 and isinstance(args[1], bmesh.types.BMesh):
            bm = args[1]
            other_args = []
        elif len(args) >= 4 and all([isinstance(arg, list) for arg in args[1:4]]):
            bm = bmesh_from_pydata(*args[1:4])
            other_args = args[4:]
        else:
            raise TypeError("{} must be called with one BMesh or with at least 3 lists (verts, edges, faces); but called with {}".format(method.__name__, list(map(type, args))))

        method_result = method(args[0], bm, *other_args)
        if method_result is None:
            return None
        elif isinstance(method_result, bmesh.types.BMesh):
            result = pydata_from_bmesh(method_result)
        elif isinstance(method_result, (list,tuple)) and len(method_result) >= 1 and isinstance(method_result[0], bmesh.types.BMesh):
            result_bmesh = pydata_from_bmesh(method_result[0])
            result_other = method_result[1:]
            result = list(result_bmesh) + list(result_other)
            if isinstance(method_result, tuple):
                result = tuple(result)
        else:
            raise ValueError("{} returned unexpected type of result: {}".format(method.__name__, type(method_result)))
        bm.free()

        return result

    real_process.__name__ = method.__name__
    real_process.__doc__ = method.__doc__
    return real_process
```

**Comment by zeffii** [comment] 2015-11-27 15:35
lets see what happens when qe plug that in :)

**Comment by zeffii** [comment] 2015-11-27 15:38
from data_structure we are missing ` checking_links, iterate_process, Input, Output, match_inputs, std_links_processing `

**Comment by zeffii** [comment] 2015-11-27 15:39
to compile this list:

`data_structure.py` misses 
> checking_links, iterate_process, Input, Output, match_inputs, std_links_processing

`sv_bmesh_utils.py` misses
>  with_bmesh

**Comment by zeffii** [comment] 2015-11-27 15:42
I'll make a branch to see if I can get it working - this bug annoys me.

**Comment by zeffii** [comment] 2015-11-27 17:13
reverted `triangulate.py` until someone fixes it.
https://github.com/nortikin/sverchok/commit/3c1404a9cf54a12ac8c7aabf20b8092cca343d48

**Comment by nortikin** [comment] 2015-11-28 13:19
thanks, zeffii. it seems Ilia Protnov has no time

**Comment by zeffii** [comment] 2015-11-28 14:34
maybe it's a simple one line fix, to do with passing positional arguments and keyword arguments,  @portnov probably fixes it in 5 minutes..or less : )  it took me an hour to conclude that I should have read the pullrequest code more definitively 8 months ago :)

**Comment by ly29** [comment] 2015-11-28 14:44
Many layers in that code. I understand decoraters, but they aren't really part of my vocabulary so to speak.

**Comment by zeffii** [comment] 2015-11-28 17:50
@portnov  :) this is very cool code btw. and i'm in two minds about it. If you recall I also wrote a limited dissolve bmesh node that was quite a bit shorter than the equivalent _longform_ methods without the decorators. It really made writing the node less mechanistic and let me focus on just the bm bit. You also proved that at soon as that is simplified, making a massively multipurpose bmesh.ops node is much more succinct. These are all good things 

The downside to the chained decorators is that it really isn't easy to follow the backend. I guess we hope to write this stuff once and never look back at it, but in practice...i don't know, I like to be able to follow the code without getting a headache. Maybe this shows a weakness of mine, or maybe this shows that the code is at a sharp point which approaches being too convoluted for no real reason.

I think i'd rather see this less convoluted in the back end, perhaps even refactored further.

You have a line like this 

 ```python
match_inputs(matcher, node.input_descriptors, node.output_descriptors)(process)
``` 
why not just 
```python
match_inputs(matcher, node)(process)
```
and deal with `node.input_descriptors, node.output_descriptors` in whatever function you're calling.

**Comment by ly29** [comment] 2015-11-28 17:58
Yeah it is super cool way to deal with the messiness of sverchok.

**Comment by zeffii** [comment] 2015-11-30 09:22
is fixed, but waiting on @portnov to supply the decorator alternative

**Closed by zeffii** 2015-11-30 09:22 UTC
Labels: bug
