### ISSUE TITLE
Cleanup of keyboard shortcut on sverchok disable (0.5.2.0)

### ISSUE THREAD

**Issue by shiprex** [nortikin/sverchok#692] opened 2015-07-02 00:39 UTC
I really, really enjoy working with sverchok :)
Small bug:
If I enable sverchok, save user settings, then disable sverchok and save user settings, I see
![image](https://cloud.githubusercontent.com/assets/806490/8467763/cc2043ca-2017-11e5-9800-ae4526d3afe3.png)
appearing in the console. It looks like it leaves behind a keyboard shortcut?

**Comment by zeffii** [comment] 2015-07-02 13:58
correct, it doesn't remove the reference to the operator - best to untick or delete the keymap entry manually until I or someone else fixes it. I'm not at a computer suitable for development at the moment, so it might not be me..

**Comment by zeffii** [comment] 2015-07-02 14:00
see where the issue is in the code:
https://github.com/nortikin/sverchok/blob/master/utils/text_editor_plugins.py#L353-L388

in `register()` there's an 'add_keymap' , but there's counterpart in the `unregister()`.

**Comment by zeffii** [comment] 2015-07-02 14:13
It would need something like:

```python
def remove_keymaps():

    wm = bpy.context.window_manager
    text_editor = wm.keyconfigs.user.keymaps.get('Text')

    keymaps = text_editor.keymap_items
    this_km = keymaps.get("text.noderefresh_from_texteditor")
    keymaps.remove(this_km)
```

the sv_plug callmenu, the second shortcut is a little trickier, but i'll fix it asap

```
        ''' SHORTCUT 2 Show svplugMenu Ctrl + I (no text selected) '''
        new_shortcut = keymaps.new('wm.call_menu', 'I', 'PRESS', ctrl=1, head=0)
        new_shortcut.properties.name = 'TEXT_MT_svplug_menu'
```

**Comment by zeffii** [comment] 2015-07-02 16:37
It would need something like:

```python
def remove_keymaps():

    wm = bpy.context.window_manager
    text_editor = wm.keyconfigs.user.keymaps.get('Text')

    keymaps = text_editor.keymap_items

    # remove shortcut 1
    this_km = keymaps.get("text.noderefresh_from_texteditor")
    keymaps.remove(this_km)

    # remove shortcut 2
    this_km = None
    for k, v in keymaps.items():
        if k == 'wm.call_menu' and v.properties.name == 'TEXT_MT_svplug_menu':
            this_km = v
            break
    if this_km:
        keymaps.remove(this_km)
    
```

**Comment by zeffii** [comment] 2015-07-03 07:05
The above may need to have some `try / except` because it's not uncommon for the keymap structure for the 'Text' window simply _not to exist_ or for a specific keymap inside a structure to be gone already.

**Comment by nortikin** [comment] 2015-07-03 09:19
you have not deactivate Sverchok if you like it ))

**Comment by zeffii** [comment] 2015-07-09 07:13
I've added the keymap removal function, and committed to master. The error will still show 2 times in the console, but it appears to be a bug in Blender itself where the UI possibly still references the keymap menu items until a global blender app refresh is triggered or something. I don't know, this does appear all i can do.

**Closed** 2015-07-09 07:13 UTC
Labels: bug

**Comment by nortikin** [comment] 2015-07-09 09:04
thanks, zeffii
