### ISSUE TITLE
Problem with vector interpolation MK3

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1726] opened 2017-06-24 08:15 UTC
Tangent socket do not work in line mode. I can not recreate this problem in new file.

![interpolation](https://user-images.githubusercontent.com/28003269/27506954-0dabaea8-58d6-11e7-8e00-0518dd2bdf59.gif)
https://gist.github.com/14197d16fa643ec677ca3596a1fdd46f
[Problem.zip](https://github.com/nortikin/sverchok/files/1099507/Problem.zip)

**Comment by zeffii** [comment] 2017-06-24 08:24
i'll take a look

**Comment by zeffii** [comment] 2017-06-24 08:29
@Durman  please in future use the IO Panels Export "Save as Zip" option, to make zips for reporting errors. That operation will copy the link to the zip it created on your HD, into your clipboard so you can find it easy for  dragging into the issue.

**Comment by zeffii** [comment] 2017-06-24 08:40
i'm not able to load that zip in any form, i think possible something in the binary has become corrupt?
I also can't load the `gist`. maybe it's a big nodetree with lots of processing? my slow computer with 2gb of ram can't load it.

**Comment by zeffii** [comment] 2017-06-24 10:21
- check the terminal / command prompt for silent messages... 
- temporarily disconnect other nodes from the output of the Vector Interpolator

**Comment by Durman** [comment] 2017-06-24 10:25
I deleted all now.)
https://gist.github.com/b7492d0de4849812fda7bec9be57d783
[2017_06_24_10_24.zip](https://github.com/nortikin/sverchok/files/1099587/2017_06_24_10_24.zip)

**Comment by zeffii** [comment] 2017-06-24 10:31
i don't know Durham. sorry : /   If there's a corruption anywhere it might help to remove the node, and add it back from t he menu.

**Comment by Durman** [comment] 2017-06-24 10:40
I tried to do it but it did not help. Sometimes I reload Blender and node interpolation begin to work until next Blender session.

**Comment by zeffii** [comment] 2017-06-24 11:54
what about when you hit F8 ?

**Comment by Durman** [comment] 2017-06-24 12:04
Nothing happens :/

**Comment by Durman** [comment] 2017-06-24 12:08
Can not you to see problem in the zip file? Try to open several times. It sometimes works, sometimes no.

**Comment by Durman** [comment] 2017-06-24 12:33
Interesting thing happens with my file. I have not no one frame info node here. I noticed that large node tree have uncatchable bugs.

![bug](https://user-images.githubusercontent.com/28003269/27508618-2b6e3b30-58fa-11e7-9d6b-052a058ed321.gif)

**Comment by zeffii** [comment] 2017-06-24 12:39
i can only import the gist if i first switch off the Processing (P) in the layout side panel, as soon as i hit P blender crashes. But at least I can open it now,, which means there is a chance I will find the cause.

**Comment by zeffii** [comment] 2017-06-24 12:40
extrude region is a very slow node.

**Comment by zeffii** [comment] 2017-06-24 12:48
just looking through the tree, I think you should do the sorting first, then the selection with list item?
![image](https://user-images.githubusercontent.com/619340/27508740-2071afc2-58ec-11e7-8235-dc543ff1d86f.png)

**Comment by zeffii** [comment] 2017-06-24 12:50
now.. I can definitely add a try/except to the Linear Mode in VectorInterpolateMK3, but I don't think the problem is inside that node.

btw, i suggest not using extrude region jst to get thickness in a plane, use 'Solidify'.

**Comment by zeffii** [comment] 2017-06-24 12:52
and some logic issue you need to address..

![image](https://user-images.githubusercontent.com/619340/27508755-af7df1a8-58ec-11e7-9e7c-55fe92d8898d.png)

**Comment by Durman** [comment] 2017-06-24 15:36
When check box fill section are enabled it receive polygons, is not it?)

**Comment by Durman** [comment] 2017-06-24 15:48
I thought that topo sort for profile node can not work with objects, for this i used two nodes and cut data on two objects. But now I see that I have 3 objects and topo sort node below works fine with objects.)) I will remake this part.

**Comment by Durman** [comment] 2017-06-24 16:06
I found sum not logical things in my tree. I fixed it but problem remained. I think this works little more faster.
https://gist.github.com/271b3a4a6773a6778f008e36e0f55e28

**Comment by Durman** [comment] 2017-06-24 16:25
I found strange work of topo sort for profile. It likes to play with output data.))

![bug sort](https://user-images.githubusercontent.com/28003269/27510095-14ae353c-591b-11e7-890e-79350a40ddcb.gif)
https://gist.github.com/f4d3a45102ed9e0d71be7f5c80d33543

**Comment by zeffii** [comment] 2017-06-24 19:04
@Durman  don't be afraid to look at the source of the `topo_sort_for_profile` script. I think once a profile is a loop, there's no sane way to say "this vertex is loop start" (not automatic anyway)

**Comment by zeffii** [comment] 2017-06-24 19:06
i wouldn't be suprised if the vertex order is different when passed into `in_verts` on that node btw..

**Comment by zeffii** [comment] 2017-06-24 20:10
![image](https://user-images.githubusercontent.com/619340/27511644-fa98feac-5929-11e7-842b-c96a98b126f3.png)

**Comment by zeffii** [comment] 2017-06-24 20:19
Additionally the `Fill Section` or `Alt+F/F` toggles on Cross Section that seems to do something wrong.. (unticking them works for me)

Polygons to Edges node is not needed here.

**Comment by Durman** [comment] 2017-06-25 06:57
Hip hip hurray. Now I think it is clearly that Cross section node have bug with sort in time. My node tree a little bit closer to normal working.

![bug cross](https://user-images.githubusercontent.com/28003269/27514198-1baa3c0e-5994-11e7-9000-747e464b7fa5.gif)

https://gist.github.com/0d70923e5853c766153b96f0adb9dbd9

**Comment by zeffii** [comment] 2017-06-25 07:27
Cross Section uses a regular bpy.ops ( Yikes! )
https://github.com/nortikin/sverchok/blob/master/nodes/modifier_make/cross_section.py

I would use the Bisect Node instead, i think it's equivalent in features. (but also will not guarantee output consitency with edge/face indices).

tough problem.  but let's agree that "Vector Interpolation Mk3" is not a factor here.

**Comment by zeffii** [comment] 2017-06-25 07:32
probably the face indices are not stable going into the Cross Section node either.. use the IndexViewer and start as far upstream as you can and gradually work your way towards a node that you suspect introduces unstable sorting.

**Comment by zeffii** [comment] 2017-06-25 07:37
the change in sorting comes from:
![image](https://user-images.githubusercontent.com/619340/27514402-d628c39e-5989-11e7-8278-0d3ee73c251a.png)

**Comment by zeffii** [comment] 2017-06-25 07:40
![image](https://user-images.githubusercontent.com/619340/27514415-53c68778-598a-11e7-9bb6-b519c1167de6.png)

**Comment by zeffii** [comment] 2017-06-25 07:41
I might make a `Solidify Lite Node`, that doesn't use bmesh operators.

**Comment by zeffii** [comment] 2017-06-25 07:45
There is no sensible way to force consistency in the face / edge indexing of the current solidfy node. I can take a lot of code from the `Inset Specials` node and make a `Solidify Lite` from it.

**Comment by zeffii** [comment] 2017-06-25 08:21
Closing to confirm that the problem is not with the `Vector Interpolation mk3` node.  Will get a [`Solidify SV`](https://github.com/nortikin/sverchok/issues/1727) node ready some time soon.

**Closed by zeffii** 2017-06-25 08:21 UTC
Labels: invalid, unconfirmed

**Comment by zeffii** [comment] 2017-06-25 08:40
Also consider:
![image](https://user-images.githubusercontent.com/619340/27514708-bd85309e-5992-11e7-94f6-1ff3c5e21d10.png)

**Comment by Durman** [comment] 2017-06-25 09:02
Thanks, yes interpolation node works normally now. I think may be problem was in something that I made wrong. In future i will use not only box but something more interesting for plan my building so I need tool like extrude.

**Comment by Durman** [comment] 2017-06-27 09:13
The problem exists.

![bug interpolation](https://user-images.githubusercontent.com/28003269/27579883-12353f28-5b3a-11e7-94a0-a8bdcb6779bd.gif)

**Comment by zeffii** [comment] 2017-06-27 09:33
This is the correct way to do a bug report. Use as few nodes as possible. Indeed, that looks strange. unfortunately i am not able to reproduce this. Which version of Python are you using (the one supplied by Blender.. or are you running your own system python? )

**Comment by zeffii** [comment] 2017-06-27 09:37
are those the only 3 nodes in the Tree?

**Comment by zeffii** [comment] 2017-06-27 09:43
Could you have multiple sverchok installations / folders? Remove All  (manually if you need) and then install a fresh download.

**Comment by zeffii** [comment] 2017-06-28 14:32
```python
import bpy
import sverchok

file_location = sverchok.nodes.vector.interpolation_mk3.__file__
bpy.ops.text.open (filepath=file_location)
```

When you encounter that situation again, can you paste the above snippet into the TextEditor and run it?Then copy the content into a post here. I'd like to see the code is the most up to date.

**Comment by Durman** [comment] 2017-06-28 14:48
Did it.
[interpolation_mk3.TXT](https://github.com/nortikin/sverchok/files/1109096/interpolation_mk3.TXT)

**Comment by zeffii** [comment] 2017-06-28 16:40
you didn't answer my other two questions above it.

**Comment by zeffii** [comment] 2017-06-28 16:43
what about zipping the blend of that file in question, and linking it here?

**Comment by Durman** [comment] 2017-06-28 17:37
Your questions is difficult.) I suggest that Blender uses itself Python. I use only three nodes in the tree. I am not found where Sverchek keep its folders.

[tangent_2017_06_28_17_36.zip](https://github.com/nortikin/sverchok/files/1109646/tangent_2017_06_28_17_36.zip)

**Comment by zeffii** [comment] 2017-06-28 19:48
> I am not found where Sverchek keep its folders.

do a windows search for "sverchok" . and remove all folders called "sverchok" and "sverchok-master". then reinstall.

**Comment by zeffii** [comment] 2017-06-28 20:11
I don't see anything obvious in the code that might lead to no output given the stated input. Additionally I can't reproduce, this makes tracking a bug hard.
