### ISSUE TITLE
Exec Node Mod node to reload on each frame a different file

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#3184] opened 2020-05-09 07:13 UTC
good day friends
I am moving stuff I did with Sverchok from old version of Sverchok and 2.80 to the latest 2.82 and latest version of Sverchok. All is working well, except one thing. 
I use an Exec node with these lines

```python
csvdata=V1[0]
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text=csvdata
```
to change the csv text file Im processing on each frame to show a different shape.

This works perfect in old version but in new version the shape is not changing. Using the Stethoscope I can see that I am indeed selecting in each frame a different csv file. Somehow those lines of the exec node don´t seem to be reloading the new one. Is there anything I should do differently in the new version for this to work?

thank you :)

**Comment by javismiles** [comment] 2020-05-09 07:18
by the way I installed the latest sverchok version from this link in the repo, is this the correct link?
https://github.com/nortikin/sverchok/archive/master.zip

**Comment by javismiles** [comment] 2020-05-09 07:27
I notice that if I hardcode:
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text="s110.csv"
then in the Text In+ node I can see that the file changed to s110.csv,
so that line is not the problem

maybe this line is:
csvdata=V1[0]

**Comment by javismiles** [comment] 2020-05-09 07:30
puzzling because the output of the Object ID Set MK2 node
sent to the stetoscope shows the correct change with s001.csv, s002.csv, etc as I change the frames.
The very same output goes to the Exec Node Mod node, and I can see the
V1 becoming V1.1  showing that 1 input went in,
but for some reason selecting that input with V1[0]
is not providing apparently the same s001.csv etc that I see in the stetoscope

**Comment by javismiles** [comment] 2020-05-09 07:35
oh, even though I have selected the "Animate Node" option (its on), only if I click on the option on its right (update node), will the lines execute ok when moving the frame position, 
very odd, not like it used to work in previous versions; also the shape is not updating even when the text file changes in Text In+

**Comment by javismiles** [comment] 2020-05-09 07:42
ok here you can see the whole thing in this image:
https://volandino.com/tmp/sverchok1.jpg

with the very same nodes, in 2.80 and older version of sverchok, when moving position in timeline, the shape would be re-rendered at each frame with the data of a different csv file

but in 2.82 with latest sverchok version, the text file is not getting updated in Text In+ and even if I force it to change, the shape doesnt get re-rendered anyway

I really need to make this work in the latest version, please help :) thank you :)

**Comment by zeffii** [comment] 2020-05-09 09:00
The bad news:

Due to changes in Blender API last month, some nodes (notably Text In and Out) have been essentially broken when Sverchok is loaded in newer versions of Blender.

I will be pushing a few modifications to those nodes shortly, so they can at least work and be useful.

**Comment by javismiles** [comment] 2020-05-09 09:01
@zeffii wow thats really bad news, thank you for letting me know, 
I cross fingers, I will have to stop my project then until those nodes are fixed; once you push those modifications, what I showed you in my image will work as it worked in my previous setup? thank you again

**Comment by zeffii** [comment] 2020-05-09 09:05
You can try in this branch `https://github.com/nortikin/sverchok/pull/3148`

but let me read what you wrote above, it may not be all doom-and-gloom

**Comment by zeffii** [comment] 2020-05-09 09:17
now. observe
![image](https://user-images.githubusercontent.com/619340/81469668-9ebe5200-91e6-11ea-87f8-29296a2bb9cc.png)

**Comment by zeffii** [comment] 2020-05-09 09:26
now with some annotations

![image](https://user-images.githubusercontent.com/619340/81469717-e80ea180-91e6-11ea-94a1-4dc1680e6ca6.png)

of which.. the execnode can be smarter i have no zero padding to convert framenumber to filenumber..

```
csvdata = f"file_0{V1[0][0]}.csv"
print(csvdata)
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = csvdata
```
but you can use fstring formatting.. so.. if all your files have padding zeros, or are offset some amount compared the the "frame number". then you do some math.

```
index = 8
offset = 0
computed_index = index + offset
computed_filename = f"file_{computed_index:03}.csv"
print(computed_filename)
>>> "file_008.csv"
```

remember i'm doing V1[0][0] because frame number comes in like `[[number]]`, so must be looked up using  `V1[0][0]`

**Comment by zeffii** [comment] 2020-05-09 09:28
additionally, there's a not so well known mode in the execution model, which lets you execute various subtrees of the graph in order of their lowest node.x or y location.

**Comment by zeffii** [comment] 2020-05-09 09:31
i think you'll be fine if you use the suggested method in execnode

**Comment by javismiles** [comment] 2020-05-09 09:35
@zeffii 

wow ok lets try this, look my files are like this:
s000.csv
s001.csv
....
s010.csv
s011.csv
....
s099.csv
...
s100.csv
s101.csv
etc

so will this work with mine?

csvdata = f"s{V1[0][0]}.csv"
print(csvdata)
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = csvdata

**Comment by javismiles** [comment] 2020-05-09 09:37
@zeffii 
nope, I tried with csvdata = f"s{V1[0][0]}.csv", 
but no changes

**Comment by zeffii** [comment] 2020-05-09 09:37
blender starts with frame 1 so
given frame = 8, you want to read s007.csv  ,then
```
index = 8
offset = -1
computed_index = index + offset
computed_filename = f"s{computed_index:03}.csv"
print(computed_filename)
```

**Comment by javismiles** [comment] 2020-05-09 09:38
@zeffii yes but if must all be related to the current frame in timeline also,therefore to whats coming in V1[0][0], how would it be then

**Comment by zeffii** [comment] 2020-05-09 09:39
or rather..
```python
index = V1[0][0]
offset = -1
computed_index = index + offset
computed_filename = f"s{computed_index:03}.csv"
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = computed_filename
```

**Comment by javismiles** [comment] 2020-05-09 09:39
do you mean like this

index = V1[0][0]
offset = -1
computed_index = index + offset
computed_filename = f"s{computed_index:03}.csv"
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text=computed_filename

**Comment by javismiles** [comment] 2020-05-09 09:40
oki im gonna try this right now

index = V1[0][0]
offset = -1
computed_index = index + offset
computed_filename = f"s{computed_index:03}.csv"
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = computed_filename

**Comment by zeffii** [comment] 2020-05-09 09:40
yeah, that gets the correct filename for any given frame input.

*fingers crossed*

**Comment by javismiles** [comment] 2020-05-09 09:41
@zeffii nop doesnt work , the node turns red already in third line:
computed_index = index + offset

that line gives trouble already

**Comment by javismiles** [comment] 2020-05-09 09:42
@zeffii Stethoscope by the way shows the correct names changing when moving the timeline, so all is good at the Stethoscope text output

**Comment by javismiles** [comment] 2020-05-09 09:43
@zeffii given that both Stetoscope and exec node are receiving the same input, and the Sthetoscope shows the file name nicely, are we sure that V1 contains the index and not the name?

**Comment by zeffii** [comment] 2020-05-09 09:44
so.. if it's red.. lets see the error 
![image](https://user-images.githubusercontent.com/619340/81470270-4d17c680-91ea-11ea-8848-70316d78106e.png)


are you outputting the filename in ExecNode ?

**Comment by javismiles** [comment] 2020-05-09 09:46
@zeffii im back, can I output the filename in Execnode? just putting a print?

**Comment by javismiles** [comment] 2020-05-09 09:47
@zeffii if I put print(index) , where does the output appear of that in the execnode?

**Comment by zeffii** [comment] 2020-05-09 09:48
no.. the print statement prints to the console/terminal , the append statement at the end in my example, then the execnode adds `csvdata` (the string) to the output..

**Comment by javismiles** [comment] 2020-05-09 09:48
@zeffii 

got the error in tree:
can only concatenate str not "int") to str

**Comment by zeffii** [comment] 2020-05-09 09:49
append , in ExecNode is a shorthand  /a convenience alias for out.append
```
out = []
append = out.append
```

**Comment by zeffii** [comment] 2020-05-09 09:50
show me a screenshot of the ExecNode, and the node going into it.

**Comment by javismiles** [comment] 2020-05-09 09:50
@zeffii thank you, I forgot how do I start blender to get the console out?

I missed this out thing, do I have to add this everytime I print something?
out = []
append = out.append

**Comment by zeffii** [comment] 2020-05-09 09:50
i have to go.

**Comment by javismiles** [comment] 2020-05-09 09:51
@zeffii in any case the error is that it cannot concatenate integers, only strings,
thank you Zeffi, will keep trying in here

**Comment by javismiles** [comment] 2020-05-09 09:52
@zeffii casting to string with str() solves that error, lets see now next lines

**Comment by javismiles** [comment] 2020-05-09 09:54
@zeffii ok I got the system console out in blender, now I can see the outputs of the prints

**Comment by javismiles** [comment] 2020-05-09 09:55
@zeffii so doing a print of index = V1[0],
what I find is that V1[0] contains the entire filename in perfect state, its perfect

so then no idea why it doesnt work

**Comment by javismiles** [comment] 2020-05-09 09:57
@zeffii 
basically nothing is wrong in the exec node, this line 
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = V1[0]
is assigning the correct thing, and the blender console shows that when I move the timeline, it assigns the correct csv file, it changes every time, so all is good with the exec node

something else is broken then mmm

**Comment by javismiles** [comment] 2020-05-09 09:59
@zeffii 
wow it now works! :)
when passing it to be a single line
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = V1[0]

and reconnecting the text in+

now it works!

**Comment by javismiles** [comment] 2020-05-09 10:00
@zeffii wonderful
thank you so much for your help @zeffii 
I also learnt new things about debugging the errors in the nodes which is great :)

ok this is awesome, now the system works with latest sverchok and blender it seems

now lets see if you can help me when you have time with the other issue I open about showing arbitrary 3d shapes, I have added new info there today, thank you :)

**Comment by zeffii** [comment] 2020-05-09 11:38
well, if `V1[0]` already contains the correct filename, just assign it directly .. why not :)

but why you should have to do that on one line is not clear to me.
```python
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = V1[0]
```
and
```python
csvfile = V1[0]
bpy.data.node_groups["CSV_TO_MESH"].nodes["Text in+"].text = csvfile
```
should be functionally equivalent,  because it works here..  (As i showed in my example ).

**Comment by zeffii** [comment] 2020-05-09 11:41
also.. your stethoscope  is outputting super small text..  in sverchok, preferences -> Node Defaults you can change the render size.

![image](https://user-images.githubusercontent.com/619340/81472836-b273b380-91fa-11ea-9a4a-e72173f103c2.png)

i don't know why stethoschope isn't picking up the correct DPI/scale for you.  can you show a screenshot of your preferences panel (like i show here)

**Comment by javismiles** [comment] 2020-05-09 11:49
@zeffii wow this is awesome, the .. in sverchok, preferences -> Node Defaults , now I can see the text in big! thank you, this really helped with that :)

**Comment by javismiles** [comment] 2020-05-09 11:50
@zeffii if it helps I have a dell xps 15 7590 with a 4k screen, maybe its because of the 4k resolution?

**Comment by zeffii** [comment] 2020-05-09 11:52
sverchok tries to automatically get the dpi info from Blender. it's obviously failing you. not much i can do there, unless you donate the same computer to me (haha)

**Comment by javismiles** [comment] 2020-05-09 11:54
@zeffii thanks to your solution with the blender preferences now its perfect, I can finally see the text well, its awesome ;)

**Comment by zeffii** [comment] 2020-05-09 12:40
closing as resolved, and can't reproduce the requirement for doing it in one line.

**Closed by zeffii** 2020-05-09 12:40 UTC
