### ISSUE TITLE
matrix have to understand vertex as location

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#1060] opened 2016-12-27 08:15 UTC
Where to write this understanding?
whan you plug vertex to any matrix socket, it have to be flatten in levels in one object and making matrices for every vertex. In .sv_get() function.
Can we?

**Comment by nortikin** [comment] 2016-12-27 08:43
https://gist.github.com/nortikin/10ead76843211aaf49d5d78a933e3592
trying to do

**Comment by zeffii** [comment] 2016-12-27 08:46
completely agree! makes sense to do the conversion in the socket

**Comment by zeffii** [comment] 2016-12-31 11:50
i was thinking the following..
```python
locations = []

def get_all(a_list):
    for item in a_list:
        if isinstance(item, (tuple, list)) and len(item)==3 and isinstance(item[0], (float, int)):
            location.append(matrix_from_location(item))
        else:
            get_all(item)
````

**Comment by zeffii** [comment] 2016-12-31 12:06
this would generate a flat list of _matrices_.   i don't think we generally use nested matrix lists ,  at least i've not used any lately..

**Comment by zeffii** [comment] 2017-01-01 01:48
something like this .. but it doesn't work yet :)

https://github.com/nortikin/sverchok/tree/verts_as_matrices

**Comment by zeffii** [comment] 2017-01-01 02:02
Perhaps this needs to be set in SvSetSocket instead..

**Comment by zeffii** [comment] 2017-01-01 02:10
viewer_draw_mk2 kind of expects the socket connected to the matrix socket, to me of type matrix...
https://github.com/nortikin/sverchok/tree/verts_as_matrices

needs a small fix too

**Comment by zeffii** [comment] 2017-01-01 02:14
![image](https://cloud.githubusercontent.com/assets/619340/21579967/68e9eb7a-cfd0-11e6-9309-15830746f5aa.png)

**Comment by zeffii** [comment] 2017-01-01 02:16
I think we took out most of these checks ( check if input socket was of correct type ) about 2 years ago.. any that remain should be easy to track down..

**Comment by zeffii** [comment] 2017-01-01 10:40
![image](https://cloud.githubusercontent.com/assets/619340/21580887/1ec76486-d017-11e6-9980-1a998db1addf.png)

@nortikin  want to try it ? see if it breaks older layouts?

**Comment by zeffii** [comment] 2017-01-01 10:41
https://github.com/nortikin/sverchok/tree/verts_as_matrices

**Comment by Kosvor2** [comment] 2017-01-01 18:42
Seems ok. I thought you were going to get rid of all sockets checks. That would be cool.

![rid_off_checks](https://cloud.githubusercontent.com/assets/22656834/21582478/3ce26d00-d06a-11e6-98b6-823a97086ae9.png)

**Comment by zeffii** [comment] 2017-01-01 19:14
>  I thought you were going to get rid of all sockets checks.

@Kosvor2   i'm more a fan of incremental modifications :)   i need more feedback from you coders, extra set of eyes and brains :)

**Comment by zeffii** [comment] 2017-01-01 19:15
@Kosvor2  btw, if you find any blatant socket tests that could be more lenient let me know here or in a new thread.

**Comment by zeffii** [comment] 2017-01-01 19:15
![thesegif](https://cloud.githubusercontent.com/assets/619340/21582602/09abe85e-d05f-11e6-96d5-f8977fc92f86.gif)

**Comment by Kosvor2** [comment] 2017-01-01 23:09
I have deleted all the `check_origin()` stuff from viewer_mk2.py and cant produce any crush.

**Comment by zeffii** [comment] 2017-01-02 08:32
With the vdmk2 i'm inclined to be more cautious than strictly needed, but most other nodes should not have the tests...

Maybe the vdmk2 restriction prohibits some freeform node usage, there are solutions to ensure all incoming StringsSocket data is really vertex data, then accept it..else reject...

**Comment by ly29** [comment] 2017-01-03 11:40
The other way around could also be useful and logical, if matrix is plugged into vertices you get the locations.

**Comment by zeffii** [comment] 2017-01-03 13:20
yeah, M->V should be fine too..

**Comment by zeffii** [comment] 2017-01-03 14:35
incase the incoming M data is nested , I think perhaps a function is needed to scan through M and reproduce the same level of indentation on the other side..

```python

if not m:
    continue

get_all(m):
    for sublist in m:
        if is_matrix(sublist):
            v = get_loc_from_matrix(sublist)
        else:
            get_all(sublist)
````
undecided about how to keep track of the nestedness...  or maybe not bother.

**Comment by ly29** [comment] 2017-01-03 14:54
Since it is new feature make a note and make it simple.

**Comment by nortikin** [comment] 2017-01-04 19:17
i see we can merge. or not?

**Comment by zeffii** [comment] 2017-01-04 19:27
I'm OK for merging. if it breaks anything..it's easy enough to revert

**Comment by ly29** [comment] 2017-01-04 19:30
it shouldn't break anything anyway

**Comment by zeffii** [comment] 2017-01-04 19:50
it's pushed now. feel free to tweak :)

**Comment by ly29** [comment] 2017-01-04 20:12
Doing a short sprint with data structure :)

**Comment by zeffii** [comment] 2017-01-04 20:20
cool. I hope to find time later tomorrow.  busy :/

**Comment by zeffii** [comment] 2017-01-07 11:06
closing this for now. If there are question / enhancements needed for this feature , reopen / create new issue

**Closed by zeffii** 2017-01-07 11:06 UTC
Labels: enhancement, todo
