### ISSUE TITLE
Ellipse does not produce result / Cannot be baked

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2657] opened 2019-11-07 09:33 UTC
[weird_002.blend.zip](https://github.com/nortikin/sverchok/files/3818822/weird_002.blend.zip)
<img width="921" alt="Screen Shot 2019-11-07 at 8 31 11 pm" src="https://user-images.githubusercontent.com/3952687/68376973-b2d4b880-019d-11ea-9ceb-feb5760dc588.png">

I tried this using Blender 2.79.

Ellipse and Matrix Apply does not produce anything when "Bake" button is pressed. 

It does not work with Intersect Edge either for unknown reason.

**Comment by enzyme69** [comment] 2019-11-07 09:33
If I were to use just BMesh Output (2.80) it seems to work:

<img width="714" alt="Screen Shot 2019-11-07 at 8 33 19 pm" src="https://user-images.githubusercontent.com/3952687/68377059-d861c200-019d-11ea-9628-46ee3ee289c9.png">

**Comment by enzyme69** [comment] 2019-11-07 09:34
<img width="872" alt="Screen Shot 2019-11-07 at 8 34 14 pm" src="https://user-images.githubusercontent.com/3952687/68377156-01825280-019e-11ea-99e2-f60b6fa219f1.png">

And ... this way does not produce anything.

**Comment by enzyme69** [comment] 2019-11-07 09:36
ERROR:
`2019-11-07 20:33:51,830 [ERROR] sverchok.core.update_system: Node Viewer BMesh had exception: list index out of range
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/core/update_system.py", line 325, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/nodes/viz/viewer_bmesh.py", line 315, in process
    fullList(mverts, maxlen)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/data_structure.py", line 159, in fullList
    l.extend([l[-1] for a in range(d)])
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/data_structure.py", line 159, in <listcomp>
    l.extend([l[-1] for a in range(d)])
IndexError: list index out of range
2019-11-07 20:34:00,678 [ERROR] sverchok.core.update_system: Node Matrix Apply had exception: No data passed into socket 'Vertices'
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/core/update_system.py", line 325, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/nodes/matrix/apply_and_join.py", line 57, in process
    vertices = self.inputs['Vertices'].sv_get()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master-3/core/sockets.py", line 379, in sv_get
    raise SvNoDataError(self)
sverchok.core.socket_data.SvNoDataError: No data passed into socket 'Vertices'
something weird happened BMElemSeq[index]: index 864 out of range
something weird happened BMElemSeq[index]: index 864 out of range
is rendering frame 7, updates missed?
something weird happened BMElemSeq[index]: index 864 out of range
is rendering frame 8, updates missed?
something weird happened BMElemSeq[index]: index 864 out of range
is rendering frame 9, updates missed?
something weird happened BMElemSeq[index]: index 864 out of range
is rendering frame 10, updates missed?
something weird happened BMElemSeq[index]: index 864 out of range`

**Comment by enzyme69** [comment] 2019-11-07 09:40
This way works... that means something strange with Matrix Apply and Ellipse...

<img width="929" alt="Screen Shot 2019-11-07 at 8 39 41 pm" src="https://user-images.githubusercontent.com/3952687/68377568-bae12800-019e-11ea-8fbc-d7e852b3a4a8.png">

**Comment by enzyme69** [comment] 2019-11-07 09:48
This is my quick fix for now, seems to work. 
<img width="1042" alt="Screen Shot 2019-11-07 at 8 47 35 pm" src="https://user-images.githubusercontent.com/3952687/68378220-d567d100-019f-11ea-8a5d-71f90836ab7e.png">

The issue is with Ellipse, seems to make Edge list that's not usual.

**Comment by enzyme69** [comment] 2019-11-07 09:49
I am actually trying to make something like this:

Involving Intersect on and off, planar edge net or maybe merge mesh 2D or something else can do this?
<img width="434" alt="Screen Shot 2019-11-07 at 8 48 19 pm" src="https://user-images.githubusercontent.com/3952687/68378273-f03a4580-019f-11ea-8f18-d072457c6160.png">

**Comment by Durman** [comment] 2019-11-07 10:03
It looks like ellipse generator has some problem with mesh generation.
![2019-11-07_14-01-15](https://user-images.githubusercontent.com/28003269/68379378-2909f880-0167-11ea-9de5-ae15edadcaa8.png)

**Comment by Durman** [comment] 2019-11-07 10:13
`Merge mesh` node actually can to find intersections. But the problem is with dyeing the result. As I see number of overlapping with other polygons can do the job. But I did not expect that such information can be useful for someone.)) 

Actually it is not difficult to implement but difficult to find correct place for such specific output.
![2019-11-07_14-06-35](https://user-images.githubusercontent.com/28003269/68379719-d54bdf00-0167-11ea-8de1-4c7cf3edf931.png)

**Comment by zeffii** [comment] 2019-11-07 11:26
https://github.com/nortikin/sverchok/blob/c96a5497dd91166a392c8b4f1362e7f05d34a72b/nodes/generators_extended/ellipse.py#L212

```python
N = 6
>>> edges = list((i, (i + 1) % N) for i in range(N + 1))
>>> edges
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0), (6, 1)]
```
that should just be `range(N)`

**Comment by Durman** [comment] 2019-11-07 11:43
Interesting. It means the node have not been used by anyone until now?)))

**Comment by zeffii** [comment] 2019-11-07 12:37
probably no-one tried to Bake it from the Viewer node :)

the viewing node does extra checks before drawing, the baking code does not.

**Comment by Durman** [comment] 2019-11-07 12:52
I see that my algorithm is not precise with number of overlapping, strange.

![overlapping number test](https://user-images.githubusercontent.com/28003269/68390393-a42ad900-017e-11ea-9ca9-d4162607a79c.gif)

**Comment by zeffii** [comment] 2019-11-07 12:58
maybe intersections are happening exactly on the half edges

**Comment by zeffii** [comment] 2019-11-07 13:15
fixed in both 2.79 and 2.8+

**Closed by zeffii** 2019-11-07 13:15 UTC
Labels: bug

**Comment by Durman** [comment] 2019-11-26 12:49
@enzyme69 Update Sverchok from `b28_prelease_master` branch and try this:
https://gist.github.com/51d9e1f7dab90d7c898256c504c73726

![2019-11-26_16-48-31](https://user-images.githubusercontent.com/28003269/69634908-ad67e100-106c-11ea-94a3-106d73793521.png)

**Comment by enzyme69** [comment] 2019-11-26 23:18
@Durman This will work on Blender 2.81? Or only 2.79?

**Comment by enzyme69** [comment] 2019-11-26 23:46
Similar to Durman example with its magic chess SNL 

<img width="1383" alt="Screen Shot 2019-11-27 at 10 45 28 am" src="https://user-images.githubusercontent.com/3952687/69681718-0e41f880-1103-11ea-97db-13c91effbfad.png">

**Comment by Durman** [comment] 2019-11-27 04:05
> This will work on Blender 2.81? Or only 2.79?

It is for 2.8+ only.
