### ISSUE TITLE
CSG Boolean 2 node reports "float division by zero"

### ISSUE THREAD

**Issue by mnn** [nortikin/sverchok#3731] opened 2020-11-21 14:28 UTC
## Problem statement

It's possible I am doing something wrong. I didn't find any documentation for the node and looking at the optional dependencies document, I don't see this node being mentioned (I may have overlooked it though).

<img width="1601" alt="2020-11-21_14-47" src="https://user-images.githubusercontent.com/1975567/99879176-56f39b00-2c0b-11eb-8d44-d4f6884435b2.png">

The boolean node doesn't output any result and shows "float division by zero" error.

## Steps to reproduce

I am not sure how to reproduce the issue. In other cases the node seemed to work fine (just tried all operations on two boxes and all work). I am attaching a blend file - [04_grain_001.zip](https://github.com/nortikin/sverchok/files/5577751/04_grain_001.zip).

## Expected result

To get a difference between two meshes.

## Actual result

No result, shown error.

## Sverchok version

0.6.0.0
I believe it's the "stable Oktober 2020" v2, installed from inside Blender (Add-ons -> Install...)

Blender version: 2.90.1

---

Maybe related to #3430?

**Comment by mnn** [comment] 2020-11-21 14:34
Did some more testing:
* moving box to not have vertices with X/Y/Z equal to 0 didn't help
* swapping inputs of the node didn't have any effect

Also found a log output:

```py
2020-11-21 15:26:36,675 [ERROR] sverchok.core.update_system: Node CSG Boolean 2 had exception: float division by zero
Traceback (most recent call last):
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/nodes/modifier_make/csg_booleanMK2.py", line 118, in process
    out.append(Boolean(v1, p1, v2, p2, SMode))
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/nodes/modifier_make/csg_booleanMK2.py", line 29, in Boolean
    b = CSG.Obj_from_pydata(VB, PB)
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/utils/csg_core.py", line 84, in Obj_from_pydata
    polygons.append(CSGPolygon(polyg))
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/utils/csg_geom.py", line 227, in __init__
    self.plane = CSGPlane.fromPoints(
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/utils/csg_geom.py", line 132, in fromPoints
    n = b.minus(a).cross(c.minus(a)).unit()
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/utils/csg_geom.py", line 49, in unit
    return self.dividedBy(self.length())
  File "/home/xxx/.config/blender/2.90/scripts/addons/sverchok-vstable2/utils/csg_geom.py", line 36, in dividedBy
    return CSGVector(self.x / a, self.y / a, self.z / a)
ZeroDivisionError: float division by zero
```

**Comment by mnn** [comment] 2020-11-21 14:56
Found the problem - the ellipsoid mesh wasn't closed (top vertex was generated multiple times for each face, not connected). Adding `Merge By Distance` fixed it for me. I am not sure if I should close this GH issue, I think the boolean node should show a better error message. Something like `input mesh not closed` instead of `float division by zero` (I spent half an hour solving this triviality).

**Comment by zeffii** [comment] 2020-11-21 15:41
glad you found the cause, a non-manifold mesh will generally be the problem when this node misbehaves. agreed, better error messages would be appreciated, more new-user friendly. no argument there.

we have no documentation for this node? yikes. it may not be so simple or efficient to return a different error message there

**Comment by zeffii** [comment] 2020-11-22 18:38
prelim CSG_Boolean node doc.

-----------------
csg_boolean_mk2.rst


csg boolean mk2
===========

This node implements the 3 boolean *3d Mesh* functions; Intersect, Join, Difference. It uses a library taken from  Evan Wallace and ported to Python by Tim Knip. The original license of the library is this MIT.
```
   ## License
    Copyright (c) 2011 Evan Wallace (http://madebyevan.com/), under the MIT license.
    Python port Copyright (c) 2012 Tim Knip (http://www.floorplanner.com), under the MIT license.
```
This Boolean implementation is by no means fast, nor does it generate optimal output geometry. It is however often "correct". There are operational limitations to be aware of.

- the algorithm expects the input meshes to be both outward facing
- expects input meshes to be manifold ( no holes.. and also no intersecting or (self)overlapping geometry)
- co planar faces will result in undetermined output
- edges on one mesh should not be in the same 3d space as a face on the other mesh.

Functions
-----------

a feature was added to allow an iterative boolean, that performs those functions of multiple input objects.

**Comment by zeffii** [comment] 2020-11-22 19:38
I don't think we'll be editing this node's code much, and the prospect of having booleans handled by geometry_nodes in the near future, further makes it even less likely.

closing the issue ( choosing a different battle, dying on a different hill )

**Closed by zeffii** 2020-11-22 19:38 UTC
