### ISSUE TITLE
Obj instancer MK2 doing nothing (Obj Socket Broken when not linked? )

### ISSUE THREAD

**Issue by DarioMazzanti** [nortikin/sverchok#3080] opened 2020-04-16 16:03 UTC
## Problem statement
I am trying to use the Obj instancer MK2 node in order to instantiate multiple times a simple cube I have in my scene. The cube only has vertex color data and custom pivot.
If I use other nodes, such as mesh instancer, the nodes work, but the vertex color data is not included. That's why I am trying to use the Obj instancer.

Please note this is the first time I use Sverchok.

Thanks!

## Steps to reproduce

1. Create an Obj instancer MK2 node 
2. Input a matrix and select the object you want to instantiate ( I do that from my scene)
3. Nothing happens in 3D view.

## Expected result

Copies of the referenced object should appear in 3D view.

## Actual result

Nothing happens in 3D view.

## Sverchok version
I installed Sverchok as described in README.md file. Also tried to update.

**Comment by zeffii** [comment] 2020-04-16 18:33
i can confirm, thanks for the report.

**Comment by zeffii** [comment] 2020-04-16 18:35
lol..
```python
    def get_objects(self):
        if self.inputs['objects'].is_linked:
            return dataCorrect(self.inputs['objects'].sv_get())
        return []
```
it expects the objects socket to be linked, or it won't even do `sv_get()` .

**Comment by zeffii** [comment] 2020-04-16 18:35
in my defence , i only use this node by passing it the output out the `Scene/Objects In`  node.  

will fix .asap.

**Comment by zeffii** [comment] 2020-04-16 18:39
but, i'm not sure if the instancing will carry over vertex_colors - i'd be surprised - but can ofcourse be fixed too.

**Comment by zeffii** [comment] 2020-04-16 19:08
@portnov  whats going on?  `self.inputs['objects'].sv_get()`  should return an object if the dropdown has filled "object_ref" right?

**Comment by zeffii** [comment] 2020-04-16 19:12
@DarioMazzanti 

this should work
![image](https://user-images.githubusercontent.com/619340/79496754-dfcba800-8026-11ea-8542-743a3f1d53a7.png)

i'm not sure when this became 'broken' .

**Comment by zeffii** [comment] 2020-04-16 19:50
woah.. looks like
```
>>> n.inputs[0].object_ref
'   Cube.001'

```
because we're using prop_search, now  a space is inserted??

**Comment by zeffii** [comment] 2020-04-16 20:11
![image](https://user-images.githubusercontent.com/619340/79501976-3e951f80-802f-11ea-8287-f660ff9a307c.png)

**Comment by zeffii** [comment] 2020-04-16 20:16
https://github.com/nortikin/sverchok/pull/3081

while one issue is partially resolved (at least in the sense that the location of the bug is now known), we will need to implement a more permanent solution.

additionally, vertex_colours are not transferred @DarioMazzanti . yet.

**Closed** 2020-04-16 20:16 UTC
Labels: bug, high priority, maintenance

**Comment by zeffii** [comment] 2020-04-16 20:24
@portnov @vicdoval @Durman 
https://developer.blender.org/T58641

what the actual fuck.

**Comment by zeffii** [comment] 2020-04-16 20:27
```
>>> obj.name
'Cube.001'

>>> obj.name_full
'Cube.001'

```

**Comment by DarioMazzanti** [comment] 2020-04-20 08:51
@zeffii thanks so much for investigating this!

**Comment by zeffii** [comment] 2020-04-20 09:21
ok, my mistake, it does transfer vertex colors

![image](https://user-images.githubusercontent.com/619340/79735788-1c362700-82f9-11ea-95b2-a43f4823d93a.png)
